#!/bin/bash

PREF="/var/mobile/Library/Preferences/com.nito.pubc.plist"

if [ ! -f $PREF ] ; then

     /bin/mv $PREF.og $PREF
     /bin/chown mobile:mobile $PREF
fi

/usr/bin/killall -9 ShadowTrackerExtra

