//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, UIViewController;

@interface ABaseApplication : NSObject
{
    NSMutableArray *_observers;	// 8 = 0x8
    UIViewController *_rootVC;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x0000000100017aac
@property(retain, nonatomic) UIViewController *rootVC; // @synthesize rootVC=_rootVC;
@property(retain, nonatomic) NSMutableArray *observers; // @synthesize observers=_observers;
- (void).cxx_destruct;	// IMP=0x0000000100018cb8
- (void)foreachObserver:(CDUnknownBlockType)arg1;	// IMP=0x0000000100018aa0
- (void)removeObserver:(id)arg1;	// IMP=0x000000010001895c
- (void)addObserver:(id)arg1;	// IMP=0x00000001000187d4
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;	// IMP=0x000000010001865c
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;	// IMP=0x00000001000184e4
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;	// IMP=0x000000010001836c
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x00000001000181f0
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x0000000100018108
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x0000000100018020
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x0000000100017f38
- (void)applicationWillEnterForeground:(id)arg1;	// IMP=0x0000000100017e50
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x0000000100017d68
- (_Bool)handleOpenURL:(id)arg1;	// IMP=0x0000000100017c7c
- (void)dealloc;	// IMP=0x0000000100017c44
- (id)init;	// IMP=0x0000000100017b64

@end

