//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface ADJActivityPackage : NSObject <NSCoding>
{
    int _activityKind;	// 8 = 0x8
    NSString *_path;	// 16 = 0x10
    NSString *_clientSdk;	// 24 = 0x18
    long long _retries;	// 32 = 0x20
    NSMutableDictionary *_parameters;	// 40 = 0x28
    NSDictionary *_partnerParameters;	// 48 = 0x30
    NSDictionary *_callbackParameters;	// 56 = 0x38
    NSString *_suffix;	// 64 = 0x40
}

@property(nonatomic) int activityKind; // @synthesize activityKind=_activityKind;
@property(copy, nonatomic) NSString *suffix; // @synthesize suffix=_suffix;
@property(retain, nonatomic) NSDictionary *callbackParameters; // @synthesize callbackParameters=_callbackParameters;
@property(retain, nonatomic) NSDictionary *partnerParameters; // @synthesize partnerParameters=_partnerParameters;
@property(retain, nonatomic) NSMutableDictionary *parameters; // @synthesize parameters=_parameters;
@property(nonatomic) long long retries; // @synthesize retries=_retries;
@property(copy, nonatomic) NSString *clientSdk; // @synthesize clientSdk=_clientSdk;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;	// IMP=0x00000001007758ac
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001007755a0
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100775360
- (id)failureMessage;	// IMP=0x00000001007752a0
- (id)successMessage;	// IMP=0x00000001007751e0
- (id)description;	// IMP=0x0000000100775120
- (long long)increaseRetries;	// IMP=0x00000001007750d8
- (long long)getRetries;	// IMP=0x00000001007750cc
- (id)extendedString;	// IMP=0x0000000100774de0

@end

