//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ADJLogger.h"

@interface ADJLogger : NSObject <ADJLogger>
{
    _Bool _logLevelLocked;	// 8 = 0x8
    _Bool _isProductionEnvironment;	// 9 = 0x9
    int _loglevel;	// 12 = 0xc
}

+ (int)logLevelFromString:(id)arg1;	// IMP=0x0000000100777e78
@property(nonatomic) _Bool isProductionEnvironment; // @synthesize isProductionEnvironment=_isProductionEnvironment;
@property(nonatomic) _Bool logLevelLocked; // @synthesize logLevelLocked=_logLevelLocked;
@property(nonatomic) int loglevel; // @synthesize loglevel=_loglevel;
- (void)logLevel:(id)arg1 format:(id)arg2 parameters:(char *)arg3;	// IMP=0x0000000100777cc4
- (void)assert:(id)arg1;	// IMP=0x0000000100777c38
- (void)error:(id)arg1;	// IMP=0x0000000100777bac
- (void)warnInProduction:(id)arg1;	// IMP=0x0000000100777b34
- (void)warn:(id)arg1;	// IMP=0x0000000100777aa8
- (void)info:(id)arg1;	// IMP=0x0000000100777a1c
- (void)debug:(id)arg1;	// IMP=0x0000000100777990
- (void)verbose:(id)arg1;	// IMP=0x0000000100777904
- (void)lockLogLevel;	// IMP=0x00000001007778f4
- (void)setLogLevel:(int)arg1 isProductionEnvironment:(_Bool)arg2;	// IMP=0x000000010077788c
- (id)init;	// IMP=0x00000001007777ec

@end

