//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ADJResponseData.h"

@interface ADJSessionResponseData : ADJResponseData
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010078a554
- (id)failureResponseData;	// IMP=0x000000010078a408
- (id)successResponseData;	// IMP=0x000000010078a2e0
- (id)initWithActivityPackage:(id)arg1;	// IMP=0x000000010078a278

@end

