//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"
#import "NSURLSessionDataDelegate.h"
#import "NSURLSessionTaskDelegate.h"

@class NSMutableURLRequest, NSOperationQueue, NSString, NSURLConnection, NSURLSession, NSURLSessionDataTask;

@interface AVURLRequest : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate, NSURLSessionDataDelegate, NSURLSessionTaskDelegate>
{
    struct AVHttpResponse response_;	// 8 = 0x8
    void *_delegate;	// 96 = 0x60
    NSString *_getFilepath;	// 104 = 0x68
    NSString *_postFilepath;	// 112 = 0x70
    NSMutableURLRequest *_request;	// 120 = 0x78
    NSURLConnection *_conn;	// 128 = 0x80
    NSURLSession *_defaultSession;	// 136 = 0x88
    NSURLSessionDataTask *_requestTask;	// 144 = 0x90
    NSOperationQueue *_queue;	// 152 = 0x98
}

+ (id)requestWithURL:(id)arg1 timeout:(int)arg2;	// IMP=0x0000000101189f40
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSURLSessionDataTask *requestTask; // @synthesize requestTask=_requestTask;
@property(retain, nonatomic) NSURLSession *defaultSession; // @synthesize defaultSession=_defaultSession;
@property(retain, nonatomic) NSURLConnection *conn; // @synthesize conn=_conn;
@property(retain, nonatomic) NSMutableURLRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) NSString *postFilepath; // @synthesize postFilepath=_postFilepath;
@property(retain, nonatomic) NSString *getFilepath; // @synthesize getFilepath=_getFilepath;
@property(nonatomic) void *delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;	// IMP=0x000000010118c59c
- (void).cxx_destruct;	// IMP=0x000000010118c4e8
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(id)arg1;	// IMP=0x000000010118c3c0
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010118c094
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;	// IMP=0x000000010118c06c
- (void)URLSession:(id)arg1 dataTask:(id)arg2 willCacheResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010118c01c
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;	// IMP=0x000000010118be24
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didBecomeStreamTask:(id)arg3;	// IMP=0x000000010118bdcc
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didBecomeDownloadTask:(id)arg3;	// IMP=0x000000010118bd74
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010118ba50
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x000000010118b968
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;	// IMP=0x000000010118b964
- (void)URLSession:(id)arg1 task:(id)arg2 needNewBodyStream:(CDUnknownBlockType)arg3;	// IMP=0x000000010118b90c
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010118b4c0
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x000000010118b470
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;	// IMP=0x000000010118b458
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;	// IMP=0x000000010118b454
- (void)connectionDidFinishLoading:(id)arg1;	// IMP=0x000000010118b404
- (void)connection:(id)arg1 didReceiveData:(id)arg2;	// IMP=0x000000010118b20c
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;	// IMP=0x000000010118af30
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;	// IMP=0x000000010118af18
- (void)connection:(id)arg1 didCancelAuthenticationChallenge:(id)arg2;	// IMP=0x000000010118af14
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;	// IMP=0x000000010118ae90
- (_Bool)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;	// IMP=0x000000010118ae88
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;	// IMP=0x000000010118ab80
- (_Bool)connectionShouldUseCredentialStorage:(id)arg1;	// IMP=0x000000010118ab78
- (void)connection:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x000000010118aab4
- (void)setBody:(id)arg1;	// IMP=0x000000010118aa28
- (void)addHead:(id)arg1 withValue:(id)arg2;	// IMP=0x000000010118a974
- (id)readFromFile:(id)arg1;	// IMP=0x000000010118a8ec
- (_Bool)write2File:(id)arg1 data:(id)arg2;	// IMP=0x000000010118a858
- (void)sendMain;	// IMP=0x000000010118a520
- (void)quit;	// IMP=0x000000010118a500
- (void)sendRequest;	// IMP=0x000000010118a4f4
- (void)setMethod:(id)arg1;	// IMP=0x000000010118a3e8
- (id)initWithURL:(id)arg1 timeout:(int)arg2;	// IMP=0x000000010118a08c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

