//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSRequest.h"

@class NSNumber, NSString;

@interface AWSCognitoIdentityLookupDeveloperIdentityInput : AWSRequest
{
    NSString *_developerUserIdentifier;	// 8 = 0x8
    NSString *_identityId;	// 16 = 0x10
    NSString *_identityPoolId;	// 24 = 0x18
    NSNumber *_maxResults;	// 32 = 0x20
    NSString *_nextToken;	// 40 = 0x28
}

+ (id)JSONKeyPathsByPropertyKey;	// IMP=0x0000000100be03cc
@property(retain, nonatomic) NSString *nextToken; // @synthesize nextToken=_nextToken;
@property(retain, nonatomic) NSNumber *maxResults; // @synthesize maxResults=_maxResults;
@property(retain, nonatomic) NSString *identityPoolId; // @synthesize identityPoolId=_identityPoolId;
@property(retain, nonatomic) NSString *identityId; // @synthesize identityId=_identityId;
@property(retain, nonatomic) NSString *developerUserIdentifier; // @synthesize developerUserIdentifier=_developerUserIdentifier;
- (void).cxx_destruct;	// IMP=0x0000000100be055c

@end

