//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSRequest.h"

@class NSDictionary, NSNumber, NSString;

@interface AWSCognitoIdentityGetOpenIdTokenForDeveloperIdentityInput : AWSRequest
{
    NSString *_identityId;	// 8 = 0x8
    NSString *_identityPoolId;	// 16 = 0x10
    NSDictionary *_logins;	// 24 = 0x18
    NSNumber *_tokenDuration;	// 32 = 0x20
}

+ (id)JSONKeyPathsByPropertyKey;	// IMP=0x0000000100bdf144
@property(retain, nonatomic) NSNumber *tokenDuration; // @synthesize tokenDuration=_tokenDuration;
@property(retain, nonatomic) NSDictionary *logins; // @synthesize logins=_logins;
@property(retain, nonatomic) NSString *identityPoolId; // @synthesize identityPoolId=_identityPoolId;
@property(retain, nonatomic) NSString *identityId; // @synthesize identityId=_identityId;
- (void).cxx_destruct;	// IMP=0x0000000100bdf298

@end

