//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface AWSCognitoIdentityResources : NSObject
{
    NSDictionary *_definitionDictionary;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x0000000100be68b8
@property(retain, nonatomic) NSDictionary *definitionDictionary; // @synthesize definitionDictionary=_definitionDictionary;
- (void).cxx_destruct;	// IMP=0x0000000100be6b10
- (id)definitionString;	// IMP=0x0000000100be6ac0
- (id)init;	// IMP=0x0000000100be6938
- (id)JSONObject;	// IMP=0x0000000100be692c

@end

