//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AWSExecutor : NSObject
{
    CDUnknownBlockType _block;	// 8 = 0x8
}

+ (id)executorWithOperationQueue:(id)arg1;	// IMP=0x0000000100b8e9a8
+ (id)executorWithDispatchQueue:(id)arg1;	// IMP=0x0000000100b8e8ec
+ (id)executorWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100b8e888
+ (id)mainThreadExecutor;	// IMP=0x0000000100b8e75c
+ (id)immediateExecutor;	// IMP=0x0000000100b8e694
+ (id)defaultExecutor;	// IMP=0x0000000100b8e4f4
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;	// IMP=0x0000000100b8ebd0
- (void)execute:(CDUnknownBlockType)arg1;	// IMP=0x0000000100b8eb4c
- (id)initWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100b8eab8

@end

