//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AWSJSONParser : NSObject
{
}

+ (id)serializeMember:(id)arg1 value:(id)arg2 target:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100b7c260
+ (id)serializeMap:(id)arg1 values:(id)arg2 target:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100b7c048
+ (id)serializeList:(id)arg1 values:(id)arg2 target:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100b7be5c
+ (id)serializeStructure:(id)arg1 values:(id)arg2 target:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100b7bbdc
+ (id)findMemberName:(id)arg1 structureRules:(id)arg2;	// IMP=0x0000000100b7b9c8
+ (id)dictionaryForJsonData:(id)arg1 response:(id)arg2 actionName:(id)arg3 serviceDefinitionRule:(id)arg4 error:(id *)arg5;	// IMP=0x0000000100b7b398
+ (_Bool)failWithCode:(long long)arg1 description:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100b7b290

@end

