//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AWSKSReachability : NSObject
{
    _Bool _reachable;	// 8 = 0x8
    _Bool _WWANOnly;	// 9 = 0x9
    _Bool _initialized;	// 10 = 0xa
    unsigned int _flags;	// 12 = 0xc
    CDUnknownBlockType _onInitializationComplete;	// 16 = 0x10
    CDUnknownBlockType _onReachabilityChanged;	// 24 = 0x18
    struct __SCNetworkReachability *_reachabilityRef;	// 32 = 0x20
    NSString *_hostname;	// 40 = 0x28
    NSString *_notificationName;	// 48 = 0x30
}

+ (id)reachabilityToInternet;	// IMP=0x0000000100bd8e68
+ (id)reachabilityToLocalNetwork;	// IMP=0x0000000100bd8dec
+ (id)reachabilityToHost:(id)arg1;	// IMP=0x0000000100bd8d88
@property _Bool initialized; // @synthesize initialized=_initialized;
@property(retain, nonatomic) NSString *notificationName; // @synthesize notificationName=_notificationName;
@property(retain, nonatomic) NSString *hostname; // @synthesize hostname=_hostname;
@property(nonatomic) struct __SCNetworkReachability *reachabilityRef; // @synthesize reachabilityRef=_reachabilityRef;
@property(nonatomic) _Bool WWANOnly; // @synthesize WWANOnly=_WWANOnly;
@property(nonatomic) _Bool reachable; // @synthesize reachable=_reachable;
@property(nonatomic) unsigned int flags; // @synthesize flags=_flags;
@property(copy) CDUnknownBlockType onReachabilityChanged; // @synthesize onReachabilityChanged=_onReachabilityChanged;
- (void).cxx_destruct;	// IMP=0x0000000100bd99e0
- (void)onReachabilityFlagsChanged:(unsigned int)arg1;	// IMP=0x0000000100bd960c
- (void)callInitializationComplete;	// IMP=0x0000000100bd957c
@property(copy) CDUnknownBlockType onInitializationComplete; // @synthesize onInitializationComplete=_onInitializationComplete;
- (_Bool)isReachableWWANOnlyWithFlags:(unsigned int)arg1;	// IMP=0x0000000100bd93c4
- (_Bool)isReachableWithFlags:(unsigned int)arg1;	// IMP=0x0000000100bd9390
- (id)extractHostName:(id)arg1;	// IMP=0x0000000100bd92e8
- (void)dealloc;	// IMP=0x0000000100bd9268
- (id)initWithReachabilityRef:(struct __SCNetworkReachability *)arg1 hostname:(id)arg2;	// IMP=0x0000000100bd9030
- (id)initWithAddress:(const struct sockaddr *)arg1;	// IMP=0x0000000100bd8fec
- (id)initWithHost:(id)arg1;	// IMP=0x0000000100bd8ed4

@end

