//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSMTLModel.h"

#import "AWSMTLJSONSerializing.h"

@interface AWSModel : AWSMTLModel <AWSMTLJSONSerializing>
{
}

+ (id)JSONKeyPathsByPropertyKey;	// IMP=0x0000000100b99940
- (id)dictionaryValue;	// IMP=0x0000000100b99948

@end

