//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSDictionary;

@interface AWSMTLModel : NSObject <NSCoding, NSCopying>
{
}

+ (id)propertyKeys;	// IMP=0x0000000100ba76b0
+ (void)enumeratePropertiesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100ba7538
+ (id)modelWithDictionary:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100ba712c
+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100b80ec0
+ (id)allowedSecureCodingClassesByPropertyKey;	// IMP=0x0000000100b7fed0
+ (id)encodingBehaviorsByPropertyKey;	// IMP=0x0000000100b7fc68
+ (unsigned long long)modelVersion;	// IMP=0x0000000100b7fc60
+ (id)dictionaryValueFromArchivedExternalRepresentation:(id)arg1 version:(unsigned long long)arg2;	// IMP=0x0000000100b80ec8
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100ba8088
- (unsigned long long)hash;	// IMP=0x0000000100ba7f1c
- (id)description;	// IMP=0x0000000100ba7e84
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100ba7e00
- (_Bool)validate:(id *)arg1;	// IMP=0x0000000100ba7c74
- (void)mergeValuesForKeysFromModel:(id)arg1;	// IMP=0x0000000100ba7ad0
- (void)mergeValueForKey:(id)arg1 fromModel:(id)arg2;	// IMP=0x0000000100ba7944
@property(readonly, copy, nonatomic) NSDictionary *dictionaryValue;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100ba71d0
- (id)init;	// IMP=0x0000000100ba7198
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100b80b4c
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100b80594
- (id)decodeValueForKey:(id)arg1 withCoder:(id)arg2 modelVersion:(unsigned long long)arg3;	// IMP=0x0000000100b8025c

@end

