//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSModel.h"

@class NSString;

@interface AWSS3AnalyticsS3BucketDestination : AWSModel
{
    NSString *_bucket;	// 8 = 0x8
    NSString *_bucketAccountId;	// 16 = 0x10
    long long _format;	// 24 = 0x18
    NSString *_prefix;	// 32 = 0x20
}

+ (id)formatJSONTransformer;	// IMP=0x0000000100bf7090
+ (id)JSONKeyPathsByPropertyKey;	// IMP=0x0000000100bf6fcc
@property(retain, nonatomic) NSString *prefix; // @synthesize prefix=_prefix;
@property(nonatomic) long long format; // @synthesize format=_format;
@property(retain, nonatomic) NSString *bucketAccountId; // @synthesize bucketAccountId=_bucketAccountId;
@property(retain, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
- (void).cxx_destruct;	// IMP=0x0000000100bf71f4

@end

