//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSModel.h"

@class AWSS3Owner, NSArray;

@interface AWSS3GetObjectAclOutput : AWSModel
{
    NSArray *_grants;	// 8 = 0x8
    AWSS3Owner *_owner;	// 16 = 0x10
    long long _requestCharged;	// 24 = 0x18
}

+ (id)requestChargedJSONTransformer;	// IMP=0x0000000100c010a4
+ (id)ownerJSONTransformer;	// IMP=0x0000000100c01060
+ (id)grantsJSONTransformer;	// IMP=0x0000000100c0101c
+ (id)JSONKeyPathsByPropertyKey;	// IMP=0x0000000100c00f70
@property(nonatomic) long long requestCharged; // @synthesize requestCharged=_requestCharged;
@property(retain, nonatomic) AWSS3Owner *owner; // @synthesize owner=_owner;
@property(retain, nonatomic) NSArray *grants; // @synthesize grants=_grants;
- (void).cxx_destruct;	// IMP=0x0000000100c011e4

@end

