//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSNetworkingConfiguration.h"

@class AWSEndpoint, NSArray, NSString;

@interface AWSServiceConfiguration : AWSNetworkingConfiguration
{
    long long _regionType;	// 8 = 0x8
    id <AWSCredentialsProvider> _credentialsProvider;	// 16 = 0x10
    AWSEndpoint *_endpoint;	// 24 = 0x18
    NSArray *_userAgentProductTokens;	// 32 = 0x20
}

+ (void)addGlobalUserAgentProductToken:(id)arg1;	// IMP=0x0000000100bdabbc
+ (id)baseUserAgent;	// IMP=0x0000000100bda830
@property(retain, nonatomic) NSArray *userAgentProductTokens; // @synthesize userAgentProductTokens=_userAgentProductTokens;
@property(retain, nonatomic) AWSEndpoint *endpoint; // @synthesize endpoint=_endpoint;
@property(retain, nonatomic) id <AWSCredentialsProvider> credentialsProvider; // @synthesize credentialsProvider=_credentialsProvider;
@property(nonatomic) long long regionType; // @synthesize regionType=_regionType;
- (void).cxx_destruct;	// IMP=0x0000000100bdb1a8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100bdaffc
- (void)addUserAgentProductToken:(id)arg1;	// IMP=0x0000000100bdae38
@property(readonly, nonatomic) NSString *userAgent;
- (id)initWithRegion:(long long)arg1 endpoint:(id)arg2 credentialsProvider:(id)arg3;	// IMP=0x0000000100bda7ac
- (id)initWithRegion:(long long)arg1 credentialsProvider:(id)arg2;	// IMP=0x0000000100bda718
- (id)init;	// IMP=0x0000000100bda6d4

@end

