//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BeaconEncodeObject.h"

@class NSString;

@interface BeaconIPSource : BeaconEncodeObject
{
    NSString *ip;	// 8 = 0x8
    long long port;	// 16 = 0x10
    int protocolType;	// 24 = 0x18
    _Bool isTest;	// 28 = 0x1c
    NSString *expRet;	// 32 = 0x20
    unsigned int cmd;	// 40 = 0x28
}

+ (id)initWithIP:(id)arg1 port:(long long)arg2;	// IMP=0x00000001007c4444
@property(nonatomic) _Bool isTest; // @synthesize isTest;
@property(nonatomic) int protocolType; // @synthesize protocolType;
@property(nonatomic) unsigned int cmd; // @synthesize cmd;
@property(nonatomic) long long port; // @synthesize port;
@property(retain, nonatomic) NSString *expRet; // @synthesize expRet;
@property(retain, nonatomic) NSString *ip; // @synthesize ip;
- (void).cxx_destruct;	// IMP=0x00000001007c4864
- (void)dealloc;	// IMP=0x00000001007c46e8
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001007c45e0
- (id)initWithWUPIPModel:(id)arg1;	// IMP=0x00000001007c44d0

@end

