//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BeaconJceObjectV2.h"

@class NSArray, NSDictionary, NSString;

@interface BeaconWupCommonStrategy : BeaconJceObjectV2
{
    int _jcev2_p_1_r_queryInterval;	// 8 = 0x8
    NSArray *_jcev2_p_0_o_moduleList__b0x9i_VOBeaconWupModuleStrategy;	// 16 = 0x10
    NSString *_jcev2_p_2_o_url;	// 24 = 0x18
    NSDictionary *_jcev2_p_3_o_cloudParas__b0x9i_M09ONSStringONSString;	// 32 = 0x20
    NSDictionary *_jcev2_p_4_o_appLogParas__b0x9i_M09ONSStringONSString;	// 40 = 0x28
}

+ (id)jceType;	// IMP=0x00000001007ab21c
@property(retain, nonatomic, getter=jce_appLogParas, setter=setJce_appLogParas:) NSDictionary *jcev2_p_4_o_appLogParas__b0x9i_M09ONSStringONSString; // @synthesize jcev2_p_4_o_appLogParas__b0x9i_M09ONSStringONSString=_jcev2_p_4_o_appLogParas__b0x9i_M09ONSStringONSString;
@property(retain, nonatomic, getter=jce_cloudParas, setter=setJce_cloudParas:) NSDictionary *jcev2_p_3_o_cloudParas__b0x9i_M09ONSStringONSString; // @synthesize jcev2_p_3_o_cloudParas__b0x9i_M09ONSStringONSString=_jcev2_p_3_o_cloudParas__b0x9i_M09ONSStringONSString;
@property(retain, nonatomic, getter=jce_url, setter=setJce_url:) NSString *jcev2_p_2_o_url; // @synthesize jcev2_p_2_o_url=_jcev2_p_2_o_url;
@property(nonatomic, getter=jce_queryInterval, setter=setJce_queryInterval:) int jcev2_p_1_r_queryInterval; // @synthesize jcev2_p_1_r_queryInterval=_jcev2_p_1_r_queryInterval;
@property(retain, nonatomic, getter=jce_moduleList, setter=setJce_moduleList:) NSArray *jcev2_p_0_o_moduleList__b0x9i_VOBeaconWupModuleStrategy; // @synthesize jcev2_p_0_o_moduleList__b0x9i_VOBeaconWupModuleStrategy=_jcev2_p_0_o_moduleList__b0x9i_VOBeaconWupModuleStrategy;
- (void).cxx_destruct;	// IMP=0x00000001007ab388
- (id)init;	// IMP=0x00000001007ab104

@end

