//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BeaconSpeedUtil : NSObject
{
}

+ (id)getFullTimeStrBy:(double)arg1;	// IMP=0x00000001007e8bdc
+ (id)getFullTimeStr;	// IMP=0x00000001007e8b8c
+ (id)getFullTimeFileStrBy:(double)arg1;	// IMP=0x00000001007e8b24
+ (id)getFullTimeFileStr;	// IMP=0x00000001007e8ad4
+ (id)getDayTimeStrBy:(double)arg1;	// IMP=0x00000001007e8a78
+ (id)getDayTimeStr;	// IMP=0x00000001007e8a28

@end

