//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BeaconFilterUtil : NSObject
{
}

+ (id)trimEventParams:(id)arg1;	// IMP=0x00000001007d9240
+ (_Bool)validateEventName:(id)arg1;	// IMP=0x00000001007d90d8
+ (_Bool)validateUserID:(id)arg1;	// IMP=0x00000001007d8fec
+ (_Bool)validateChannelID:(id)arg1;	// IMP=0x00000001007d8fe0
+ (_Bool)parseBool:(id)arg1;	// IMP=0x00000001007d8f3c
+ (_Bool)isValidASC:(id)arg1;	// IMP=0x00000001007d8e9c
+ (id)trimString:(id)arg1 length:(int)arg2;	// IMP=0x00000001007d8e1c
+ (id)shareInstance;	// IMP=0x00000001007d8d68

@end

