//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface BeaconAppUsageEventReporter : NSObject
{
    _Bool _isReportCpuMem;	// 8 = 0x8
    NSMutableArray *_cpuList;	// 16 = 0x10
    NSMutableArray *_memoryList;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x00000001007b0134
@property(retain, nonatomic) NSMutableArray *memoryList; // @synthesize memoryList=_memoryList;
@property(retain, nonatomic) NSMutableArray *cpuList; // @synthesize cpuList=_cpuList;
@property(nonatomic) _Bool isReportCpuMem; // @synthesize isReportCpuMem=_isReportCpuMem;
- (void).cxx_destruct;	// IMP=0x00000001007b1704
- (void)clearCpuData;	// IMP=0x00000001007b1554
- (void)cacheCpuData;	// IMP=0x00000001007b13f8
- (void)recordCpuMem;	// IMP=0x00000001007b12d8
- (void)reportMemoryEvent:(id)arg1;	// IMP=0x00000001007b10e0
- (void)reportCpuEvent;	// IMP=0x00000001007b0e4c
- (_Bool)reportAppUsageEvent2;	// IMP=0x00000001007b09ec
- (_Bool)reportAppUsageEvent;	// IMP=0x00000001007b0928
- (void)stopAppUsageTask;	// IMP=0x00000001007b0774
- (void)startAppUsageReportTask;	// IMP=0x00000001007b0424
- (void)closeCpuCollect;	// IMP=0x00000001007b03b0
- (void)openCpuCollect;	// IMP=0x00000001007b01bc

@end

