//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BeaconZipUtil : NSObject
{
}

+ (id)gzipCompress:(id)arg1;	// IMP=0x00000001007ca3d0
+ (id)getBeaconZipUtil:(int)arg1;	// IMP=0x00000001007ca33c

@end

