//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BeaconJceObjectV2.h"

@class NSArray;

@interface BeaconWupEventRecordPackage : BeaconJceObjectV2
{
    NSArray *_jcev2_p_0_o_list__b0x9i_VOBeaconWupEventRecord;	// 8 = 0x8
}

+ (id)jceType;	// IMP=0x00000001007ab768
@property(retain, nonatomic, getter=jce_list, setter=setJce_list:) NSArray *jcev2_p_0_o_list__b0x9i_VOBeaconWupEventRecord; // @synthesize jcev2_p_0_o_list__b0x9i_VOBeaconWupEventRecord=_jcev2_p_0_o_list__b0x9i_VOBeaconWupEventRecord;
- (void).cxx_destruct;	// IMP=0x00000001007ab7dc
- (id)init;	// IMP=0x00000001007ab6e4

@end

