//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface BFMeasurementEvent : NSObject
{
    NSString *_name;	// 8 = 0x8
    NSDictionary *_args;	// 16 = 0x10
}

+ (void)postNotificationForEventName:(id)arg1 args:(id)arg2;	// IMP=0x00000001006a2e90
- (void).cxx_destruct;	// IMP=0x00000001006a2f20
- (id)initEventWithName:(id)arg1 args:(id)arg2;	// IMP=0x00000001006a2d8c
- (void)postNotification;	// IMP=0x00000001006a2c48

@end

