//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BFTask;

@interface BFTaskCompletionSource : NSObject
{
    BFTask *_task;	// 8 = 0x8
}

+ (id)taskCompletionSource;	// IMP=0x000000010069dd68
@property(readonly, nonatomic) BFTask *task; // @synthesize task=_task;
- (void).cxx_destruct;	// IMP=0x000000010069e23c
- (_Bool)trySetCancelled;	// IMP=0x000000010069e1e0
- (_Bool)trySetException:(id)arg1;	// IMP=0x000000010069e168
- (_Bool)trySetError:(id)arg1;	// IMP=0x000000010069e0f0
- (_Bool)trySetResult:(id)arg1;	// IMP=0x000000010069e078
- (void)cancel;	// IMP=0x000000010069e004
- (void)setException:(id)arg1;	// IMP=0x000000010069df64
- (void)setError:(id)arg1;	// IMP=0x000000010069dec4
- (void)setResult:(id)arg1;	// IMP=0x000000010069de24
- (id)init;	// IMP=0x000000010069dd90

@end

