//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLYJceObjectV2.h"

@class NSArray, NSString;

@interface BLYAppSession : BLYJceObjectV2
{
    NSString *jcev2_p_0_r_sessionId;	// 8 = 0x8
    NSArray *jcev2_p_1_o_events__b0x9i_VONSString;	// 16 = 0x10
}

+ (id)jceType;	// IMP=0x000000010073eaa0
+ (void)initialize;	// IMP=0x000000010073e9dc
@property(retain, nonatomic, getter=jce_events, setter=setJce_events:) NSArray *jcev2_p_1_o_events__b0x9i_VONSString; // @synthesize jcev2_p_1_o_events__b0x9i_VONSString;
@property(retain, nonatomic, getter=jce_sessionId, setter=setJce_sessionId:) NSString *jcev2_p_0_r_sessionId; // @synthesize jcev2_p_0_r_sessionId;
- (void).cxx_destruct;	// IMP=0x000000010073eb14
- (id)init;	// IMP=0x000000010073ea3c

@end

