//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"

@class NSMutableURLRequest, NSString, NSURLSessionDataTask;

@interface BLYHttpRequest : NSObject <NSURLConnectionDataDelegate, NSURLConnectionDelegate>
{
    CDUnknownBlockType _completionBlock;	// 8 = 0x8
    NSMutableURLRequest *_request;	// 16 = 0x10
    NSURLSessionDataTask *_dataTask;	// 24 = 0x18
    _Bool _loading;	// 32 = 0x20
}

@property(getter=isLoading) _Bool loading; // @synthesize loading=_loading;
@property(retain, nonatomic) NSURLSessionDataTask *dataTask; // @synthesize dataTask=_dataTask;
@property(retain, nonatomic) NSMutableURLRequest *request; // @synthesize request=_request;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;	// IMP=0x000000010075f748
- (void)cancel;	// IMP=0x000000010075f628
- (void)start;	// IMP=0x000000010075f558
- (void)sendUrlConnectionRequest;	// IMP=0x000000010075f308
- (id)initWithUrlRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010075efd0
- (id)stringByAddingPercentEncodingForFormData:(id)arg1;	// IMP=0x000000010075ee64
- (id)initWithUrlString:(id)arg1 requestData:(id)arg2 headerInfo:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010075ea24

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

