//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLYJceStream.h"

@class NSData;

@interface BLYJceInputStreamV2 : BLYJceStream
{
    int _headType;	// 24 = 0x18
    int _headTag;	// 28 = 0x1c
    NSData *_dataHolders;	// 32 = 0x20
}

+ (id)streamWithData:(id)arg1;	// IMP=0x000000010075a118
@property(retain, nonatomic) NSData *dataHolders; // @synthesize dataHolders=_dataHolders;
@property(readonly, nonatomic) int headTag; // @synthesize headTag=_headTag;
@property(nonatomic) int headType; // @synthesize headType=_headType;
- (void).cxx_destruct;	// IMP=0x000000010075c2b8
- (id)readAnything:(int)arg1 required:(_Bool)arg2 description:(id)arg3;	// IMP=0x000000010075bf80
- (id)readDictionary:(int)arg1 required:(_Bool)arg2 description:(id)arg3;	// IMP=0x000000010075bca4
- (id)readArray:(int)arg1 required:(_Bool)arg2 description:(id)arg3;	// IMP=0x000000010075ba54
- (id)readObject:(int)arg1 required:(_Bool)arg2 description:(Class)arg3;	// IMP=0x000000010075b4ac
- (id)readData:(int)arg1 required:(_Bool)arg2;	// IMP=0x000000010075b230
- (id)readString:(int)arg1 required:(_Bool)arg2;	// IMP=0x000000010075afc0
- (id)readNumber:(int)arg1 required:(_Bool)arg2;	// IMP=0x000000010075aca4
- (id)readDataWithSize:(int)arg1;	// IMP=0x000000010075ac64
- (void)skip:(unsigned int)arg1;	// IMP=0x000000010075ac2c
- (char *)readBytes:(unsigned int)arg1;	// IMP=0x000000010075ab00
- (double)readDouble;	// IMP=0x000000010075aaa0
- (float)readFloat;	// IMP=0x000000010075aa4c
- (double)readDouble:(int)arg1;	// IMP=0x000000010075a8b4
- (float)readFloat:(int)arg1;	// IMP=0x000000010075a708
- (long long)readInt:(int)arg1;	// IMP=0x000000010075a530
- (long long)readInt8;	// IMP=0x000000010075a488
- (int)readInt4;	// IMP=0x000000010075a434
- (short)readInt2;	// IMP=0x000000010075a3f4
- (BOOL)readInt1;	// IMP=0x000000010075a3c0
- (_Bool)readHead;	// IMP=0x000000010075a314
- (_Bool)peakHead;	// IMP=0x000000010075a280
- (id)data;	// IMP=0x000000010075a248
- (id)init;	// IMP=0x000000010075a1f0

@end

