//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BLYModule : NSObject
{
    NSString *_moduleName;	// 8 = 0x8
    Class _className;	// 16 = 0x10
}

@property(retain, nonatomic) Class className; // @synthesize className=_className;
@property(copy, nonatomic) NSString *moduleName; // @synthesize moduleName=_moduleName;
- (void).cxx_destruct;	// IMP=0x0000000100739f88
- (unsigned long long)hash;	// IMP=0x0000000100739f0c
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100739e64
- (id)description;	// IMP=0x0000000100739dbc
- (id)initWithClass:(Class)arg1;	// IMP=0x0000000100739cc8

@end

