//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLYAbstractModule.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface BLYMartianTracker : BLYAbstractModule
{
    _Bool _autoTrackingEnable;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_trackerQueue;	// 16 = 0x10
    NSMutableArray *_trackerMessages;	// 24 = 0x18
}

+ (void)trackPageView:(id)arg1;	// IMP=0x0000000100757c00
+ (id)trackLog;	// IMP=0x0000000100757b4c
+ (id)currentTimeString;	// IMP=0x0000000100757884
+ (id)constructSelector;	// IMP=0x00000001007572e4
+ (id)sharedTracker;	// IMP=0x0000000100757164
@property(retain, nonatomic) NSMutableArray *trackerMessages; // @synthesize trackerMessages=_trackerMessages;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *trackerQueue; // @synthesize trackerQueue=_trackerQueue;
@property(nonatomic, getter=isAutoTrackingEnabled) _Bool autoTrackingEnable; // @synthesize autoTrackingEnable=_autoTrackingEnable;
- (void).cxx_destruct;	// IMP=0x0000000100757de8
- (void)trackAppLifeCycleEvent:(id)arg1;	// IMP=0x0000000100757cd0
- (id)allLogs;	// IMP=0x0000000100757930
- (void)trackMessage:(id)arg1;	// IMP=0x00000001007575c8
- (void)didReceiveAppLifeCycleEvent:(id)arg1;	// IMP=0x00000001007574b4
- (void)registerAppLifeCycleEvents;	// IMP=0x000000010075744c
- (void)startTrack;	// IMP=0x00000001007573b0
- (id)init;	// IMP=0x00000001007572f0
- (_Bool)disableModule;	// IMP=0x000000010075728c
- (_Bool)enableModule;	// IMP=0x00000001007571fc

@end

