//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Bugly : NSObject
{
}

+ (void)setComponentIdentifier:(id)arg1 version:(id)arg2;	// IMP=0x000000010072e500
+ (_Bool)isAppCrashedOnStartUpExceedTheLimit;	// IMP=0x000000010072e4ac
+ (void)reportError:(id)arg1;	// IMP=0x000000010072e408
+ (void)reportException:(id)arg1;	// IMP=0x000000010072e364
+ (id)buglyDeviceId;	// IMP=0x000000010072e308
+ (id)sdkVersion;	// IMP=0x000000010072e2f4
+ (void)reportExceptionWithCategory:(unsigned long long)arg1 name:(id)arg2 reason:(id)arg3 callStack:(id)arg4 extraInfo:(id)arg5 terminateApp:(_Bool)arg6;	// IMP=0x000000010072e0e8
+ (unsigned long long)currentTag;	// IMP=0x000000010072e094
+ (id)allUserValues;	// IMP=0x000000010072e038
+ (void)setUserValue:(id)arg1 forKey:(id)arg2;	// IMP=0x000000010072dfac
+ (void)setTag:(unsigned long long)arg1;	// IMP=0x000000010072df5c
+ (void)updateAppVersion:(id)arg1;	// IMP=0x000000010072dedc
+ (void)setUserIdentifier:(id)arg1;	// IMP=0x000000010072de6c
+ (void)startWithConfig:(id)arg1;	// IMP=0x000000010072de50
+ (void)startWithAppId:(id)arg1 config:(id)arg2;	// IMP=0x000000010072ddfc
+ (void)startWithAppId:(id)arg1 developmentDevice:(_Bool)arg2 config:(id)arg3;	// IMP=0x000000010072d690
+ (unsigned long long)convert:(unsigned long long)arg1;	// IMP=0x000000010072d670
+ (void)startWithAppId:(id)arg1;	// IMP=0x000000010072d660

@end

