//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BuglyLog : NSObject
{
}

+ (void)level:(unsigned long long)arg1 tag:(id)arg2 log:(id)arg3;	// IMP=0x0000000100731b84
+ (void)level:(unsigned long long)arg1 log:(id)arg2;	// IMP=0x0000000100731a90
+ (void)level:(unsigned long long)arg1 logs:(id)arg2;	// IMP=0x00000001007319e0
+ (void)log:(id)arg1;	// IMP=0x000000010073190c
+ (void)initLogger:(unsigned long long)arg1 consolePrint:(_Bool)arg2;	// IMP=0x00000001007318c8
+ (unsigned long long)convert:(unsigned long long)arg1;	// IMP=0x00000001007318a8

@end

