//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSArray, NSString;

@interface FBSDKErrorRecoveryConfiguration : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_localizedRecoveryDescription;	// 8 = 0x8
    NSArray *_localizedRecoveryOptionDescriptions;	// 16 = 0x10
    unsigned long long _errorCategory;	// 24 = 0x18
    NSString *_recoveryActionName;	// 32 = 0x20
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001006c9c64
@property(readonly, nonatomic) NSString *recoveryActionName; // @synthesize recoveryActionName=_recoveryActionName;
@property(readonly, nonatomic) unsigned long long errorCategory; // @synthesize errorCategory=_errorCategory;
@property(readonly, nonatomic) NSArray *localizedRecoveryOptionDescriptions; // @synthesize localizedRecoveryOptionDescriptions=_localizedRecoveryOptionDescriptions;
@property(readonly, nonatomic) NSString *localizedRecoveryDescription; // @synthesize localizedRecoveryDescription=_localizedRecoveryDescription;
- (void).cxx_destruct;	// IMP=0x00000001006c9f38
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001006c9ef4
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001006c9dfc
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001006c9c6c
- (id)initWithRecoveryDescription:(id)arg1 optionDescriptions:(id)arg2 category:(unsigned long long)arg3 recoveryActionName:(id)arg4;	// IMP=0x00000001006c9b3c
- (id)init;	// IMP=0x00000001006c9a80

@end

