//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"

@class NSMutableData, NSString, NSURLConnection, NSURLResponse;

@interface FBSDKURLConnection : NSObject <NSURLConnectionDataDelegate>
{
    id <FBSDKURLConnectionDelegate> _delegate;	// 8 = 0x8
    NSURLConnection *_connection;	// 16 = 0x10
    NSMutableData *_data;	// 24 = 0x18
    CDUnknownBlockType _handler;	// 32 = 0x20
    NSURLResponse *_response;	// 40 = 0x28
    unsigned long long _requestStartTime;	// 48 = 0x30
    unsigned long long _loggerSerialNumber;	// 56 = 0x38
}

@property(readonly, nonatomic) unsigned long long loggerSerialNumber; // @synthesize loggerSerialNumber=_loggerSerialNumber;
@property(nonatomic) unsigned long long requestStartTime; // @synthesize requestStartTime=_requestStartTime;
@property(retain, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(retain, nonatomic) NSMutableData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(nonatomic) __weak id <FBSDKURLConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001006d5350
- (void)setDelegateQueue:(id)arg1;	// IMP=0x00000001006d524c
- (void)start;	// IMP=0x00000001006d5234
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;	// IMP=0x00000001006d51a8
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;	// IMP=0x00000001006d5190
- (void)connectionDidFinishLoading:(id)arg1;	// IMP=0x00000001006d5080
- (void)connection:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x00000001006d4ed4
- (void)connection:(id)arg1 didReceiveData:(id)arg2;	// IMP=0x00000001006d4e68
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;	// IMP=0x00000001006d4e0c
- (void)cancel;	// IMP=0x00000001006d4db4
- (void)logMessage:(id)arg1;	// IMP=0x00000001006d4d6c
- (void)invokeHandler:(CDUnknownBlockType)arg1 error:(id)arg2 response:(id)arg3 responseData:(id)arg4;	// IMP=0x00000001006d4cdc
- (void)logAndInvokeHandler:(CDUnknownBlockType)arg1 response:(id)arg2 responseData:(id)arg3;	// IMP=0x00000001006d4b0c
- (void)logAndInvokeHandler:(CDUnknownBlockType)arg1 error:(id)arg2;	// IMP=0x00000001006d49d8
- (id)init;	// IMP=0x00000001006d491c
- (id)initWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001006d47ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

