//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSDKAudioResourceLoader.h"

@interface FBSDKLikeButtonPopWAV : FBSDKAudioResourceLoader
{
}

+ (id)data;	// IMP=0x00000001006fddec
+ (id)name;	// IMP=0x00000001006fddc0

@end

