//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSDKSharingDialog.h"
#import "FBSDKWebDialogDelegate.h"

@class FBSDKWebDialog, NSString, UIViewController;

@interface FBSDKShareDialog : NSObject <FBSDKWebDialogDelegate, FBSDKSharingDialog>
{
    FBSDKWebDialog *_webDialog;	// 8 = 0x8
    _Bool _shouldFailOnDataError;	// 16 = 0x10
    id <FBSDKSharingDelegate> _delegate;	// 24 = 0x18
    id <FBSDKSharingContent> _shareContent;	// 32 = 0x20
    UIViewController *_fromViewController;	// 40 = 0x28
    unsigned long long _mode;	// 48 = 0x30
}

+ (id)showFromViewController:(id)arg1 withContent:(id)arg2 delegate:(id)arg3;	// IMP=0x00000001006fde88
+ (void)initialize;	// IMP=0x00000001006fde14
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(nonatomic) __weak UIViewController *fromViewController; // @synthesize fromViewController=_fromViewController;
@property(nonatomic) _Bool shouldFailOnDataError; // @synthesize shouldFailOnDataError=_shouldFailOnDataError;
@property(copy, nonatomic) id <FBSDKSharingContent> shareContent; // @synthesize shareContent=_shareContent;
@property(nonatomic) __weak id <FBSDKSharingDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001007030d8
- (id)_calculatePreJSONInitialTextWithHashtag:(id)arg1;	// IMP=0x0000000100702ef8
- (id)_calculateInitialText;	// IMP=0x0000000100702a24
- (void)_logDialogShow;	// IMP=0x0000000100702708
- (void)_invokeDelegateDidFailWithError:(id)arg1;	// IMP=0x0000000100702564
- (void)_invokeDelegateDidCompleteWithResults:(id)arg1;	// IMP=0x00000001007023dc
- (void)_invokeDelegateDidCancel;	// IMP=0x00000001007022a0
- (_Bool)_validateShareMediaContentAvailability:(id)arg1 error:(id *)arg2;	// IMP=0x00000001007021c0
- (_Bool)_validateVideoURL:(id)arg1 error:(id *)arg2;	// IMP=0x000000010070211c
- (_Bool)_validateShareContentForShareSheet:(id *)arg1;	// IMP=0x0000000100701cf4
- (_Bool)_validateShareContentForNative:(id *)arg1;	// IMP=0x0000000100701b70
- (_Bool)_validateShareContentForFeed:(id *)arg1;	// IMP=0x0000000100701a3c
- (_Bool)_validateShareContentForBrowser:(id *)arg1;	// IMP=0x000000010070182c
- (_Bool)_validateFullyCompatibleWithError:(id *)arg1;	// IMP=0x00000001007016cc
- (_Bool)_validateWithError:(id *)arg1;	// IMP=0x0000000100701468
- (_Bool)_useSafariViewController;	// IMP=0x00000001007013b0
- (_Bool)_useNativeDialog;	// IMP=0x00000001007012f8
- (_Bool)_showWeb:(id *)arg1;	// IMP=0x00000001007011d4
- (_Bool)_showShareSheetWithCanShowError:(id *)arg1 validationError:(id *)arg2;	// IMP=0x0000000100700b68
- (_Bool)_showNativeWithCanShowError:(id *)arg1 validationError:(id *)arg2;	// IMP=0x0000000100700630
- (_Bool)_showFeedWeb:(id *)arg1;	// IMP=0x0000000100700564
- (_Bool)_showFeedBrowser:(id *)arg1;	// IMP=0x00000001007002b0
- (_Bool)_showBrowser:(id *)arg1;	// IMP=0x00000001006ffc80
- (_Bool)_photoContentHasAtLeastOneImage:(id)arg1;	// IMP=0x00000001006ffb30
- (void)_handleWebResponseParameters:(id)arg1 error:(id)arg2 cancelled:(_Bool)arg3;	// IMP=0x00000001006ff9e0
- (id)_contentURLs;	// IMP=0x00000001006ff7d8
- (id)_contentVideoURLs;	// IMP=0x00000001006ff530
- (id)_contentImages;	// IMP=0x00000001006ff280
- (void)_cleanUpWebDialog;	// IMP=0x00000001006ff240
- (_Bool)_supportsShareSheetMinimumVersion:(id)arg1;	// IMP=0x00000001006ff0ac
- (_Bool)_canUseMMPInShareSheet;	// IMP=0x00000001006ff068
- (_Bool)_canUseQuoteInShareSheet;	// IMP=0x00000001006ff024
- (_Bool)_canUseFBShareSheet;	// IMP=0x00000001006feed8
- (_Bool)_canAttributeThroughShareSheet;	// IMP=0x00000001006fed3c
- (_Bool)_canShowShareSheet;	// IMP=0x00000001006fec90
- (_Bool)_canShowNative;	// IMP=0x00000001006fec7c
- (void)_loadNativeMethodName:(id *)arg1 methodVersion:(id *)arg2;	// IMP=0x00000001006fea7c
- (id)_nativeScheme;	// IMP=0x00000001006fe9dc
- (_Bool)_showAutomatic:(id *)arg1;	// IMP=0x00000001006fe8ac
- (_Bool)_isOpenGraphURLShare:(id)arg1;	// IMP=0x00000001006fe72c
- (_Bool)_isDefaultToShareSheet;	// IMP=0x00000001006fe650
- (void)webDialogDidCancel:(id)arg1;	// IMP=0x00000001006fe5e0
- (void)webDialog:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x00000001006fe534
- (void)webDialog:(id)arg1 didCompleteWithResults:(id)arg2;	// IMP=0x00000001006fe2f4
- (_Bool)validateWithError:(id *)arg1;	// IMP=0x00000001006fe2b0
- (_Bool)show;	// IMP=0x00000001006fe06c
- (_Bool)canShow;	// IMP=0x00000001006fdfc8
- (void)dealloc;	// IMP=0x00000001006fdf68

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

