//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BFAppLinkResolving.h"

@class NSMutableDictionary, NSString;

@interface FBSDKAppLinkResolver : NSObject <BFAppLinkResolving>
{
    NSMutableDictionary *_cachedLinks;	// 8 = 0x8
    long long _userInterfaceIdiom;	// 16 = 0x10
}

+ (id)resolver;	// IMP=0x00000001006cffac
+ (void)initialize;	// IMP=0x00000001006cef50
@property(nonatomic) long long userInterfaceIdiom; // @synthesize userInterfaceIdiom=_userInterfaceIdiom;
@property(retain, nonatomic) NSMutableDictionary *cachedLinks; // @synthesize cachedLinks=_cachedLinks;
- (void).cxx_destruct;	// IMP=0x00000001006d00b8
- (id)appLinkFromURLInBackground:(id)arg1;	// IMP=0x00000001006cfe08
- (id)appLinksFromURLsInBackground:(id)arg1;	// IMP=0x00000001006cf0ac
- (id)initWithUserInterfaceIdiom:(long long)arg1;	// IMP=0x00000001006cf004

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

