//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class FBSDKErrorRecoveryAttempter, NSError, NSString, UIAlertView;

@interface FBSDKGraphErrorRecoveryProcessor : NSObject <UIAlertViewDelegate>
{
    FBSDKErrorRecoveryAttempter *_recoveryAttempter;	// 8 = 0x8
    NSError *_error;	// 16 = 0x10
    UIAlertView *_alertView;	// 24 = 0x18
    id <FBSDKGraphErrorRecoveryProcessorDelegate> _delegate;	// 32 = 0x20
}

@property(retain, nonatomic) id <FBSDKGraphErrorRecoveryProcessorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001006cb594
- (void)didPresentErrorWithRecovery:(_Bool)arg1 contextInfo:(void *)arg2;	// IMP=0x00000001006cb4f8
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;	// IMP=0x00000001006cb474
- (void)displayAlertWithTitle:(id)arg1 message:(id)arg2 cancelButtonTitle:(id)arg3;	// IMP=0x00000001006cb238
- (void)displayAlertWithRecoverySuggestion:(id)arg1 recoveryOptionsTitles:(id)arg2;	// IMP=0x00000001006caec4
- (_Bool)processError:(id)arg1 request:(id)arg2 delegate:(id)arg3;	// IMP=0x00000001006ca358
- (void)dealloc;	// IMP=0x00000001006ca2f4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

