//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface FBSDKButton : UIButton
{
    _Bool _skipIntrinsicContentSizing;	// 8 = 0x8
    _Bool _isExplicitlyDisabled;	// 9 = 0x9
}

- (double)_textPaddingCorrectionForHeight:(double)arg1;	// IMP=0x00000001006d4328
- (double)_paddingForHeight:(double)arg1;	// IMP=0x00000001006d42e8
- (double)_marginForHeight:(double)arg1;	// IMP=0x00000001006d42cc
- (double)_heightForFont:(id)arg1;	// IMP=0x00000001006d4294
- (double)_heightForContentRect:(struct CGRect)arg1;	// IMP=0x00000001006d422c
- (double)_fontSizeForHeight:(double)arg1;	// IMP=0x00000001006d4210
- (void)_configureWithIcon:(id)arg1 title:(id)arg2 backgroundColor:(id)arg3 highlightedColor:(id)arg4 selectedTitle:(id)arg5 selectedIcon:(id)arg6 selectedColor:(id)arg7 selectedHighlightedColor:(id)arg8;	// IMP=0x00000001006d3b2c
- (id)_backgroundImageWithColor:(id)arg1 cornerRadius:(double)arg2 scale:(double)arg3;	// IMP=0x00000001006d3950
- (void)_applicationDidBecomeActiveNotification:(id)arg1;	// IMP=0x00000001006d3944
- (struct CGSize)sizeThatFits:(struct CGSize)arg1 title:(id)arg2;	// IMP=0x00000001006d37b4
- (_Bool)isImplicitlyDisabled;	// IMP=0x00000001006d37ac
- (id)defaultSelectedColor;	// IMP=0x00000001006d377c
- (id)defaultIcon;	// IMP=0x00000001006d374c
- (id)defaultHighlightedColor;	// IMP=0x00000001006d371c
- (id)defaultFont;	// IMP=0x00000001006d3704
- (id)defaultDisabledColor;	// IMP=0x00000001006d36d4
- (id)defaultBackgroundColor;	// IMP=0x00000001006d36a4
- (void)configureWithIcon:(id)arg1 title:(id)arg2 backgroundColor:(id)arg3 highlightedColor:(id)arg4 selectedTitle:(id)arg5 selectedIcon:(id)arg6 selectedColor:(id)arg7 selectedHighlightedColor:(id)arg8;	// IMP=0x00000001006d3538
- (void)configureWithIcon:(id)arg1 title:(id)arg2 backgroundColor:(id)arg3 highlightedColor:(id)arg4;	// IMP=0x00000001006d3494
- (void)configureButton;	// IMP=0x00000001006d33cc
- (void)checkImplicitlyDisabled;	// IMP=0x00000001006d3310
- (void)logTapEventWithEventName:(id)arg1 parameters:(id)arg2;	// IMP=0x00000001006d3268
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;	// IMP=0x00000001006d2e08
- (void)sizeToFit;	// IMP=0x00000001006d2d98
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001006d2c94
- (void)layoutSubviews;	// IMP=0x00000001006d2b70
- (struct CGSize)intrinsicContentSize;	// IMP=0x00000001006d2b0c
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;	// IMP=0x00000001006d29f0
- (void)setEnabled:(_Bool)arg1;	// IMP=0x00000001006d29d4
- (void)dealloc;	// IMP=0x00000001006d2958
- (void)awakeFromNib;	// IMP=0x00000001006d28f0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001006d2880

@end

