//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSDKLoginCompleting.h"

@class FBSDKLoginCompletionParameters;

@interface FBSDKLoginSystemAccountErrorCompleter : NSObject <FBSDKLoginCompleting>
{
    FBSDKLoginCompletionParameters *_parameters;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001006e9bb0
- (void)completeLogIn:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001006e9b98
- (id)initWithError:(id)arg1 permissions:(id)arg2;	// IMP=0x00000001006e9a6c
- (id)init;	// IMP=0x00000001006e9a44

@end

