//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSDKMessengerContext.h"

@class NSSet, NSString;

@interface FBSDKMessengerURLHandlerReplyContext : FBSDKMessengerContext
{
    NSString *_metadata;	// 8 = 0x8
    NSSet *_userIDs;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSSet *userIDs; // @synthesize userIDs=_userIDs;
@property(readonly, copy, nonatomic) NSString *metadata; // @synthesize metadata=_metadata;
- (void).cxx_destruct;	// IMP=0x00000001006f7200
- (id)queryComponents;	// IMP=0x00000001006f7158
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001006f7054
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001006f6f44
- (id)initWithMetadata:(id)arg1 userIDs:(id)arg2;	// IMP=0x00000001006f6e70

@end

