//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSDKSharingContent.h"

@class FBSDKHashtag, NSArray, NSDictionary, NSString, NSURL;

@interface FBSDKShareLinkContent : NSObject <FBSDKSharingContent>
{
    NSURL *_contentURL;	// 8 = 0x8
    FBSDKHashtag *_hashtag;	// 16 = 0x10
    NSArray *_peopleIDs;	// 24 = 0x18
    NSString *_placeID;	// 32 = 0x20
    NSString *_ref;	// 40 = 0x28
    NSDictionary *_feedParameters;	// 48 = 0x30
    NSString *_quote;	// 56 = 0x38
    NSString *_contentDescription;	// 64 = 0x40
    NSString *_contentTitle;	// 72 = 0x48
    NSURL *_imageURL;	// 80 = 0x50
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001006fca64
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(readonly, nonatomic) NSString *contentTitle; // @synthesize contentTitle=_contentTitle;
@property(readonly, nonatomic) NSString *contentDescription; // @synthesize contentDescription=_contentDescription;
@property(copy, nonatomic) NSString *quote; // @synthesize quote=_quote;
@property(copy, nonatomic) NSDictionary *feedParameters; // @synthesize feedParameters=_feedParameters;
@property(copy, nonatomic) NSString *ref; // @synthesize ref=_ref;
@property(copy, nonatomic) NSString *placeID; // @synthesize placeID=_placeID;
@property(copy, nonatomic) NSArray *peopleIDs; // @synthesize peopleIDs=_peopleIDs;
@property(copy, nonatomic) FBSDKHashtag *hashtag; // @synthesize hashtag=_hashtag;
@property(copy, nonatomic) NSURL *contentURL; // @synthesize contentURL=_contentURL;
- (void).cxx_destruct;	// IMP=0x00000001006fd1b8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001006fcf20
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001006fcd94
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001006fca6c
- (_Bool)isEqualToShareLinkContent:(id)arg1;	// IMP=0x00000001006fc684
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001006fc5f4
@property(readonly) unsigned long long hash;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

