//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSArray, NSMutableArray, NSString;

@interface FBSDKAppEventsState : NSObject <NSCopying, NSSecureCoding>
{
    NSMutableArray *_mutableEvents;	// 8 = 0x8
    unsigned long long _numSkipped;	// 16 = 0x10
    NSString *_tokenString;	// 24 = 0x18
    NSString *_appID;	// 32 = 0x20
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001006afee8
@property(readonly, copy) NSString *appID; // @synthesize appID=_appID;
@property(readonly, copy) NSString *tokenString; // @synthesize tokenString=_tokenString;
@property(readonly) unsigned long long numSkipped; // @synthesize numSkipped=_numSkipped;
- (void).cxx_destruct;	// IMP=0x00000001006b0978
- (id)JSONStringForEvents:(_Bool)arg1;	// IMP=0x00000001006b072c
- (_Bool)isCompatibleWithTokenString:(id)arg1 appID:(id)arg2;	// IMP=0x00000001006b061c
- (_Bool)isCompatibleWithAppEventsState:(id)arg1;	// IMP=0x00000001006b0570
- (_Bool)areAllEventsImplicit;	// IMP=0x00000001006b03fc
- (void)addEvent:(id)arg1 isImplicit:(_Bool)arg2;	// IMP=0x00000001006b02b8
- (void)addEventsFromAppEventState:(id)arg1;	// IMP=0x00000001006b01d8
@property(readonly, copy) NSArray *events;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001006b00b8
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001006afef0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001006afe5c
- (id)initWithToken:(id)arg1 appID:(id)arg2;	// IMP=0x00000001006afd54
- (id)init;	// IMP=0x00000001006afc98

@end

