//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIWebViewDelegate.h"

@class NSString, UIActivityIndicatorView, UIButton, UIWebView;

@interface FBSDKWebDialogView : UIView <UIWebViewDelegate>
{
    UIButton *_closeButton;	// 8 = 0x8
    UIActivityIndicatorView *_loadingView;	// 16 = 0x10
    UIWebView *_webView;	// 24 = 0x18
    id <FBSDKWebDialogViewDelegate> _delegate;	// 32 = 0x20
}

@property(nonatomic) __weak id <FBSDKWebDialogViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001006e385c
- (void)webViewDidFinishLoad:(id)arg1;	// IMP=0x00000001006e37cc
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;	// IMP=0x00000001006e3440
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;	// IMP=0x00000001006e32f8
- (void)_close:(id)arg1;	// IMP=0x00000001006e32b4
- (void)layoutSubviews;	// IMP=0x00000001006e307c
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x00000001006e2f10
- (void)stopLoading;	// IMP=0x00000001006e2ef8
- (void)loadURL:(id)arg1;	// IMP=0x00000001006e2e54
- (void)dealloc;	// IMP=0x00000001006e2df4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001006e2aac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

