//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIRAEvent;

@interface FIRARawEventData : NSObject
{
    FIRAEvent *_rawEvent;	// 8 = 0x8
    long long _rowID;	// 16 = 0x10
    long long _metadataFingerprint;	// 24 = 0x18
}

@property(readonly, nonatomic) long long metadataFingerprint; // @synthesize metadataFingerprint=_metadataFingerprint;
@property(readonly, nonatomic) long long rowID; // @synthesize rowID=_rowID;
@property(readonly, nonatomic) FIRAEvent *rawEvent; // @synthesize rawEvent=_rawEvent;
- (void).cxx_destruct;	// IMP=0x00000001008a40c8
- (id)initWithRawEvent:(id)arg1 rowID:(long long)arg2 metadataFingerprint:(long long)arg3;	// IMP=0x00000001008a3f08

@end

