//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>;

@interface FIRAInAppPurchaseProductCache : NSObject
{
    NSMutableSet *_invalidProductIdentifiers;	// 8 = 0x8
    NSMutableDictionary *_validProducts;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_lockQueue;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x00000001008dc378
- (void).cxx_destruct;	// IMP=0x00000001008dccfc
- (void)requestProductsWithProductIdentifiers:(id)arg1 queue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001008dc72c
- (id)cachedProductForProductIdentifier:(id)arg1;	// IMP=0x00000001008dc4dc
- (id)init;	// IMP=0x00000001008dc3f8

@end

