//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FIRADailyCounts : NSObject
{
    int _day;	// 8 = 0x8
    int _conversionsCount;	// 12 = 0xc
    int _allEventsCount;	// 16 = 0x10
    int _publicEventsCount;	// 20 = 0x14
    int _errorEventsCount;	// 24 = 0x18
    int _realtimeCount;	// 28 = 0x1c
}

@property(readonly, nonatomic) int realtimeCount; // @synthesize realtimeCount=_realtimeCount;
@property(readonly, nonatomic) int errorEventsCount; // @synthesize errorEventsCount=_errorEventsCount;
@property(readonly, nonatomic) int publicEventsCount; // @synthesize publicEventsCount=_publicEventsCount;
@property(readonly, nonatomic) int allEventsCount; // @synthesize allEventsCount=_allEventsCount;
@property(readonly, nonatomic) int conversionsCount; // @synthesize conversionsCount=_conversionsCount;
@property(readonly, nonatomic) int day; // @synthesize day=_day;
- (void)decrementAllEventsCount;	// IMP=0x00000001008a0258
- (void)incrementRealtimeCountsForCurrentDay:(int)arg1;	// IMP=0x00000001008a01e4
- (void)incrementErrorEventsCountForCurrentDay:(int)arg1;	// IMP=0x00000001008a015c
- (void)incrementCountsForCurrentDay:(int)arg1 isPublicEvent:(_Bool)arg2 isConversion:(_Bool)arg3;	// IMP=0x00000001008a00c0
- (id)initWithDay:(int)arg1 conversionsCount:(int)arg2 allEventsCount:(int)arg3 publicEventsCount:(int)arg4 errorEventsCount:(int)arg5 realtimeCount:(int)arg6;	// IMP=0x00000001008a0010

@end

