//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface FIRASqliteStore : NSObject
{
    struct sqlite3 *_sqliteHandle;	// 8 = 0x8
    NSMutableDictionary *_statementCache;	// 16 = 0x10
    const char *_queueLabel;	// 24 = 0x18
    NSString *_databasePath;	// 32 = 0x20
}

@property(readonly, nonatomic) NSString *databasePath; // @synthesize databasePath=_databasePath;
- (void).cxx_destruct;	// IMP=0x00000001008aae94
- (void)setDatabaseError:(id *)arg1 operation:(id)arg2;	// IMP=0x00000001008aade0
- (id)monitorContextForDatabaseOperation:(id)arg1;	// IMP=0x00000001008aab34
- (id)errorDescriptionForDatabaseOperation:(id)arg1;	// IMP=0x00000001008aaa68
- (id)lastErrorMessage;	// IMP=0x00000001008aa9b0
- (_Bool)bindValues:(id)arg1 toStatement:(struct sqlite3_stmt *)arg2 error:(id *)arg3;	// IMP=0x00000001008aa574
- (struct sqlite3_stmt *)updateStatementForRecord:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 error:(id *)arg5;	// IMP=0x00000001008a9f1c
- (struct sqlite3_stmt *)upsertStatementForRecord:(id)arg1 inTableWithName:(id)arg2 error:(id *)arg3;	// IMP=0x00000001008a98a8
- (id)valueAtColumn:(int)arg1 forStatement:(struct sqlite3_stmt *)arg2;	// IMP=0x00000001008a9738
- (void)finalizeAndClearStatements;	// IMP=0x00000001008a95d0
- (_Bool)closeAndDeleteDatabase;	// IMP=0x00000001008a93f0
- (void)closeDatabase;	// IMP=0x00000001008a931c
- (_Bool)validateDatabaseWithError:(id *)arg1;	// IMP=0x00000001008a9220
- (_Bool)openAndValidateDatabase:(id *)arg1;	// IMP=0x00000001008a8eec
- (_Bool)executeSQLStatement:(struct sqlite3_stmt *)arg1 error:(id *)arg2;	// IMP=0x00000001008a8e38
- (_Bool)executeSQL:(id)arg1 error:(id *)arg2;	// IMP=0x00000001008a8d68
- (struct sqlite3_stmt *)prepareSQL:(id)arg1 error:(id *)arg2;	// IMP=0x00000001008a8c34
- (void)cleanUpStatement:(struct sqlite3_stmt *)arg1 forQuery:(id)arg2;	// IMP=0x00000001008a8b68
- (struct sqlite3_stmt *)statementForQuery:(id)arg1 parameterValues:(id)arg2 error:(id *)arg3;	// IMP=0x00000001008a8960
- (struct sqlite3_stmt *)statementForQuery:(id)arg1 error:(id *)arg2;	// IMP=0x00000001008a8948
- (_Bool)rollbackTransaction;	// IMP=0x00000001008a88a0
- (_Bool)endTransaction;	// IMP=0x00000001008a87f8
- (_Bool)beginTransaction;	// IMP=0x00000001008a8750
- (_Bool)performTransaction:(CDUnknownBlockType)arg1;	// IMP=0x00000001008a848c
- (id)numberForQuery:(id)arg1 parameterValues:(id)arg2 error:(id *)arg3;	// IMP=0x00000001008a82a8
- (id)recordsForQuery:(id)arg1 parameterValues:(id)arg2 error:(id *)arg3 withFilter:(CDUnknownBlockType)arg4;	// IMP=0x00000001008a7e3c
- (id)recordsForQuery:(id)arg1 parameterValues:(id)arg2 error:(id *)arg3;	// IMP=0x00000001008a7dc4
- (_Bool)deleteAllRecordsFromTableWithName:(id)arg1 error:(id *)arg2;	// IMP=0x00000001008a7c7c
- (id)deleteRecordsFromTableWithName:(id)arg1 condition:(id)arg2 parameterValues:(id)arg3 error:(id *)arg4;	// IMP=0x00000001008a7a94
- (_Bool)deleteRecordFromTableWithName:(id)arg1 columnName:(id)arg2 columnValue:(id)arg3 error:(id *)arg4;	// IMP=0x00000001008a7840
- (_Bool)updateRecord:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 error:(id *)arg5;	// IMP=0x00000001008a769c
- (_Bool)upsertRecord:(id)arg1 inTableWithName:(id)arg2 error:(id *)arg3;	// IMP=0x00000001008a7584
- (id)columnInfoForTableWithName:(id)arg1 error:(id *)arg2;	// IMP=0x00000001008a7330
- (id)columnsForTableWithName:(id)arg1 error:(id *)arg2;	// IMP=0x00000001008a7134
- (id)rowCountForTableWithName:(id)arg1 columnName:(id)arg2 columnValue:(id)arg3 error:(id *)arg4;	// IMP=0x00000001008a6f54
- (id)rowCountForTableWithName:(id)arg1 error:(id *)arg2;	// IMP=0x00000001008a6f38
- (id)tableExists:(id)arg1 error:(id *)arg2;	// IMP=0x00000001008a6d9c
- (id)validateTableWithName:(id)arg1 requiredColumnNames:(id)arg2 addOnColumns:(id)arg3 error:(id *)arg4;	// IMP=0x00000001008a678c
- (_Bool)copyContentsFromTable:(id)arg1 toTable:(id)arg2 error:(id *)arg3;	// IMP=0x00000001008a664c
- (_Bool)renameTable:(id)arg1 toName:(id)arg2 error:(id *)arg3;	// IMP=0x00000001008a650c
- (_Bool)dropTableWithName:(id)arg1 error:(id *)arg2;	// IMP=0x00000001008a6448
- (_Bool)ensureTableWithName:(id)arg1 createSQL:(id)arg2 requiredColumnNames:(id)arg3 addOnColumns:(id)arg4 error:(id *)arg5;	// IMP=0x00000001008a624c
- (_Bool)ensureTableWithName:(id)arg1 elementaryColumnInfo:(id)arg2 addOnColumnInfo:(id)arg3 modifyColumnInfo:(id)arg4 error:(id *)arg5;	// IMP=0x00000001008a5e94
- (_Bool)ensureSchemaOfTableWithName:(id)arg1 elementaryColumnInfo:(id)arg2 addOnColumnInfo:(id)arg3 error:(id *)arg4;	// IMP=0x00000001008a5698
- (_Bool)ensureTableWithName:(id)arg1 elementaryColumnInfo:(id)arg2 addOnColumnInfo:(id)arg3 error:(id *)arg4;	// IMP=0x00000001008a4f60
@property(readonly, nonatomic) struct sqlite3 *sqliteHandle;
- (void)dealloc;	// IMP=0x00000001008a4f04
- (id)initWithDatabasePath:(id)arg1;	// IMP=0x00000001008a4c88

@end

