//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FIRAppEnvironmentUtil : NSObject
{
}

+ (_Bool)hasSCInfoFolder;	// IMP=0x00000001009056b8
+ (_Bool)isAppExtension;	// IMP=0x0000000100905634
+ (id)systemVersion;	// IMP=0x00000001009055d8
+ (id)deviceModel;	// IMP=0x0000000100905508
+ (_Bool)isSimulator;	// IMP=0x0000000100905488
+ (_Bool)hasEmbeddedMobileProvision;	// IMP=0x00000001009053f8
+ (_Bool)isAppStoreReceiptSandbox;	// IMP=0x00000001009052b8
+ (_Bool)isFromAppStore;	// IMP=0x0000000100905138

@end

