//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface FIRAMonitoringSampledData : NSObject
{
    NSMutableArray *_sampledData;	// 8 = 0x8
}

+ (id)sampledDataEntryWithKey:(id)arg1 timestamp:(id)arg2 context:(id)arg3 population:(id)arg4;	// IMP=0x00000001008e4b4c
+ (id)monitoringURLParamWithKey:(id)arg1 population:(id)arg2 context:(id)arg3;	// IMP=0x00000001008e4a68
+ (_Bool)isValidUserDefaultsArrayEntry:(id)arg1;	// IMP=0x00000001008e4888
- (void).cxx_destruct;	// IMP=0x00000001008e4c74
- (id)sampledData;	// IMP=0x00000001008e4860
- (id)monitoringDataForDispatchWithSamplePeriod:(double)arg1 lastSampledTimestamp:(double)arg2;	// IMP=0x00000001008e4654
- (void)insertOrUpdateSampledDataWithKey:(id)arg1 encodedContext:(id)arg2;	// IMP=0x00000001008e4480
- (id)initWithArray:(id)arg1;	// IMP=0x00000001008e43b4

@end

