//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface FIRAEventFilter : NSObject
{
    int _audienceID;	// 8 = 0x8
    int _filterID;	// 12 = 0xc
    NSString *_eventName;	// 16 = 0x10
    NSData *_data;	// 24 = 0x18
}

@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
@property(readonly, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
@property(readonly, nonatomic) int filterID; // @synthesize filterID=_filterID;
@property(readonly, nonatomic) int audienceID; // @synthesize audienceID=_audienceID;
- (void).cxx_destruct;	// IMP=0x00000001008a3bf8
- (id)initWithAudienceID:(int)arg1 filterID:(int)arg2 eventName:(id)arg3 data:(id)arg4;	// IMP=0x00000001008a3ac0

@end

