//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIRInstanceIDAuthKeychain;

@interface FIRInstanceIDTokenStore : NSObject
{
    FIRInstanceIDAuthKeychain *_keychain;	// 8 = 0x8
}

+ (id)tokenInfoFromKeychainItem:(id)arg1;	// IMP=0x0000000100924478
+ (id)serviceKeyForAuthorizedEntity:(id)arg1 scope:(id)arg2;	// IMP=0x0000000100923f40
+ (id)defaultStore;	// IMP=0x0000000100923e44
@property(retain, nonatomic) FIRInstanceIDAuthKeychain *keychain; // @synthesize keychain=_keychain;
- (void).cxx_destruct;	// IMP=0x0000000100924bf4
- (_Bool)removeAllTokensWithError:(id *)arg1;	// IMP=0x0000000100924a64
- (_Bool)removeTokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 error:(id *)arg3;	// IMP=0x000000010092488c
- (_Bool)saveTokenInfo:(id)arg1;	// IMP=0x00000001009245b0
- (id)cachedTokenInfos;	// IMP=0x00000001009241b4
- (id)tokenInfoWithAuthorizedEntity:(id)arg1 scope:(id)arg2;	// IMP=0x0000000100923fa4
- (id)initWithKeychain:(id)arg1;	// IMP=0x0000000100923ebc
- (id)init;	// IMP=0x0000000100923e10

@end

