//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FIRInstanceIDAuthKeychain : NSObject
{
    NSString *_generic;	// 8 = 0x8
    NSString *_identifier;	// 16 = 0x10
}

+ (id)keychainQueryForService:(id)arg1 account:(id)arg2 accessGroup:(id)arg3 generic:(id)arg4;	// IMP=0x0000000100915334
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSString *generic; // @synthesize generic=_generic;
- (void).cxx_destruct;	// IMP=0x0000000100915fbc
- (_Bool)removeAllItemsWithError:(id *)arg1;	// IMP=0x0000000100915f58
- (_Bool)setData:(id)arg1 forService:(id)arg2 accessibility:(void *)arg3 account:(id)arg4 accessGroup:(id)arg5 error:(id *)arg6;	// IMP=0x0000000100915d80
- (_Bool)removeItemsMatchingService:(id)arg1 account:(id)arg2 accessGroup:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100915c3c
- (id)itemForService:(id)arg1 account:(id)arg2 accessGroup:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100915b88
- (id)itemsMatchingService:(id)arg1 account:(id)arg2 accessGroup:(id)arg3 error:(id *)arg4;	// IMP=0x00000001009158b4
@property(readonly, nonatomic) NSString *defaultAccessGroup;
- (id)keychainQueryForService:(id)arg1 account:(id)arg2 accessGroup:(id)arg3;	// IMP=0x0000000100915580
- (id)initWithIdentifier:(id)arg1;	// IMP=0x00000001009152a8

@end

