//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURLSession;

@interface FIRInstanceIDCheckinService : NSObject
{
    NSURLSession *_session;	// 8 = 0x8
}

+ (void)setCheckinTestBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100919d70
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
- (void).cxx_destruct;	// IMP=0x0000000100919dc4
- (id)checkinParametersWithExistingCheckin:(id)arg1;	// IMP=0x000000010091981c
- (void)stopFetching;	// IMP=0x00000001009197dc
- (void)checkinWithExistingCheckin:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100918e0c
- (void)dealloc;	// IMP=0x0000000100918d88
- (id)init;	// IMP=0x0000000100918c94

@end

