//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDelegate.h"
#import "NSURLSessionDownloadDelegate.h"
#import "NSURLSessionTaskDelegate.h"

@class NSData, NSString, NSURL, NSURLRequest, NSURLSessionConfiguration;

@interface FIRNetworkURLSession : NSObject <NSURLSessionDelegate, NSURLSessionTaskDelegate, NSURLSessionDownloadDelegate>
{
    CDUnknownBlockType _completionHandler;	// 8 = 0x8
    NSString *_sessionID;	// 16 = 0x10
    NSURLSessionConfiguration *_sessionConfig;	// 24 = 0x18
    NSURL *_networkDirectoryURL;	// 32 = 0x20
    NSData *_downloadedData;	// 40 = 0x28
    NSURL *_uploadingFileURL;	// 48 = 0x30
    NSURLRequest *_request;	// 56 = 0x38
    _Bool _backgroundNetworkEnabled;	// 64 = 0x40
    id <FIRNetworkLoggerDelegate> _loggerDelegate;	// 72 = 0x48
}

+ (id)sessionIDToSystemCompletionHandlerDictionary;	// IMP=0x0000000100902178
+ (id)sessionIDToFetcherMap;	// IMP=0x00000001009020fc
+ (id)fetcherWithSessionIdentifier:(id)arg1;	// IMP=0x000000010090200c
+ (void)handleEventsForBackgroundURLSessionID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100900224
@property(nonatomic) __weak id <FIRNetworkLoggerDelegate> loggerDelegate; // @synthesize loggerDelegate=_loggerDelegate;
@property(nonatomic, getter=isBackgroundNetworkEnabled) _Bool backgroundNetworkEnabled; // @synthesize backgroundNetworkEnabled=_backgroundNetworkEnabled;
- (void).cxx_destruct;	// IMP=0x0000000100902bd8
- (void)populateSessionConfig:(id)arg1 withRequest:(id)arg2;	// IMP=0x0000000100902a8c
- (void)callCompletionHandler:(CDUnknownBlockType)arg1 withResponse:(id)arg2 data:(id)arg3 error:(id)arg4;	// IMP=0x00000001009027bc
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100902554
- (void)excludeFromBackupForURL:(id)arg1;	// IMP=0x000000010090244c
- (_Bool)ensureTemporaryDirectoryExists;	// IMP=0x0000000100902288
- (id)temporaryFilePathWithSessionID:(id)arg1;	// IMP=0x00000001009021f8
- (void)removeTempItemAtURL:(id)arg1;	// IMP=0x0000000100901eb0
- (void)maybeRemoveTempFilesAtURL:(id)arg1 expiringTime:(double)arg2;	// IMP=0x0000000100901b50
- (id)backgroundSessionConfigWithSessionID:(id)arg1;	// IMP=0x0000000100901ab8
- (void)setSessionID:(id)arg1;	// IMP=0x0000000100901a78
- (void)callSystemCompletionHandler:(id)arg1;	// IMP=0x000000010090195c
- (void)addSystemCompletionHandler:(CDUnknownBlockType)arg1 forSession:(id)arg2;	// IMP=0x00000001009017bc
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00000001009010e0
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x0000000100900ebc
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(id)arg1;	// IMP=0x0000000100900d8c
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;	// IMP=0x0000000100900bf4
- (id)sessionIDFromAsyncGETRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001009008bc
- (id)sessionIDFromAsyncPOSTRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100900348
- (id)initWithNetworkLoggerDelegate:(id)arg1;	// IMP=0x00000001008ffffc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

