//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FApplePlatformObject.h"

@interface FMetalDeferredStats : FApplePlatformObject
{
    unsigned long long TextureSize;	// 16 = 0x10
    int TexType;	// 24 = 0x18
    _Bool bIsRenderTarget;	// 28 = 0x1c
}

+ (id)alloc;	// IMP=0x000000010220c35c
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010220c340
+ (CDStruct_eb6fb79d *)classAllocator;	// IMP=0x000000010220c334
- (void)dealloc;	// IMP=0x000000010220c378

@end

