//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FApplePlatformObject.h"

@class NSHashTable;

@interface FMetalDebugCommandEncoder : FApplePlatformObject
{
    NSHashTable *UpdatedFences;	// 16 = 0x10
    NSHashTable *WaitingFences;	// 24 = 0x18
}

+ (id)alloc;	// IMP=0x00000001021e43ec
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001021e43d0
+ (CDStruct_eb6fb79d *)classAllocator;	// IMP=0x00000001021e43c4
- (void)addWaitFence:(id)arg1;	// IMP=0x00000001021e459c
- (void)addUpdateFence:(id)arg1;	// IMP=0x00000001021e4530
- (id)commandEncoder;	// IMP=0x00000001021e4528
- (void)dealloc;	// IMP=0x00000001021e44b8
- (id)init;	// IMP=0x00000001021e4408

@end

