//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FApplePlatformObject.h"

#import "NSObject.h"

@class NSString;

@interface FMetalBufferData : FApplePlatformObject <NSObject>
{
    char *Data;	// 16 = 0x10
    unsigned int Len;	// 24 = 0x18
}

+ (id)alloc;	// IMP=0x0000000102212a1c
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000102212a00
+ (CDStruct_eb6fb79d *)classAllocator;	// IMP=0x00000001022129f4
- (void)dealloc;	// IMP=0x0000000102212ba8
- (id)initWithBytes:(const void *)arg1 length:(unsigned int)arg2;	// IMP=0x0000000102212b10
- (id)initWithSize:(unsigned int)arg1;	// IMP=0x0000000102212a94
- (id)init;	// IMP=0x0000000102212a38

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

