//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FApplePlatformObject.h"

@class FMTLHeap;

@interface FMetalResourceData : FApplePlatformObject
{
    int type;	// 16 = 0x10
    unsigned long long size;	// 24 = 0x18
    unsigned long long timestamp;	// 32 = 0x20
    int mode;	// 40 = 0x28
    unsigned int usage;	// 44 = 0x2c
    int aliased;	// 48 = 0x30
    void *owner;	// 56 = 0x38
    FMTLHeap *heap;	// 64 = 0x40
    id resource;	// 72 = 0x48
}

+ (id)alloc;	// IMP=0x00000001021e4c34
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001021e4c18
+ (CDStruct_eb6fb79d *)classAllocator;	// IMP=0x00000001021e4c0c
@property id resource; // @synthesize resource;
@property(retain) FMTLHeap *heap; // @synthesize heap;
- (void)dealloc;	// IMP=0x00000001021e4c50

@end

