//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKTurnBasedMatchmakerViewControllerDelegate.h"

@class NSString;

@interface FTurnBasedMatchmakerDelegateIOS : NSObject <GKTurnBasedMatchmakerViewControllerDelegate>
{
    struct FTurnBasedMatchmakerDelegate *_delegate;	// 8 = 0x8
}

- (void)turnBasedMatchmakerViewControllerWasCancelled:(id)arg1;	// IMP=0x00000001019c9c88
- (void)turnBasedMatchmakerViewController:(id)arg1 playerQuitForMatch:(id)arg2;	// IMP=0x00000001019c9c84
- (void)turnBasedMatchmakerViewController:(id)arg1 didFindMatch:(id)arg2;	// IMP=0x00000001019c9790
- (void)turnBasedMatchmakerViewController:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x00000001019c9770
- (id)initWithDelegate:(struct FTurnBasedMatchmakerDelegate *)arg1;	// IMP=0x00000001019c9720

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

