//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADConfigurationDelegate.h"
#import "GADStatisticDictionaryDelegate.h"

@class GADAd, GADConfiguration, GADContentQueue, GADScheduler, GADStatisticDictionary, NSArray, NSMutableSet, NSObject<OS_dispatch_queue>, NSString, UIViewController;

@interface GADApplication : NSObject <GADConfigurationDelegate, GADStatisticDictionaryDelegate>
{
    GADAd *_backgroundingAd;	// 8 = 0x8
    id <NSObject> _appBecameActiveObserver;	// 16 = 0x10
    id <NSObject> _appWillEnterForegroundObserver;	// 24 = 0x18
    id <NSObject> _appWillResignActiveObserver;	// 32 = 0x20
    GADContentQueue *_contentQueue;	// 40 = 0x28
    GADScheduler *_scheduler;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_serialQueue;	// 56 = 0x38
    NSObject<OS_dispatch_queue> *_lockQueue;	// 64 = 0x40
    NSArray *_availableAdapterNames;	// 72 = 0x48
    unsigned long long _activeViewID;	// 80 = 0x50
    NSString *_version;	// 88 = 0x58
    NSString *_mainBundleIdentifier;	// 96 = 0x60
    _Bool _appFinishedLaunching;	// 104 = 0x68
    _Bool _hasRunAdditionalEarlyActivities;	// 105 = 0x69
    _Bool _backgroundLoadingEnabled;	// 106 = 0x6a
    _Bool _needsConfigurationUpdate;	// 107 = 0x6b
    _Bool _isConfigurationUpdatePublisherInitiated;	// 108 = 0x6c
    GADConfiguration *_configuration;	// 112 = 0x70
    NSMutableSet *_adRequesters;	// 120 = 0x78
    unsigned long long _mainWindowSupportedInterfaceOrientations;	// 128 = 0x80
    _Bool _debugModeEnabled;	// 136 = 0x88
    NSString *_sessionIdentifier;	// 144 = 0x90
    GADStatisticDictionary *_statistics;	// 152 = 0x98
    GADStatisticDictionary *_nativeAdStatistics;	// 160 = 0xa0
    NSString *_inAppPreviewCreativeToken;	// 168 = 0xa8
    NSString *_UUIDString;	// 176 = 0xb0
    NSObject<OS_dispatch_queue> *_notificationSerialQueue;	// 184 = 0xb8
    NSObject<OS_dispatch_queue> *_statisticsSerialQueue;	// 192 = 0xc0
    unsigned long long _sequenceNumber;	// 200 = 0xc8
    NSMutableSet *_adStatistics;	// 208 = 0xd0
}

+ (id)sharedInstance;	// IMP=0x000000010095c594
+ (void)load;	// IMP=0x000000010095c358
@property(readonly, nonatomic) NSMutableSet *adStatistics; // @synthesize adStatistics=_adStatistics;
@property(nonatomic) unsigned long long sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *statisticsSerialQueue; // @synthesize statisticsSerialQueue=_statisticsSerialQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *notificationSerialQueue; // @synthesize notificationSerialQueue=_notificationSerialQueue;
@property(readonly, nonatomic) NSString *UUIDString; // @synthesize UUIDString=_UUIDString;
@property(copy, nonatomic) NSString *inAppPreviewCreativeToken; // @synthesize inAppPreviewCreativeToken=_inAppPreviewCreativeToken;
@property(nonatomic) _Bool debugModeEnabled; // @synthesize debugModeEnabled=_debugModeEnabled;
@property(readonly, copy, nonatomic) GADStatisticDictionary *nativeAdStatistics; // @synthesize nativeAdStatistics=_nativeAdStatistics;
@property(readonly, copy, nonatomic) GADStatisticDictionary *statistics; // @synthesize statistics=_statistics;
@property(readonly, copy, nonatomic) NSString *sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
- (void).cxx_destruct;	// IMP=0x000000010095f0ac
- (void)openURL:(id)arg1 strictUniversalLink:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010095ebc0
- (void)openURL:(id)arg1;	// IMP=0x000000010095eaa8
- (long long)topViewControllerOrientation;	// IMP=0x000000010095e900
- (_Bool)supportsOrientations:(unsigned long long)arg1;	// IMP=0x000000010095e6c0
- (unsigned long long)mainWindowSupportedInterfaceOrientations;	// IMP=0x000000010095e5c0
- (_Bool)isSplitScreenEnabled;	// IMP=0x000000010095e53c
- (id)parameters;	// IMP=0x000000010095e2b8
- (unsigned long long)nextActiveViewID;	// IMP=0x000000010095e180
- (void)GADLinkCategories;	// IMP=0x000000010095e16c
- (void)didUpdateStatisticDictionary:(id)arg1;	// IMP=0x000000010095e0fc
- (id)notificationQueue;	// IMP=0x000000010095e0ec
- (id)pendingAdStatistics;	// IMP=0x000000010095ded0
@property(readonly, copy, nonatomic) UIViewController *topViewController;
- (id)mainWindow;	// IMP=0x000000010095dcf8
- (id)placeholderView;	// IMP=0x000000010095dbac
- (id)iTunesMetadata;	// IMP=0x000000010095da40
- (id)iTunesMetadataPath;	// IMP=0x000000010095d8f8
@property(readonly, nonatomic) _Bool backgroundReloadingEnabled;
@property(readonly, nonatomic) _Bool backgroundLoadingEnabled;
- (void)enableBackgroundAdLoading;	// IMP=0x000000010095d838
@property(readonly, nonatomic) _Bool active;
- (void)appDidFinishLaunching;	// IMP=0x000000010095d7a0
@property(readonly, copy, nonatomic) NSString *mainBundleIdentifier;
@property(readonly, copy, nonatomic) NSString *version;
- (void)runAdditionalEarlyActivities;	// IMP=0x000000010095d4d4
- (void)runEarlyActivities;	// IMP=0x000000010095d23c
- (void)dealloc;	// IMP=0x000000010095d164
- (id)init;	// IMP=0x000000010095c614
- (void)configurationDidUpdate:(id)arg1;	// IMP=0x0000000100959004
- (void)loadServerSideConfigurationIfNeeded;	// IMP=0x0000000100958ec8
- (void)loadServerSideConfigurationForPublisherApplicationID:(id)arg1;	// IMP=0x0000000100958da4
- (void)refreshServerSideConfiguration;	// IMP=0x0000000100958c64
- (id)javaScriptForRequestingServerSideConfiguration;	// IMP=0x00000001009587bc
@property(readonly, nonatomic) GADConfiguration *configuration;
- (void)createConfiguration;	// IMP=0x00000001009584b8
- (void)stopContentHashing;	// IMP=0x0000000100959b40
- (void)startContentHashing;	// IMP=0x0000000100959158
- (id)fingerprintWithServedPenaltyDeduction;	// IMP=0x00000001009590e4
- (void)updateAvailableAdapterNamesWithPotentialAdapterNames:(id)arg1;	// IMP=0x0000000100959e7c
- (void)setAvailableAdapterNames:(id)arg1;	// IMP=0x0000000100959d1c
@property(readonly, copy) NSArray *availableAdapterNames;
- (id)nextRequestStatisticsDictionaryForSlot:(id)arg1;	// IMP=0x000000010095ba40
- (id)timeSinceFirstAdRequestInMilliseconds;	// IMP=0x000000010095b92c
- (id)nextSequenceNumberAsString;	// IMP=0x000000010095b6e4
- (void)incrementSequenceNumber;	// IMP=0x000000010095b698
- (void)incrementTotalAdClickCount;	// IMP=0x000000010095b64c
- (long long)currentAdRequestCount;	// IMP=0x000000010095b5d0
- (void)requesterDidEndRequest:(id)arg1;	// IMP=0x000000010095b3a0
- (void)requesterWillBeginRequest:(id)arg1;	// IMP=0x000000010095b15c
- (void)updateTimeInSession;	// IMP=0x000000010095aff8
- (void)incrementTotalAdRequestCountInCurrentSession;	// IMP=0x000000010095af14
- (void)decrementTotalAdRequestCount;	// IMP=0x000000010095aec8
- (void)incrementTotalAdRequestCount;	// IMP=0x000000010095ae7c
- (void)didNotSendAdStatistics:(id)arg1;	// IMP=0x000000010095ad20
- (void)willResignActive;	// IMP=0x000000010095ad1c
- (void)resetTimeInSession;	// IMP=0x000000010095abbc
- (void)resetPreqsInSession;	// IMP=0x000000010095aa5c
- (void)sendForegroundPing;	// IMP=0x000000010095a4d4
- (void)willEnterForeground;	// IMP=0x000000010095a480
- (void)didBecomeActive;	// IMP=0x000000010095a140
- (void)willLeaveApplicationDueToClickOnAd:(id)arg1;	// IMP=0x000000010095a018

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

