//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADBannerAdViewDelegate.h"

@class GADAdView, NSTimer, NSURL;

@interface GADAdNetworkJavaScriptAdViewDelegate : GADBannerAdViewDelegate
{
    GADAdView *_adView;	// 8 = 0x8
    unsigned long long _checkRenderingCount;	// 16 = 0x10
    NSTimer *_checkRenderingTimer;	// 24 = 0x18
    _Bool _renderingCheckHasStarted;	// 32 = 0x20
    _Bool _wasPassbackReceived;	// 33 = 0x21
    NSURL *_passbackURL;	// 40 = 0x28
}

@property(nonatomic) _Bool wasPassbackReceived; // @synthesize wasPassbackReceived=_wasPassbackReceived;
@property(copy, nonatomic) NSURL *passbackURL; // @synthesize passbackURL=_passbackURL;
- (void).cxx_destruct;	// IMP=0x000000010093f5b4
- (void)adViewDidFinishLoad:(id)arg1;	// IMP=0x000000010093f4d8
- (_Bool)adView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;	// IMP=0x000000010093f378
- (void)adViewDidNotRenderContent;	// IMP=0x000000010093f2c4
- (void)adViewDidRenderContent;	// IMP=0x000000010093f258
- (void)stopRenderingTimer;	// IMP=0x000000010093f20c
- (void)startRenderingTimerForAdView:(id)arg1;	// IMP=0x000000010093f188
- (void)checkIsContentRenderedInAdView;	// IMP=0x000000010093f124
- (_Bool)isPassbackRequest:(id)arg1;	// IMP=0x000000010093ef98
- (id)initWithSlot:(id)arg1;	// IMP=0x000000010093ef88
- (id)initWithSlot:(id)arg1 passbackURL:(id)arg2;	// IMP=0x000000010093eef0

@end

