//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADGMSGHandler.h"

@class GADOpener;

@interface GADAdRefreshGMSGHandler : GADGMSGHandler
{
    GADOpener *_opener;	// 8 = 0x8
}

+ (id)actionBlockDictionary;	// IMP=0x000000010097a13c
- (void).cxx_destruct;	// IMP=0x000000010097a4b8
- (void)adView:(id)arg1 didReceiveRefreshAction:(id)arg2;	// IMP=0x000000010097a320
- (id)initWithOpener:(id)arg1;	// IMP=0x000000010097a2a0

@end

