//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GADBlockTimerTarget : NSObject
{
    CDUnknownBlockType _block;	// 8 = 0x8
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;	// IMP=0x00000001009bda7c
- (void)timerFired:(id)arg1;	// IMP=0x00000001009bda40

@end

