//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADViewController.h"

@class GADAdView, GADAdViewDelegate, NSURL, UIActivityIndicatorView, UIBarButtonItem, UIToolbar;

@interface GADBrowserViewController : GADViewController
{
    NSURL *_URLToLoad;	// 8 = 0x8
    NSURL *_referringURLToLoad;	// 16 = 0x10
    GADAdViewDelegate *_adViewDelegate;	// 24 = 0x18
    GADAdView *_adView;	// 32 = 0x20
    UIToolbar *_toolbar;	// 40 = 0x28
    UIBarButtonItem *_flexibleSpaceButton;	// 48 = 0x30
    UIBarButtonItem *_backButton;	// 56 = 0x38
    UIBarButtonItem *_forwardButton;	// 64 = 0x40
    UIBarButtonItem *_reloadButton;	// 72 = 0x48
    UIBarButtonItem *_safariButton;	// 80 = 0x50
    UIBarButtonItem *_doneButton;	// 88 = 0x58
    UIBarButtonItem *_spinnerContainingButton;	// 96 = 0x60
    UIActivityIndicatorView *_spinner;	// 104 = 0x68
}

@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UIBarButtonItem *spinnerContainingButton; // @synthesize spinnerContainingButton=_spinnerContainingButton;
@property(retain, nonatomic) UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) UIBarButtonItem *safariButton; // @synthesize safariButton=_safariButton;
@property(retain, nonatomic) UIBarButtonItem *reloadButton; // @synthesize reloadButton=_reloadButton;
@property(retain, nonatomic) UIBarButtonItem *forwardButton; // @synthesize forwardButton=_forwardButton;
@property(retain, nonatomic) UIBarButtonItem *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UIBarButtonItem *flexibleSpaceButton; // @synthesize flexibleSpaceButton=_flexibleSpaceButton;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) GADAdView *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) GADAdViewDelegate *adViewDelegate; // @synthesize adViewDelegate=_adViewDelegate;
@property(retain, nonatomic) NSURL *referringURLToLoad; // @synthesize referringURLToLoad=_referringURLToLoad;
@property(retain, nonatomic) NSURL *URLToLoad; // @synthesize URLToLoad=_URLToLoad;
- (void).cxx_destruct;	// IMP=0x00000001009449e8
- (void)openInSafari;	// IMP=0x0000000100944670
- (void)reload;	// IMP=0x0000000100944630
- (void)stop;	// IMP=0x00000001009445f0
- (void)forward;	// IMP=0x000000010094455c
- (void)back;	// IMP=0x00000001009444c8
- (void)load:(id)arg1 referringURL:(id)arg2;	// IMP=0x000000010094437c
- (void)doneButtonPressed:(id)arg1;	// IMP=0x000000010094436c
- (void)refreshToolbar;	// IMP=0x0000000100943f58
- (void)createToolbarButtons;	// IMP=0x0000000100943914
- (id)buttonWithImage:(id)arg1 name:(id)arg2 width:(long long)arg3 enabled:(_Bool)arg4 action:(SEL)arg5;	// IMP=0x0000000100943818
- (void)didRotateFromInterfaceOrientation:(long long)arg1;	// IMP=0x0000000100943768
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100943174
- (void)viewDidLoad;	// IMP=0x00000001009430d0
- (void)dealloc;	// IMP=0x0000000100943074

@end

