//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADBufferedClearcutLogger, NSObject<OS_dispatch_queue>, NSString;

@interface GADClearcutLogger : NSObject
{
    GADBufferedClearcutLogger *_bufferedLogger;	// 8 = 0x8
    NSString *_clearcutID;	// 16 = 0x10
    _Bool _shouldReportEventsOnDealloc;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_lockQueue;	// 32 = 0x20
    _Bool _environmentReported;	// 40 = 0x28
    _Bool _experimentIDsReported;	// 41 = 0x29
}

- (void).cxx_destruct;	// IMP=0x0000000100952d14
@property _Bool experimentIDsReported;
@property _Bool environmentReported;
- (void)reportBufferedParameters:(id)arg1;	// IMP=0x0000000100952724
- (id)clearcutParametersFromEvent:(id)arg1;	// IMP=0x0000000100952710
- (void)executeClearcutCommandWithParameter:(id)arg1;	// IMP=0x000000010095262c
- (void)reportExperimentIDs;	// IMP=0x00000001009524e0
- (void)reportEnvironment;	// IMP=0x0000000100952208
- (void)reportEvent:(id)arg1;	// IMP=0x00000001009520c4
- (void)dealloc;	// IMP=0x0000000100951eac
- (id)init;	// IMP=0x0000000100951bfc

@end

