//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GADInAppPurchase : NSObject
{
    NSString *_productID;	// 8 = 0x8
    long long _quantity;	// 16 = 0x10
}

@property(readonly, nonatomic) long long quantity; // @synthesize quantity=_quantity;
@property(readonly, copy, nonatomic) NSString *productID; // @synthesize productID=_productID;
- (void).cxx_destruct;	// IMP=0x00000001009df594
- (void)reportPurchaseStatus:(long long)arg1;	// IMP=0x00000001009df570
- (id)init;	// IMP=0x00000001009df558

@end

