//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFMailComposeViewControllerDelegate.h"

@class MFMailComposeViewController, NSString;

@interface GADMailComposeDelegateProxy : NSObject <MFMailComposeViewControllerDelegate>
{
    GADMailComposeDelegateProxy *_strongSelf;	// 8 = 0x8
    id <MFMailComposeViewControllerDelegate> _mailComposeDelegate;	// 16 = 0x10
    MFMailComposeViewController *_mailComposeViewController;	// 24 = 0x18
}

+ (id)associatedDelegateProxyForController:(id)arg1;	// IMP=0x00000001009da158
@property(retain, nonatomic) MFMailComposeViewController *mailComposeViewController; // @synthesize mailComposeViewController=_mailComposeViewController;
@property(nonatomic) __weak id <MFMailComposeViewControllerDelegate> mailComposeDelegate; // @synthesize mailComposeDelegate=_mailComposeDelegate;
- (void).cxx_destruct;	// IMP=0x00000001009da56c
- (void)stopProxying;	// IMP=0x00000001009da4ec
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;	// IMP=0x00000001009da2c8
- (id)initInternal;	// IMP=0x00000001009da1e0
- (id)init;	// IMP=0x00000001009da1c8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

