//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GADPublicKey : NSObject
{
    struct __SecCertificate *_certificate;	// 8 = 0x8
    struct __SecTrust *_trustStore;	// 16 = 0x10
    struct __SecKey *_key;	// 24 = 0x18
}

- (_Bool)isSignatureValid:(id)arg1 forMessage:(id)arg2;	// IMP=0x0000000100958314
- (void)dealloc;	// IMP=0x0000000100958298
- (id)initWithCertificateData:(id)arg1;	// IMP=0x00000001009581ac

@end

