//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADSDKCoreGMSGHandlerDelegate.h"
#import "GADSDKCoreWebViewNotification.h"

@class GADSDKCoreWebView, GADWebViewConfiguration, NSArray, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface GADSDKCoreController : NSObject <GADSDKCoreWebViewNotification, GADSDKCoreGMSGHandlerDelegate>
{
    NSObject<OS_dispatch_queue> *_lockQueue;	// 8 = 0x8
    NSMutableArray *_pendingActiveWebViewLoadDelegates;	// 16 = 0x10
    NSMutableArray *_activeViewSDKCoreWebViews;	// 24 = 0x18
    unsigned long long _lastWebViewRefreshTimestamp;	// 32 = 0x20
    unsigned long long _requestID;	// 40 = 0x28
    unsigned long long _activeViewUnloadCacheMaxSize;	// 48 = 0x30
    _Bool _activeViewRequestedSDKCoreReload;	// 56 = 0x38
    GADSDKCoreWebView *_activeViewSDKCoreWebView;	// 64 = 0x40
    _Bool _useNewWebViewsForActiveViewProcessing;	// 72 = 0x48
    double _activeViewSamplingInterval;	// 80 = 0x50
    _Bool _SDKCoreUpdateHandled;	// 88 = 0x58
    NSMutableDictionary *_pendingJavaScriptBlocks;	// 96 = 0x60
    NSMutableDictionary *_pendingJavaScriptBlockExecutionCompletionHandlers;	// 104 = 0x68
    NSMutableDictionary *_pendingJavaScriptCompletionHandlers;	// 112 = 0x70
    NSMutableDictionary *_pendingBuildAdURLDelegates;	// 120 = 0x78
    double _SDKCoreJavaScriptCompletionBlockTimeoutInterval;	// 128 = 0x80
    _Bool _hasReportedSDKCoreStateAtLeastOnce;	// 136 = 0x88
    _Bool _refreshPaused;	// 137 = 0x89
    NSString *_SDKCoreWebViewExperimentID;	// 144 = 0x90
    GADWebViewConfiguration *_webViewConfiguration;	// 152 = 0x98
    NSArray *_activeViewMonitorRefreshIntervals;	// 160 = 0xa0
    GADSDKCoreWebView *_activeSDKCoreWebView;	// 168 = 0xa8
}

+ (id)sharedInstance;	// IMP=0x00000001009eadc4
@property(retain, nonatomic) GADSDKCoreWebView *activeSDKCoreWebView; // @synthesize activeSDKCoreWebView=_activeSDKCoreWebView;
@property(copy) NSArray *activeViewMonitorRefreshIntervals; // @synthesize activeViewMonitorRefreshIntervals=_activeViewMonitorRefreshIntervals;
- (void).cxx_destruct;	// IMP=0x00000001009f0fcc
- (void)SDKCoreGMSGHandlerDidReceiveResumeSDKCoreRefreshAction:(id)arg1;	// IMP=0x00000001009f0ee0
- (void)SDKCoreGMSGHandlerDidReceivePauseSDKCoreRefreshAction:(id)arg1;	// IMP=0x00000001009f0e44
- (void)SDKCoreGMSGHandler:(id)arg1 didReceiveResultActionWithRequestID:(id)arg2 arguments:(id)arg3;	// IMP=0x00000001009f0a88
- (void)SDKCoreGMSGHandlerDidReceiveSDKCoreUpdateNotification:(id)arg1;	// IMP=0x00000001009f09ec
- (void)SDKCoreGMSGHandler:(id)arg1 didReceiveInvalidAdWithRequestID:(id)arg2 parameters:(id)arg3;	// IMP=0x00000001009f0600
- (void)SDKCoreGMSGHandler:(id)arg1 loadAdWithRequestID:(id)arg2 parameters:(id)arg3;	// IMP=0x00000001009f0150
- (void)SDKCoreGMSGHandler:(id)arg1 loadAdURLWithRequestID:(id)arg2 parameters:(id)arg3;	// IMP=0x00000001009efe18
- (void)SDKCoreGMSGHandler:(id)arg1 didLoadSDKConstants:(id)arg2;	// IMP=0x00000001009edb3c
- (void)handleSDKCoreUpdate;	// IMP=0x00000001009ed774
- (void)executePendingJavaScriptBlocks;	// IMP=0x00000001009ed260
- (id)nextRequestID;	// IMP=0x00000001009ed1f4
@property double SDKCoreJavaScriptCompletionBlockTimeoutInterval;
@property double activeViewSamplingInterval;
- (void)observeSDKCoreWebViewForSDKCoreLoadRequestCompleted;	// IMP=0x00000001009ece04
- (void)didFinishLoadingSDKCoreInSDKCoreWebView:(id)arg1;	// IMP=0x00000001009ec9bc
- (void)asynchronouslyRequestURLForDelegate:(id)arg1;	// IMP=0x00000001009ec45c
- (id)adRequestParameterJSONFromParameters:(id)arg1;	// IMP=0x00000001009ec3ac
- (void)refreshActiveWebViewSDKCore;	// IMP=0x00000001009ec08c
- (void)attemptToRefreshActiveWebViewSDKCore;	// IMP=0x00000001009ebe4c
- (void)postJavaScriptNotification:(id)arg1 userInfo:(id)arg2;	// IMP=0x00000001009ebd24
- (void)executeExportedJavaScriptCommand:(id)arg1 parameters:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001009eba20
- (void)executeJavaScriptFromBlockWhenReady:(CDUnknownBlockType)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001009eb7b8
- (void)buildAdURL:(id)arg1;	// IMP=0x00000001009eb658
- (void)finishedUsingSDKCoreWebViewForActiveViewProcessing:(id)arg1;	// IMP=0x00000001009eb608
- (id)SDKCoreWebViewForActiveViewProcessing;	// IMP=0x00000001009eb358
- (void)dealloc;	// IMP=0x00000001009eb2cc
- (id)init;	// IMP=0x00000001009eafe4
- (void)setSDKCoreWebViewExperiment;	// IMP=0x00000001009eae44
- (void)removeFinishedActiveViewWebViews;	// IMP=0x00000001009ea9cc
- (void)cacheRunningActiveViewWebView:(id)arg1;	// IMP=0x00000001009ea85c

@end

