//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface GADStatisticsCore : NSObject
{
    NSMutableDictionary *_statistics;	// 8 = 0x8
    NSString *_userDefaultsKey;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_lockQueue;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001009fa08c
- (void)removeObjectForKey:(id)arg1;	// IMP=0x00000001009f9f4c
- (void)appendDictionary:(id)arg1 toArrayForKey:(id)arg2;	// IMP=0x00000001009f9c74
- (void)appendString:(id)arg1 toArrayForKey:(id)arg2;	// IMP=0x00000001009f99bc
- (id)arrayForKey:(id)arg1;	// IMP=0x00000001009f97d4
- (void)setIdentifier:(id)arg1;	// IMP=0x00000001009f95ac
- (void)savePersistentStatistics;	// IMP=0x00000001009f9524
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x00000001009f9508
@property(readonly, copy, nonatomic) NSDictionary *statistics;
- (void)dealloc;	// IMP=0x00000001009f92f4
- (id)init;	// IMP=0x00000001009f91fc

@end

