//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADBannerView.h"

#import "GADDynamicHeightSearchBannerViewDelegate.h"

@class GADDynamicHeightSearchBannerView, NSString;

@interface GADSearchBannerView : GADBannerView <GADDynamicHeightSearchBannerViewDelegate>
{
    GADDynamicHeightSearchBannerView *_dynamicHeightAdView;	// 88 = 0x58
}

@property(retain, nonatomic) GADDynamicHeightSearchBannerView *dynamicHeightAdView; // @synthesize dynamicHeightAdView=_dynamicHeightAdView;
- (void).cxx_destruct;	// IMP=0x0000000100a1f8c0
- (void)bannerView:(id)arg1 didFailToReceiveAdWithError:(id)arg2;	// IMP=0x0000000100a1f730
- (void)bannerView:(id)arg1 didUpdateDesiredContentSize:(struct CGSize)arg2;	// IMP=0x0000000100a1f624
- (void)bannerView:(id)arg1 didReceiveLandingPageURL:(id)arg2;	// IMP=0x0000000100a1f520
- (void)bannerViewDidReceiveAd:(id)arg1;	// IMP=0x0000000100a1f474
- (void)setAdUnitID:(id)arg1;	// IMP=0x0000000100a1f3e0
- (void)setFrame:(struct CGRect)arg1;	// IMP=0x0000000100a1f33c
- (void)loadRequest:(id)arg1;	// IMP=0x0000000100a1f280
- (void)commonInitWithAdSize:(struct GADAdSize)arg1;	// IMP=0x0000000100a1f124

// Remaining properties
@property(nonatomic) __weak id <GADAdSizeDelegate> adSizeDelegate; // @dynamic adSizeDelegate;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

