//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADLoadable.h"
#import "GADNativeAdDelegate.h"
#import "GADNativeAdUnconfirmedClickDelegate.h"

@class GADNativeAd<GADNativeAdSourceAttributing><GADOverlayViewSource>, GADNativeAdImage, GADVideoController, NSArray, NSDecimalNumber, NSDictionary, NSObject<OS_dispatch_queue>, NSString, UIViewController;

@interface GADUnifiedNativeAd : NSObject <GADNativeAdDelegate, GADNativeAdUnconfirmedClickDelegate, GADLoadable>
{
    NSObject<OS_dispatch_queue> *_lockQueue;	// 8 = 0x8
    GADNativeAd<GADNativeAdSourceAttributing><GADOverlayViewSource> *_internalNativeAd;	// 16 = 0x10
    NSString *_headline;	// 24 = 0x18
    NSString *_callToAction;	// 32 = 0x20
    GADNativeAdImage *_icon;	// 40 = 0x28
    NSString *_body;	// 48 = 0x30
    NSArray *_images;	// 56 = 0x38
    NSDecimalNumber *_starRating;	// 64 = 0x40
    NSString *_store;	// 72 = 0x48
    NSString *_price;	// 80 = 0x50
    NSString *_advertiser;	// 88 = 0x58
    GADVideoController *_videoController;	// 96 = 0x60
    NSDictionary *_extraAssets;	// 104 = 0x68
    NSString *_adNetworkClassName;	// 112 = 0x70
    GADNativeAdImage *_adChoicesIcon;	// 120 = 0x78
    id <GADUnifiedNativeAdUnconfirmedClickDelegate> _unconfirmedClickDelegate;	// 128 = 0x80
    id <GADUnifiedNativeAdDelegate> _delegate;	// 136 = 0x88
    UIViewController *_rootViewController;	// 144 = 0x90
}

+ (id)mediationConnectorForConfiguration:(id)arg1 networkConfiguration:(id)arg2;	// IMP=0x000000010097742c
+ (_Bool)canInitWithAdLoader:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100977380
+ (id)requestParametersForAdLoader:(id)arg1;	// IMP=0x00000001009771d0
+ (id)requiredDelegateProtocol;	// IMP=0x00000001009771c4
@property(readonly, nonatomic) GADNativeAd<GADNativeAdSourceAttributing><GADOverlayViewSource> *internalNativeAd; // @synthesize internalNativeAd=_internalNativeAd;
@property(readonly, nonatomic) GADNativeAdImage *adChoicesIcon; // @synthesize adChoicesIcon=_adChoicesIcon;
@property(readonly, copy, nonatomic) NSString *adNetworkClassName; // @synthesize adNetworkClassName=_adNetworkClassName;
@property(readonly, copy, nonatomic) NSDictionary *extraAssets; // @synthesize extraAssets=_extraAssets;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(nonatomic) __weak id <GADUnifiedNativeAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) GADVideoController *videoController; // @synthesize videoController=_videoController;
@property(readonly, copy, nonatomic) NSString *advertiser; // @synthesize advertiser=_advertiser;
@property(readonly, copy, nonatomic) NSString *price; // @synthesize price=_price;
@property(readonly, copy, nonatomic) NSString *store; // @synthesize store=_store;
@property(readonly, copy, nonatomic) NSDecimalNumber *starRating; // @synthesize starRating=_starRating;
@property(readonly, nonatomic) NSArray *images; // @synthesize images=_images;
@property(readonly, copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(readonly, nonatomic) GADNativeAdImage *icon; // @synthesize icon=_icon;
@property(readonly, copy, nonatomic) NSString *callToAction; // @synthesize callToAction=_callToAction;
@property(readonly, copy, nonatomic) NSString *headline; // @synthesize headline=_headline;
- (void).cxx_destruct;	// IMP=0x0000000100977c04
- (void)nativeAdDidCancelUnconfirmedClick:(id)arg1;	// IMP=0x0000000100977a64
- (void)nativeAd:(id)arg1 didReceiveUnconfirmedClickOnAssetID:(id)arg2;	// IMP=0x00000001009779dc
- (void)nativeAdWillLeaveApplication:(id)arg1;	// IMP=0x0000000100977974
- (void)nativeAdDidDismissScreen:(id)arg1;	// IMP=0x000000010097790c
- (void)nativeAdWillDismissScreen:(id)arg1;	// IMP=0x00000001009778a4
- (void)nativeAdWillPresentScreen:(id)arg1;	// IMP=0x000000010097783c
- (void)nativeAdDidRecordClick:(id)arg1;	// IMP=0x00000001009777d4
- (void)nativeAdDidRecordImpression:(id)arg1;	// IMP=0x000000010097776c
- (id)overlayView;	// IMP=0x0000000100977754
- (id)adChoicesContentView;	// IMP=0x000000010097773c
- (void)cancelUnconfirmedClick;	// IMP=0x0000000100977724
- (void)registerClickConfirmingView:(id)arg1;	// IMP=0x00000001009776fc
- (id)unconfirmedClickDelegate;	// IMP=0x000000010097756c
- (void)setUnconfirmedClickDelegate:(id)arg1;	// IMP=0x0000000100977438
- (void)loadAssetsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100977434
- (void)adLoaderDidReceiveAd:(id)arg1;	// IMP=0x0000000100977388
- (_Bool)recordImpressionWithData:(id)arg1;	// IMP=0x00000001009771ac
- (void)reportTouchEventWithData:(id)arg1;	// IMP=0x0000000100977194
- (void)performClickWithData:(id)arg1;	// IMP=0x000000010097717c
- (void)unregisterAdView;	// IMP=0x00000001009770f8
- (void)registerAdView:(id)arg1 clickableAssetViews:(id)arg2 nonclickableAssetViews:(id)arg3;	// IMP=0x0000000100977080
- (id)init;	// IMP=0x0000000100977068
- (id)initWithNativeAd:(id)arg1;	// IMP=0x0000000100976c28

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

