//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURLRequest, NSURLResponse;

@interface GADURLConnectionRedirect : NSObject
{
    NSURLResponse *_response;	// 8 = 0x8
    NSURLRequest *_request;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(readonly, copy, nonatomic) NSURLResponse *response; // @synthesize response=_response;
- (void).cxx_destruct;	// IMP=0x00000001009b9cac
- (id)initWithResponse:(id)arg1 request:(id)arg2;	// IMP=0x00000001009b9bd8

@end

