//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GGAWSTransferUtility : NSObject
{
}

+ (void)setCurrentDownloadReq:(id)arg1;	// IMP=0x0000000100c2b428
+ (id)currentDownloadReq;	// IMP=0x0000000100c2b41c
+ (void)setCurrentUploadReq:(id)arg1;	// IMP=0x0000000100c2b3c8
+ (id)currentUploadReq;	// IMP=0x0000000100c2b3bc
+ (void)EndTimer;	// IMP=0x0000000100c2b3a8
+ (void)StartTimerWithTimeoutHanlder:(CDUnknownBlockType)arg1;	// IMP=0x0000000100c2b0ec
+ (void)CancelDownloadByTransferManager;	// IMP=0x0000000100c2b0b8
+ (void)CancelUploadByTransferManager;	// IMP=0x0000000100c2b084
+ (void)CancelAll;	// IMP=0x0000000100c2b030
+ (void)downladByTransferManagerWithKey:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3 progressHanlder:(CDUnknownBlockType)arg4;	// IMP=0x0000000100c2a894
+ (void)downloadBinaryDataWithKey:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3 progressHanlder:(CDUnknownBlockType)arg4;	// IMP=0x0000000100c2a248
+ (void)uploadByTransferManager:(id)arg1 key:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4 progressHanlder:(CDUnknownBlockType)arg5;	// IMP=0x0000000100c29774
+ (void)uploadBinaryData:(id)arg1 key:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4 progressHanlder:(CDUnknownBlockType)arg5;	// IMP=0x0000000100c28b3c

@end

