//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TApmCollectPerformance.h"

@interface GPUCollectPerformance : TApmCollectPerformance
{
}

- (void)stopMonitor;	// IMP=0x0000000101133170
- (void)getGPUInfo;	// IMP=0x0000000101133020
- (void)collectionDatas;	// IMP=0x0000000101132f68
- (void)startMonitor;	// IMP=0x0000000101132f34

@end

