//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GSDKDESEncrypt : NSObject
{
}

+ (id)getIPv6:(const char *)arg1;	// IMP=0x000000010050d3a0
+ (id)httpDnsUrlWithDomain:(id)arg1;	// IMP=0x000000010050d05c
+ (id)GSDKDES128Decrypt:(id)arg1 key:(id)arg2;	// IMP=0x000000010050cdf0
+ (id)GSDKDES128Encrypt:(id)arg1 key:(id)arg2;	// IMP=0x000000010050cbd4

@end

