//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface GSDKMemory : NSObject
{
    NSMutableArray *_usedmem_numList;	// 8 = 0x8
    NSMutableArray *_availmem_numList;	// 16 = 0x10
    NSMutableArray *_mem_Dots;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x0000000100502a94
@property(retain, nonatomic) NSMutableArray *mem_Dots; // @synthesize mem_Dots=_mem_Dots;
@property(retain, nonatomic) NSMutableArray *availmem_numList; // @synthesize availmem_numList=_availmem_numList;
@property(retain, nonatomic) NSMutableArray *usedmem_numList; // @synthesize usedmem_numList=_usedmem_numList;
- (void).cxx_destruct;	// IMP=0x0000000100503b94
- (double)getUsedMemory;	// IMP=0x00000001005039a0
- (double)getSystemAvailableMemory;	// IMP=0x0000000100503800
- (void)getMemoryMessage;	// IMP=0x00000001005034b8
- (id)memDots;	// IMP=0x00000001005034a8
- (id)resultMemory_noCollect;	// IMP=0x00000001005033ec
- (id)resultMemory;	// IMP=0x0000000100502da8
- (void)dealloc;	// IMP=0x0000000100502cbc
- (void)startMemory;	// IMP=0x0000000100502b14

@end

