//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HelpshiftFAQFilter, HelpshiftSupportMetaData, NSArray, NSDictionary, NSString;

@interface HelpshiftAPIConfigBuilder : NSObject
{
    _Bool _presentFullScreenOniPad;	// 8 = 0x8
    _Bool _enableFullPrivacy;	// 9 = 0x9
    _Bool _showConversationInfoScreen;	// 10 = 0xa
    _Bool _gotoConversationAfterContactUs;	// 11 = 0xb
    _Bool _requireEmail;	// 12 = 0xc
    _Bool _hideNameAndEmail;	// 13 = 0xd
    _Bool _showSearchOnNewConversation;	// 14 = 0xe
    _Bool _showConversationResolutionQuestion;	// 15 = 0xf
    _Bool _enableTypingIndicator;	// 16 = 0x10
    _Bool _isGotoConversationAfterContactUsSet;	// 17 = 0x11
    int _enableContactUs;	// 20 = 0x14
    NSArray *_customContactUsFlows;	// 24 = 0x18
    HelpshiftFAQFilter *_withTagsMatching;	// 32 = 0x20
    HelpshiftSupportMetaData *_customMetaData;	// 40 = 0x28
    NSDictionary *_customIssueFields;	// 48 = 0x30
    NSDictionary *_extraConfig;	// 56 = 0x38
    NSString *_conversationPrefillText;	// 64 = 0x40
}

@property(nonatomic) _Bool isGotoConversationAfterContactUsSet; // @synthesize isGotoConversationAfterContactUsSet=_isGotoConversationAfterContactUsSet;
@property(nonatomic) _Bool enableTypingIndicator; // @synthesize enableTypingIndicator=_enableTypingIndicator;
@property(nonatomic) _Bool showConversationResolutionQuestion; // @synthesize showConversationResolutionQuestion=_showConversationResolutionQuestion;
@property(retain, nonatomic) NSString *conversationPrefillText; // @synthesize conversationPrefillText=_conversationPrefillText;
@property(nonatomic) _Bool showSearchOnNewConversation; // @synthesize showSearchOnNewConversation=_showSearchOnNewConversation;
@property(nonatomic) _Bool hideNameAndEmail; // @synthesize hideNameAndEmail=_hideNameAndEmail;
@property(nonatomic) _Bool requireEmail; // @synthesize requireEmail=_requireEmail;
@property(nonatomic) _Bool gotoConversationAfterContactUs; // @synthesize gotoConversationAfterContactUs=_gotoConversationAfterContactUs;
@property(retain, nonatomic) NSDictionary *extraConfig; // @synthesize extraConfig=_extraConfig;
@property(retain, nonatomic) NSDictionary *customIssueFields; // @synthesize customIssueFields=_customIssueFields;
@property(retain, nonatomic) HelpshiftSupportMetaData *customMetaData; // @synthesize customMetaData=_customMetaData;
@property(retain, nonatomic) HelpshiftFAQFilter *withTagsMatching; // @synthesize withTagsMatching=_withTagsMatching;
@property(retain, nonatomic) NSArray *customContactUsFlows; // @synthesize customContactUsFlows=_customContactUsFlows;
@property(nonatomic) int enableContactUs; // @synthesize enableContactUs=_enableContactUs;
@property(nonatomic) _Bool showConversationInfoScreen; // @synthesize showConversationInfoScreen=_showConversationInfoScreen;
@property(nonatomic) _Bool enableFullPrivacy; // @synthesize enableFullPrivacy=_enableFullPrivacy;
@property(nonatomic) _Bool presentFullScreenOniPad; // @synthesize presentFullScreenOniPad=_presentFullScreenOniPad;
- (void).cxx_destruct;	// IMP=0x000000010141a804
- (id)build;	// IMP=0x000000010141a240
- (id)init;	// IMP=0x000000010141a0b4

@end

