//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsMessageTableViewCell.h"

@class HSButton, HsAspectFitImageView, HsThemeableButton, NSLayoutConstraint, UIActivityIndicatorView, UILabel, UIView;

@interface HsAgentAttachmentTableViewCell : HsMessageTableViewCell
{
    UIView *_attachmentContainerView;	// 8 = 0x8
    HsAspectFitImageView *_iconImageView;	// 16 = 0x10
    HsThemeableButton *_attachmentNameButton;	// 24 = 0x18
    HSButton *_downloadButton;	// 32 = 0x20
    UILabel *_attachmentDescLabel;	// 40 = 0x28
    UIActivityIndicatorView *_activityIndicator;	// 48 = 0x30
    NSLayoutConstraint *_downloadButtonContainerWidthConstrain;	// 56 = 0x38
}

@property(nonatomic) __weak NSLayoutConstraint *downloadButtonContainerWidthConstrain; // @synthesize downloadButtonContainerWidthConstrain=_downloadButtonContainerWidthConstrain;
@property(nonatomic) __weak UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) __weak UILabel *attachmentDescLabel; // @synthesize attachmentDescLabel=_attachmentDescLabel;
@property(nonatomic) __weak HSButton *downloadButton; // @synthesize downloadButton=_downloadButton;
@property(nonatomic) __weak HsThemeableButton *attachmentNameButton; // @synthesize attachmentNameButton=_attachmentNameButton;
@property(nonatomic) __weak HsAspectFitImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak UIView *attachmentContainerView; // @synthesize attachmentContainerView=_attachmentContainerView;
- (void).cxx_destruct;	// IMP=0x000000010143978c
- (void)applyTinting;	// IMP=0x0000000101439130
- (void)applyTheming;	// IMP=0x0000000101438d20
- (id)accessibilityLabel;	// IMP=0x0000000101438b28
- (void)attachmentNameButtonClicked:(id)arg1;	// IMP=0x0000000101438a54
- (void)downloadButtonClicked:(id)arg1;	// IMP=0x0000000101438980
- (void)showDownloadedState;	// IMP=0x00000001014386a4
- (void)showDownloadingState;	// IMP=0x00000001014383c4
- (void)showNotStartedState;	// IMP=0x0000000101438128
- (void)setMessageDefaults;	// IMP=0x0000000101438030
- (void)setupDefaultColors;	// IMP=0x0000000101438024
- (void)setupViewsDefaults;	// IMP=0x0000000101437d64
- (void)updateWithDM:(id)arg1;	// IMP=0x0000000101437c74
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000101437c40
- (void)awakeFromNib;	// IMP=0x0000000101437bf0

@end

