//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsAgentMessageDM.h"

@class HsTextInput;

@interface HsAgentMessageWithTextInputDM : HsAgentMessageDM
{
    _Bool _isMessageEmpty;	// 8 = 0x8
    HsTextInput *_input;	// 16 = 0x10
}

@property _Bool isMessageEmpty; // @synthesize isMessageEmpty=_isMessageEmpty;
@property(retain) HsTextInput *input; // @synthesize input=_input;
- (void).cxx_destruct;	// IMP=0x00000001014819a0
- (_Bool)canBeCountedAsUnseen;	// IMP=0x0000000101481914
- (void)merge:(id)arg1;	// IMP=0x000000010148182c
- (id)initWithBody:(id)arg1 createdAt:(id)arg2 authorName:(id)arg3 placeholder:(id)arg4 botInfo:(id)arg5 required:(_Bool)arg6 inputLabel:(id)arg7 skipLabel:(id)arg8 keyboardType:(unsigned long long)arg9 isMessageEmpty:(_Bool)arg10;	// IMP=0x0000000101481694

@end

