//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HSAppLifeCycleEventsObserver.h"
#import "HsAutoRetriable.h"

@class HsAnalyticsEventDTO, HsDomain, HsSDKConfigurationDM, NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface HsAnalyticsDM : NSObject <HsAutoRetriable, HSAppLifeCycleEventsObserver>
{
    HsDomain *_domain;	// 8 = 0x8
    id <HsPlatform> _platform;	// 16 = 0x10
    NSMutableArray *_events;	// 24 = 0x18
    HsSDKConfigurationDM *_sdkConfigDM;	// 32 = 0x20
    id <HsAnalyticsDao> _dao;	// 40 = 0x28
    HsAnalyticsEventDTO *_lastScreenEvent;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_workerQueue;	// 56 = 0x38
}

+ (id)stringForAnalyticsEvent:(unsigned long long)arg1;	// IMP=0x000000010139c4f4
+ (id)stringForAnalyticsEventKey:(unsigned long long)arg1;	// IMP=0x000000010139c400
- (void).cxx_destruct;	// IMP=0x000000010139d7c0
- (id)getEvents;	// IMP=0x000000010139d798
- (void)applicationWillEnterForeground;	// IMP=0x000000010139d6cc
- (void)retryFailedRoutes:(unsigned long long)arg1 withError:(id *)arg2;	// IMP=0x000000010139d39c
- (id)completeEventsDataForEventDTOs:(id)arg1 forUser:(id)arg2;	// IMP=0x000000010139cd88
- (id)dtoFromSerialisedAnalyticsEvent:(id)arg1;	// IMP=0x000000010139cc18
- (id)dtosFromSerialisedAnalyticsEvents:(id)arg1;	// IMP=0x000000010139ca70
- (id)serialisedAnalyticsEventDTO:(id)arg1;	// IMP=0x000000010139c8c0
- (id)serialisedAnalyticsEventsDTOs:(id)arg1;	// IMP=0x000000010139c6ec
- (_Bool)isEventAlreadyAdded:(unsigned long long)arg1;	// IMP=0x000000010139c2bc
- (_Bool)isOpenEventAlreadyAdded;	// IMP=0x000000010139c2ac
- (_Bool)isDecomposedOpenEventAlreadyAdded;	// IMP=0x000000010139c29c
- (_Bool)isDynamicFormClosedEventAdded;	// IMP=0x000000010139c28c
- (_Bool)isDynamicFormOpenEventAdded;	// IMP=0x000000010139c27c
- (id)formattedAnalyticsEventDTO:(id)arg1;	// IMP=0x000000010139c0cc
- (id)formattedAnalyticsEventsDTOs:(id)arg1;	// IMP=0x000000010139bef8
- (void)addEvent:(id)arg1;	// IMP=0x000000010139bd70
- (_Bool)sendEventsData:(id)arg1;	// IMP=0x000000010139bb54
- (id)createAnalyticsNetwork;	// IMP=0x000000010139ba64
- (void)addLastScreenEvent;	// IMP=0x000000010139b9e0
- (id)lastScreenEvent;	// IMP=0x000000010139b8e8
- (_Bool)syncEventsForUser:(id)arg1;	// IMP=0x000000010139b808
- (void)clearEvents;	// IMP=0x000000010139b77c
- (void)pushEvent:(unsigned long long)arg1;	// IMP=0x000000010139b76c
- (void)pushEvent:(unsigned long long)arg1 withId:(id)arg2;	// IMP=0x000000010139b66c
- (void)pushEvent:(unsigned long long)arg1 withData:(id)arg2;	// IMP=0x000000010139b490
- (id)initWithDomain:(id)arg1 platform:(id)arg2;	// IMP=0x000000010139b2b0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

