//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HSApplicationLifeCycleEventsListener : NSObject
{
    id <HSApplicationLifeCycleEvents> _delegate;	// 8 = 0x8
}

@property(nonatomic) __weak id <HSApplicationLifeCycleEvents> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001013af668
- (void)applicationDidBecomeActive;	// IMP=0x00000001013af5ac
- (void)applicationDidEnterBackground;	// IMP=0x00000001013af524
- (void)applicationWillResignActive;	// IMP=0x00000001013af49c
- (void)applicationWillEnterForeground;	// IMP=0x00000001013af414
- (void)initialiseListners;	// IMP=0x00000001013af2c8
- (void)dealloc;	// IMP=0x00000001013af1b0
- (id)initWithDelegate:(id)arg1;	// IMP=0x00000001013af12c

@end

