//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsButtonWidget.h"

@class NSString;

@interface HsAttachmentWidget : HsButtonWidget
{
    NSString *_attachmentResourceName;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001013d568c
- (id)attachmentResourceName;	// IMP=0x00000001013d567c
- (void)setAttachmentResourceName:(id)arg1;	// IMP=0x00000001013d5628

@end

