//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HSLoadingViewModel, HSSDKDataDM, HSUserManagerDM, HelpshiftAPIConfig, HelpshiftInstallConfig, HelpshiftUser, HsAnalyticsDM, HsConversationDM, HsConversationInboxDM, HsConversationInboxManagerDM, HsConversationalVM, HsDomain, HsFAQsDM, HsLocalizationDM, HsMetaDataDM, HsNewConversationVM, HsSDKConfigurationDM, NSNumber, NSString;

@protocol HsCore <NSObject>
- (HSLoadingViewModel *)loadingViewModelWithRenderer:(id <HSLoadingRenderer>)arg1;
- (void)sendRequestIdsForSuccessfulApiCalls;
- (long long)unseenMessageCountSync;
- (void)unseenMessageCountWithHandler:(void (^)(unsigned long long, NSError *))arg1 shouldFetch:(_Bool)arg2;
- (void)applicationWillEnterForeground;
- (void)setupConversationPolling;
- (void)sendAnalyticsEvents;
- (HsLocalizationDM *)localizationDM;
- (HsAnalyticsDM *)analyticsDM;
- (HSSDKDataDM *)sdkDataDM;
- (HsFAQsDM *)faqsDM;
- (HsConversationDM *)fetchActiveConversationOrPreConversation;
- (HsConversationDM *)fetchActiveConversation;
- (HsConversationInboxManagerDM *)conversationInboxManagerDM;
- (HsConversationInboxDM *)conversationInboxDM;
- (HsSDKConfigurationDM *)sdkConfigDM;
- (HsMetaDataDM *)metaDataDM;
- (HSUserManagerDM *)userManagerDM;
- (void)updateApiConfig:(HelpshiftAPIConfig *)arg1;
- (void)updateInstallConfig:(HelpshiftInstallConfig *)arg1;
- (void)setInstallCredentialsWithApiKey:(NSString *)arg1 domain:(NSString *)arg2 appId:(NSString *)arg3;
- (void)fetchServerConfig;
- (void)setPushToken:(NSString *)arg1;
- (_Bool)clearAnonymousUser;
- (_Bool)logout;
- (HsConversationalVM *)conversationalViewModelWithRenderer:(id <HsConversationalRenderer>)arg1 conversationHistory:(_Bool)arg2 conversationLocalId:(NSNumber *)arg3 withError:(id *)arg4;
- (void)setName:(NSString *)arg1 andEmail:(NSString *)arg2;
- (_Bool)login:(HelpshiftUser *)arg1;
- (HsNewConversationVM *)newConversationViewModel:(id <HsNewConversationRenderer>)arg1;
- (HsDomain *)domain;
@end

