//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsMessageDM.h"

@interface HsConversationDividerMessageDM : HsMessageDM
{
    _Bool _showDividerLabel;	// 8 = 0x8
}

@property(nonatomic) _Bool showDividerLabel; // @synthesize showDividerLabel=_showDividerLabel;
- (_Bool)isUISupported;	// IMP=0x000000010147adb0
- (id)initWithShowDividerLable:(_Bool)arg1;	// IMP=0x000000010147acd4

@end

