//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsCorePoller.h"

@interface HsConversationInChatPoller : HsCorePoller
{
}

- (id)backoffBuilder;	// IMP=0x00000001013d0adc
- (id)failureBackoff;	// IMP=0x00000001013d0968
- (id)successBackoff;	// IMP=0x00000001013d08d0
- (id)initWithDelegate:(id)arg1;	// IMP=0x00000001013d0874

@end

