//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HsCoreViewUtils : NSObject
{
}

+ (struct CGSize)computeExpectedLabelSize:(id)arg1 forFont:(id)arg2 andWidth:(double)arg3;	// IMP=0x000000010136fa1c
+ (id)getTopViewController;	// IMP=0x000000010136f72c

@end

