//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsConversationVM.h"

#import "HsNewConversationListener.h"

@class HSReachability, NSString;

@interface HsConversationalVM : HsConversationVM <HsNewConversationListener>
{
    _Bool _isInBetweenBotExecution;	// 8 = 0x8
    _Bool _awaitingUserInputForBotStep;	// 9 = 0x9
    _Bool _isShowingPollFailureError;	// 10 = 0xa
    _Bool _isUserReplyDraftClearedForBotChange;	// 11 = 0xb
    HSReachability *_reachability;	// 16 = 0x10
}

@property _Bool isUserReplyDraftClearedForBotChange; // @synthesize isUserReplyDraftClearedForBotChange=_isUserReplyDraftClearedForBotChange;
@property(retain) HSReachability *reachability; // @synthesize reachability=_reachability;
@property _Bool isShowingPollFailureError; // @synthesize isShowingPollFailureError=_isShowingPollFailureError;
@property _Bool awaitingUserInputForBotStep; // @synthesize awaitingUserInputForBotStep=_awaitingUserInputForBotStep;
@property _Bool isInBetweenBotExecution; // @synthesize isInBetweenBotExecution=_isInBetweenBotExecution;
- (void).cxx_destruct;	// IMP=0x000000010135d384
- (void)updateDependenciesForMessageDMs:(id)arg1;	// IMP=0x000000010135d164
- (id)splitFAQListWithOptionInputMessageDM:(id)arg1 shouldExpandOptions:(_Bool)arg2;	// IMP=0x000000010135cee8
- (id)splitAgentTextWithOptionInputMessageDM:(id)arg1 shouldExpandOptions:(_Bool)arg2;	// IMP=0x000000010135ccec
- (id)incrementCreatedAt:(id)arg1;	// IMP=0x000000010135cb74
- (id)splitFAQList:(id)arg1;	// IMP=0x000000010135ca24
- (id)splitOptionInputMessageDM:(id)arg1 shouldExpandOptions:(_Bool)arg2;	// IMP=0x000000010135c934
- (id)processMessages:(id)arg1 withLatestBotMessage:(id)arg2;	// IMP=0x000000010135c6dc
- (void)setUpRechability;	// IMP=0x000000010135c624
- (void)handleNetworkChange:(id)arg1;	// IMP=0x000000010135c5d4
- (void)onUIMessageListUpdated;	// IMP=0x000000010135c594
- (void)newConversationButtonClicked;	// IMP=0x000000010135c274
- (void)handleAdminSuggestedQuestionReadWithServerID:(id)arg1 questionServerID:(id)arg2 questionPublishID:(id)arg3;	// IMP=0x000000010135c008
- (void)conversationCreationFailedWithError:(id)arg1;	// IMP=0x000000010135bee4
- (void)handlePreIssueCreationSuccess;	// IMP=0x000000010135bdb4
- (void)conversationCreationSuccessfulWithLocalId:(id)arg1;	// IMP=0x000000010135bda8
- (void)updateLastUserActivityTime;	// IMP=0x000000010135bd74
- (id)adjustedDate;	// IMP=0x000000010135bcac
- (void)onNetworkUnavailable;	// IMP=0x000000010135bad8
- (void)onNetworkAvailable;	// IMP=0x000000010135b954
- (void)updateUserInputState;	// IMP=0x000000010135b728
- (void)conversationStateChangedTo:(unsigned long long)arg1;	// IMP=0x000000010135b5c0
- (void)showStandardUserInput;	// IMP=0x000000010135b564
- (void)disableTextInput;	// IMP=0x000000010135b520
- (id)evaluateBotMessageDMs:(id)arg1;	// IMP=0x000000010135b150
- (void)removeOptionMessageFromUI;	// IMP=0x000000010135b01c
- (id)processMessagesForBots:(id)arg1 withCurrentBotsExecutionState:(_Bool)arg2;	// IMP=0x000000010135abf4
- (id)buildUiMessages:(id)arg1;	// IMP=0x000000010135aa38
- (void)updateMessage:(id)arg1;	// IMP=0x000000010135a9c4
- (void)addAllMessageDMs:(id)arg1;	// IMP=0x000000010135a900
- (void)disableUserInputOptions;	// IMP=0x000000010135a7e4
- (void)optionSelectedWithDM:(id)arg1 selectedOption:(id)arg2 isSkipped:(_Bool)arg3;	// IMP=0x000000010135a494
- (void)skipTapped;	// IMP=0x000000010135a1cc
- (void)sendTextMessageWithString:(id)arg1;	// IMP=0x0000000101359c98
- (void)userDidEnterReply:(id)arg1;	// IMP=0x0000000101359c04
- (void)sendTextMessage;	// IMP=0x0000000101359b98
- (void)showFakeTypingIndicator:(_Bool)arg1;	// IMP=0x0000000101359928
- (void)createPreIssue;	// IMP=0x00000001013598ac
- (void)onConversationInboxPollSuccess;	// IMP=0x00000001013597ac
- (void)onConversationInboxPollFailure;	// IMP=0x0000000101359628
- (id)greetingMessageIfNewPreissue;	// IMP=0x00000001013593b0
- (void)addGreetingMessageIfNewPreissue;	// IMP=0x00000001013592c4
- (void)initMessagesList;	// IMP=0x00000001013591d0
- (id)conversationalRenderer;	// IMP=0x00000001013591c4
- (id)conversationalMediator;	// IMP=0x00000001013591b8
- (id)widgetGatewayWithDevice:(id)arg1 sdkConfigDM:(id)arg2 conversationInboxDM:(id)arg3;	// IMP=0x00000001013590bc
- (id)mediatorWithDomain:(id)arg1;	// IMP=0x0000000101359054
- (void)conversationViewControllerDidAppear;	// IMP=0x0000000101358bb8
- (id)initWithPlatform:(id)arg1 domain:(id)arg2 conversationInboxDM:(id)arg3 viewableConversation:(id)arg4 sdkDataDM:(id)arg5 conversationalRenderer:(id)arg6;	// IMP=0x0000000101358a84

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

