//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface HSConfigPlist : NSObject
{
    NSDictionary *pListDict;	// 8 = 0x8
    NSDictionary *_styleSheet;	// 16 = 0x10
}

@property(retain, nonatomic) NSDictionary *styleSheet; // @synthesize styleSheet=_styleSheet;
- (void).cxx_destruct;	// IMP=0x00000001014b26ec
- (id)getSpinnerView;	// IMP=0x00000001014b2580
- (id)getStatusUpToDateView;	// IMP=0x00000001014b22c0
- (id)getAccessoryView;	// IMP=0x00000001014b1fd8
- (void)applyStyleForView:(id)arg1;	// IMP=0x00000001014b1ea0
- (void)setChatAckTextColor:(id)arg1;	// IMP=0x00000001014b1da4
- (void)setGlobalBoldFontIfAvailable:(id)arg1 size:(double)arg2;	// IMP=0x00000001014b1c4c
- (void)setGlobalFontIfAvailable:(id)arg1 size:(double)arg2;	// IMP=0x00000001014b1af4
- (id)backButtonWithTitle:(id)arg1;	// IMP=0x00000001014b19cc
- (void)applyStyleForConvResolutionButton:(id)arg1 withProperty:(int)arg2;	// IMP=0x00000001014b188c
- (void)applyGlobalTextColorForLabel:(id)arg1 withAlpha:(double)arg2;	// IMP=0x00000001014b179c
- (void)applyStyleForCSATLabel:(id)arg1;	// IMP=0x00000001014b16dc
- (void)applyStyleForRatingStarButton:(id)arg1;	// IMP=0x00000001014b1618
- (void)applyStyleForBarButtonItem:(id)arg1;	// IMP=0x00000001014b1378
- (void)applyStyleForBadgeView:(id)arg1;	// IMP=0x00000001014b1270
- (void)applyStyleForChatReplyBar:(id)arg1 andTextView:(id)arg2;	// IMP=0x00000001014b1108
- (void)applyStyleForNavigationBar:(id)arg1;	// IMP=0x00000001014b0d98
- (void)applyStyleForTableViewHeaderLabel:(id)arg1;	// IMP=0x00000001014b0a98
- (void)applyStyleForFAQsStatus:(id)arg1 forLabel:(id)arg2;	// IMP=0x00000001014b08b4
- (void)applyStyleForTableViewCellLabel:(id)arg1;	// IMP=0x00000001014b0738
- (void)applyStyleForTableViewCell:(id)arg1 forLabel:(id)arg2;	// IMP=0x00000001014b03e0
- (void)applyStyleForTableViewCell:(id)arg1;	// IMP=0x00000001014b012c
- (void)applyBackgroundViewForTableView:(id)arg1;	// IMP=0x00000001014b0014
- (void)applyStyleForTableView:(id)arg1;	// IMP=0x00000001014afe94
- (void)applyStyleForSearchBar:(id)arg1;	// IMP=0x00000001014afca4
- (void)applyStyleValue:(int)arg1 property:(int)arg2 toView:(id)arg3;	// IMP=0x00000001014afbf8
- (void)loadStylesheet;	// IMP=0x00000001014afa20
- (id)getStyleDictByUIElement:(int)arg1;	// IMP=0x00000001014aecb0
- (id)getStyleByUIElement:(int)arg1 property:(int)arg2;	// IMP=0x00000001014ae91c
- (id)getNumberValue:(int)arg1 property:(int)arg2;	// IMP=0x00000001014ae83c
- (_Bool)getBooleanValue:(int)arg1 property:(int)arg2;	// IMP=0x00000001014ae6d4
- (id)getValue:(int)arg1 property:(int)arg2;	// IMP=0x00000001014ae5d8
- (id)getStyleValue:(int)arg1 property:(int)arg2;	// IMP=0x00000001014ae4d8
- (id)init;	// IMP=0x00000001014ae310

@end

