//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HsSpecification.h"

@class NSString;

@interface HsDailyFrequencySyncSpecification : NSObject <HsSpecification>
{
    NSString *_dataType;	// 8 = 0x8
    double _elapsedTimeThreshold;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001013a2230
- (_Bool)isSatisfiedForDataChangeCount:(unsigned long long)arg1 andElapsedTimeSinceSync:(double)arg2;	// IMP=0x00000001013a2170
- (id)getDataType;	// IMP=0x00000001013a2160
- (id)initWithDailyFrequency:(unsigned long long)arg1 forDataType:(id)arg2;	// IMP=0x00000001013a20b8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

