//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HsApiExecutor.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface HsDispatchQueueExecutor : NSObject <HsApiExecutor>
{
    NSObject<OS_dispatch_queue> *_workerQueue;	// 8 = 0x8
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workerQueue; // @synthesize workerQueue=_workerQueue;
- (void).cxx_destruct;	// IMP=0x000000010137600c
- (_Bool)callAndReturnBool:(CDUnknownBlockType)arg1;	// IMP=0x0000000101375e48
- (long long)callAndReturnInteger:(CDUnknownBlockType)arg1;	// IMP=0x0000000101375ca8
- (id)callAndReturn:(CDUnknownBlockType)arg1;	// IMP=0x0000000101375abc
- (void)runOnUiThread:(CDUnknownBlockType)arg1;	// IMP=0x0000000101375a00
- (void)runSync:(CDUnknownBlockType)arg1;	// IMP=0x000000010137599c
- (void)runAsync:(CDUnknownBlockType)arg1;	// IMP=0x0000000101375938
- (void)runSyncOnUIThread:(CDUnknownBlockType)arg1;	// IMP=0x00000001013758b8
- (id)initWithThreadName:(id)arg1;	// IMP=0x0000000101375814

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

