//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HSSDKDataDM, HSUserManagerDM, HsAnalyticsDM, HsConversationInboxManagerDM, HsFAQsDM, HsLocalizationDM, HsMetaDataDM, HsRetriableEventsDM, HsSDKConfigurationDM, HsThreader, HsWebsocketConfigDM;

@interface HsDomain : NSObject
{
    id <HsPlatform> _platform;	// 8 = 0x8
    HsSDKConfigurationDM *_sdkConfigDM;	// 16 = 0x10
    HsWebsocketConfigDM *_websocketConfigDM;	// 24 = 0x18
    HsMetaDataDM *_metaDataDM;	// 32 = 0x20
    HsAnalyticsDM *_analyticsDM;	// 40 = 0x28
    HsRetriableEventsDM *_retriableEventsDM;	// 48 = 0x30
    HsLocalizationDM *_localizationDM;	// 56 = 0x38
    HSUserManagerDM *_userManagerDM;	// 64 = 0x40
    HSSDKDataDM *_sdkDataDM;	// 72 = 0x48
    HsConversationInboxManagerDM *_conversationInboxManagerDM;	// 80 = 0x50
    HsFAQsDM *_faqsDM;	// 88 = 0x58
    HsThreader *_serialThreaderPrivate;	// 96 = 0x60
    HsThreader *_concurrentThreaderPrivate;	// 104 = 0x68
}

@property(retain, nonatomic) HsThreader *concurrentThreaderPrivate; // @synthesize concurrentThreaderPrivate=_concurrentThreaderPrivate;
@property(retain, nonatomic) HsThreader *serialThreaderPrivate; // @synthesize serialThreaderPrivate=_serialThreaderPrivate;
- (void).cxx_destruct;	// IMP=0x00000001013bca94
- (id)faqsDM;	// IMP=0x00000001013bc99c
- (id)conversationInboxManagerDM;	// IMP=0x00000001013bc8b0
- (id)fetchActiveConversation;	// IMP=0x00000001013bc824
- (id)conversationInboxDM;	// IMP=0x00000001013bc7d0
- (id)sdkDataDM;	// IMP=0x00000001013bc724
- (id)userManagerDM;	// IMP=0x00000001013bc648
- (id)localizationDM;	// IMP=0x00000001013bc564
- (id)websocketConfigDM;	// IMP=0x00000001013bc4b4
- (id)retriableEventsDM;	// IMP=0x00000001013bc404
- (id)analyticsDM;	// IMP=0x00000001013bc354
- (id)metaDataDM;	// IMP=0x00000001013bc204
- (id)sdkConfigurationDM;	// IMP=0x00000001013bc0e8
- (void)runOnUI:(CDUnknownBlockType)arg1;	// IMP=0x00000001013bc010
- (void)runConcurrent:(CDUnknownBlockType)arg1 withDelay:(double)arg2;	// IMP=0x00000001013bbf74
- (void)runConcurrent:(CDUnknownBlockType)arg1;	// IMP=0x00000001013bbee8
- (void)runSerial:(CDUnknownBlockType)arg1;	// IMP=0x00000001013bbe5c
@property(readonly) HsThreader *concurrentThreader;
@property(readonly) HsThreader *serialThreader;
- (id)initWithPlatform:(id)arg1;	// IMP=0x00000001013bbbb4

@end

