//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HsNetwork.h"

@class NSString;

@interface HsEtagNetwork : NSObject <HsNetwork>
{
    id <HsNetwork> _network;	// 8 = 0x8
    id <HsNetworkRequestDAO> _networkRequestDao;	// 16 = 0x10
    NSString *_route;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000101345c64
- (id)makeRequest:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000101345b00
- (id)initWithNetwork:(id)arg1 platform:(id)arg2 route:(id)arg3;	// IMP=0x0000000101345a04

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

