//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HsExponentialBackoffBuilder;

@interface HsHTTPBackoffBuilder : NSObject
{
    HsExponentialBackoffBuilder *_exponentialBackoffBuilder;	// 8 = 0x8
    id <HsRetryPolicy> _retryPolicy;	// 16 = 0x10
}

@property(retain, nonatomic) id <HsRetryPolicy> retryPolicy; // @synthesize retryPolicy=_retryPolicy;
@property(retain, nonatomic) HsExponentialBackoffBuilder *exponentialBackoffBuilder; // @synthesize exponentialBackoffBuilder=_exponentialBackoffBuilder;
- (void).cxx_destruct;	// IMP=0x00000001014c5c10
- (id)build;	// IMP=0x00000001014c5b88
- (id)init;	// IMP=0x00000001014c5acc

@end

