//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HsExponentialBackoff;

@interface HsHTTPBackoff : NSObject
{
    HsExponentialBackoff *_exponentialBackoff;	// 8 = 0x8
    id <HsRetryPolicy> _retryPolicy;	// 16 = 0x10
}

@property(retain, nonatomic) id <HsRetryPolicy> retryPolicy; // @synthesize retryPolicy=_retryPolicy;
@property(retain, nonatomic) HsExponentialBackoff *exponentialBackoff; // @synthesize exponentialBackoff=_exponentialBackoff;
- (void).cxx_destruct;	// IMP=0x00000001013a1f74
- (_Bool)shouldRetryForStatusCode:(int)arg1;	// IMP=0x00000001013a1ed8
- (double)nextIntervalForStatusCode:(long long)arg1;	// IMP=0x00000001013a1e2c
- (void)reset;	// IMP=0x00000001013a1dec
- (id)initWithBuilder:(id)arg1;	// IMP=0x00000001013a1cec

@end

