//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HSAppLifeCycleEventsHandler.h"

@class NSHashTable, NSObject<OS_dispatch_queue>, NSString;

@interface HSiOSAppLifeCycleEventHandler : NSObject <HSAppLifeCycleEventsHandler>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSHashTable *_observers;	// 16 = 0x10
}

@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;	// IMP=0x00000001014201b0
- (void)dispatchEvent:(unsigned long long)arg1;	// IMP=0x000000010141ff44
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x000000010141ff34
- (void)applicationWillEnterForeground:(id)arg1;	// IMP=0x000000010141ff24
- (void)applicationDidFinishLaunching:(id)arg1;	// IMP=0x000000010141ff20
- (void)removeObserver:(id)arg1;	// IMP=0x000000010141fdcc
- (void)addObserver:(id)arg1;	// IMP=0x000000010141fc78
- (id)init;	// IMP=0x000000010141fb24

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

