//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HsDevice.h"

@class NSDictionary;

@interface HsiOSDevice : NSObject <HsDevice>
{
    NSDictionary *deviceMakeDictionary;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001014991a8
- (_Bool)getPushOptIn;	// IMP=0x0000000101498fb0
- (long long)getTimeZone;	// IMP=0x0000000101498f48
- (id)getCarrierName;	// IMP=0x0000000101498e8c
- (id)getLanguageCode;	// IMP=0x0000000101498df8
- (id)getCountryCode;	// IMP=0x0000000101498d10
- (id)getAppVersion;	// IMP=0x0000000101498c0c
- (id)getDeviceMakeString;	// IMP=0x0000000101498b98
- (id)getBuildModel;	// IMP=0x0000000101498928
- (id)getOsVersion;	// IMP=0x00000001014988cc
- (id)init;	// IMP=0x0000000101498288

@end

