//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HSKeyboardHandler : NSObject
{
    unsigned long long _keyboardStatus;	// 8 = 0x8
    id <HSKeyboardEventObserver> _eventObserver;	// 16 = 0x10
}

@property(nonatomic) __weak id <HSKeyboardEventObserver> eventObserver; // @synthesize eventObserver=_eventObserver;
@property(nonatomic) unsigned long long keyboardStatus; // @synthesize keyboardStatus=_keyboardStatus;
- (void).cxx_destruct;	// IMP=0x00000001013bdc78
- (_Bool)isIllogicalKeyboardStatus:(unsigned long long)arg1;	// IMP=0x00000001013bdb80
- (void)updateKeyboardStatus:(unsigned long long)arg1;	// IMP=0x00000001013bdb24
- (unsigned long long)keyboardStatusForNotification:(id)arg1;	// IMP=0x00000001013bda2c
- (void)resizeView:(id)arg1;	// IMP=0x00000001013bd41c
- (void)didShowOrHideKeyboard:(id)arg1;	// IMP=0x00000001013bd3bc
- (void)didChangeKeyboardFrame:(id)arg1;	// IMP=0x00000001013bd2e4
- (void)willShowOrHideKeyboard:(id)arg1;	// IMP=0x00000001013bd20c
- (void)removeObserver;	// IMP=0x00000001013bd110
- (void)addObserver:(id)arg1;	// IMP=0x00000001013bcfc0

@end

