//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HsKeyValueStorage.h"

@class NSString;

@interface HsKeyValueDbStorage : NSObject <HsKeyValueStorage>
{
    NSString *_namespace;	// 8 = 0x8
}

@property(retain, nonatomic) NSString *namespace; // @synthesize namespace=_namespace;
- (void).cxx_destruct;	// IMP=0x0000000101369fb8
- (void)removeObjectForKey:(id)arg1;	// IMP=0x0000000101369d88
- (id)objectForKey:(id)arg1;	// IMP=0x0000000101369a34
- (void)setObject:(id)arg1 forKey:(id)arg2;	// IMP=0x000000010136979c
- (void)destroyStorage;	// IMP=0x000000010136966c
- (void)initStorage;	// IMP=0x0000000101369518
- (void)initStorageWithNamespace:(id)arg1;	// IMP=0x00000001013694e4
- (id)getTableName;	// IMP=0x0000000101369334
- (id)escapeKey:(id)arg1;	// IMP=0x0000000101369270

@end

