//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HSBaseViewController.h"

#import "HSLoadingRenderer.h"

@class HSFailureView, HSLoadingViewModel, NSString, UIActivityIndicatorView, UILabel;

@interface HSLoadingViewController : HSBaseViewController <HSLoadingRenderer>
{
    UIActivityIndicatorView *_loadingIndicator;	// 8 = 0x8
    UILabel *_loadingLabel;	// 16 = 0x10
    HSFailureView *_failureView;	// 24 = 0x18
    HSLoadingViewModel *_viewModel;	// 32 = 0x20
}

@property(retain, nonatomic) HSLoadingViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak HSFailureView *failureView; // @synthesize failureView=_failureView;
@property(nonatomic) __weak UILabel *loadingLabel; // @synthesize loadingLabel=_loadingLabel;
@property(nonatomic) __weak UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
- (void).cxx_destruct;	// IMP=0x0000000101410764
- (void)hideNetworkError;	// IMP=0x0000000101410698
- (void)showNetworkError;	// IMP=0x0000000101410688
- (void)goToConversation;	// IMP=0x00000001014104f4
- (void)showLoadingLabel;	// IMP=0x0000000101410428
- (void)showAuthenticationFailedView;	// IMP=0x0000000101410418
- (void)showFailedView:(unsigned long long)arg1;	// IMP=0x000000010140ff64
- (void)setUpDefaultViewState;	// IMP=0x000000010140fcf8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010140fb00
- (void)setupViews;	// IMP=0x000000010140f904
- (void)viewDidLoad;	// IMP=0x000000010140f8b4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

