//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HsConversationMerger, HsDomain;

@interface HsNetworkConversationLoader : NSObject
{
    id <HsPlatform> _platform;	// 8 = 0x8
    HsDomain *_domain;	// 16 = 0x10
    HsConversationMerger *_merger;	// 24 = 0x18
}

@property(retain) HsConversationMerger *merger; // @synthesize merger=_merger;
@property(retain) HsDomain *domain; // @synthesize domain=_domain;
@property(retain) id <HsPlatform> platform; // @synthesize platform=_platform;
- (void).cxx_destruct;	// IMP=0x00000001013bf614
- (id)createConversationNetwork;	// IMP=0x00000001013bf42c
- (_Bool)hasOlderMessagesForUser:(id)arg1;	// IMP=0x00000001013bf2f0
- (void)conversationsBeforeCursor:(id)arg1 forUser:(id)arg2 withError:(id *)arg3;	// IMP=0x00000001013bef10
- (id)initWithPlatform:(id)arg1 domain:(id)arg2 merger:(id)arg3;	// IMP=0x00000001013bee28

@end

