//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface HsPaginationCursor : NSObject
{
    NSString *_issueCursor;	// 8 = 0x8
    NSString *_messageCursor;	// 16 = 0x10
}

@property(readonly) NSString *messageCursor; // @synthesize messageCursor=_messageCursor;
@property(readonly) NSString *issueCursor; // @synthesize issueCursor=_issueCursor;
- (void).cxx_destruct;	// IMP=0x00000001013727f0
- (id)initWithIssueCursor:(id)arg1 messageCursor:(id)arg2;	// IMP=0x000000010137271c

@end

