//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface HSPersistentDataModel : NSObject
{
    struct sqlite3 *hsDB;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *workerQueue;	// 16 = 0x10
    id <HsKeyValueStorage> _storage;	// 24 = 0x18
}

+ (id)getLegacyDeviceUdid;	// IMP=0x000000010149ce08
+ (_Bool)doesTable:(id)arg1 existInDb:(struct sqlite3 *)arg2;	// IMP=0x000000010149cd44
+ (short)getFaqOptionForDeviceSearch;	// IMP=0x000000010149cc50
+ (void)setFaqOptionForDeviceSearch:(short)arg1;	// IMP=0x000000010149cab4
+ (void)setSearchIndexFileName:(id)arg1;	// IMP=0x000000010149c970
+ (id)getSearchIndexFileName;	// IMP=0x000000010149c874
+ (struct sqlite3 *)getHsftFaqSearchDbConn;	// IMP=0x000000010149c6ac
+ (struct sqlite3 *)getHsftFaqsDbConn;	// IMP=0x000000010149c27c
+ (_Bool)doesFAQSectionTableExist;	// IMP=0x000000010149c0ac
+ (void)removeOldFaqDb;	// IMP=0x000000010149bf44
+ (void)removeOldDB;	// IMP=0x000000010149be28
+ (_Bool)isFAQsDbValid;	// IMP=0x000000010149bbd8
+ (id)convertMetaDataToString:(id)arg1;	// IMP=0x000000010149bb38
+ (id)filterForPrivateData:(id)arg1;	// IMP=0x000000010149b9e4
+ (id)cleanUpTagsArray:(id)arg1;	// IMP=0x000000010149b7dc
+ (_Bool)isSDKInstalledCorrectly;	// IMP=0x000000010149b62c
+ (void)dropAllAndReinitialize;	// IMP=0x000000010149b528
+ (void)removeObjectForKey:(id)arg1;	// IMP=0x000000010149b488
+ (id)objectForKey:(id)arg1;	// IMP=0x000000010149b3dc
+ (void)migrateKVStoreToSDKDataDM;	// IMP=0x000000010149b2cc
+ (void)migrateUserDefaultsToKVStore;	// IMP=0x000000010149b028
+ (id)sharedInstance;	// IMP=0x000000010149aed0
@property(retain, nonatomic) id <HsKeyValueStorage> storage; // @synthesize storage=_storage;
- (void).cxx_destruct;	// IMP=0x000000010149ceb0

@end

