//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsWidget.h"

@interface HsProfileFormWidget : HsWidget
{
    _Bool _isVisible;	// 8 = 0x8
}

- (_Bool)isVisible;	// IMP=0x000000010139d874
- (void)setVisible:(_Bool)arg1;	// IMP=0x000000010139d864

@end

