//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsWidget.h"

@interface HsProgressBarWidget : HsWidget
{
    _Bool _visible;	// 8 = 0x8
}

- (void)setVisible:(_Bool)arg1;	// IMP=0x00000001013a4f0c
- (_Bool)visible;	// IMP=0x00000001013a4efc

@end

