//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HsCoreFactory;

@interface HSRedactionAgent : NSObject
{
    HsCoreFactory *_factory;	// 8 = 0x8
}

@property(retain, nonatomic) HsCoreFactory *factory; // @synthesize factory=_factory;
- (void).cxx_destruct;	// IMP=0x0000000101349bd0
- (void)markUser:(id)arg1 forRedactionOfType:(unsigned long long)arg2;	// IMP=0x0000000101349a14
- (_Bool)isConversationRedactedWhereLastRedactionAtServerTime:(id)arg1 andLastRedactionAtLocalTime:(id)arg2;	// IMP=0x0000000101349994
- (_Bool)isUserRedactedWhereProfileCreateAt:(id)arg1 andOldestConversationCreateAt:(id)arg2;	// IMP=0x0000000101349910
- (void)markUser:(id)arg1 forRedactionUpdatesWhereProfileCreatedAtTime:(id)arg2 lastRedactionAtServerTime:(id)arg3;	// IMP=0x0000000101349680
- (id)initWithCoreFactory:(id)arg1;	// IMP=0x000000010134960c

@end

