//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HSAppLifeCycleEventsObserver.h"

@class HSCategoryTagsFilter, HelpshiftAPIConfig, HsDomain, NSString;

@interface HsSDKConfigurationDM : NSObject <HSAppLifeCycleEventsObserver>
{
    id <HsPlatform> _platform;	// 8 = 0x8
    HsDomain *_domain;	// 16 = 0x10
    id <HsResponseParser> _responseParser;	// 24 = 0x18
    id <HsKVStore> _kvStore;	// 32 = 0x20
    HelpshiftAPIConfig *_cachedAPIConfig;	// 40 = 0x28
    _Bool _hideThanksAlertAfterIssueFiling;	// 48 = 0x30
    HSCategoryTagsFilter *_withTagsMatching;	// 56 = 0x38
}

@property(nonatomic) _Bool hideThanksAlertAfterIssueFiling; // @synthesize hideThanksAlertAfterIssueFiling=_hideThanksAlertAfterIssueFiling;
@property(retain, nonatomic) HSCategoryTagsFilter *withTagsMatching; // @synthesize withTagsMatching=_withTagsMatching;
- (void).cxx_destruct;	// IMP=0x0000000101443f24
- (_Bool)getEnableContactUsOptionForLocation:(int)arg1;	// IMP=0x0000000101443c40
- (void)applicationDidEnterBackground;	// IMP=0x0000000101443bd8
- (void)applicationWillEnterForeground;	// IMP=0x0000000101443ad8
- (int)intValueForKey:(id)arg1;	// IMP=0x0000000101443a18
- (id)stringValueForKey:(id)arg1;	// IMP=0x0000000101443928
- (_Bool)booleanValueForKey:(id)arg1;	// IMP=0x00000001014437bc
- (id)customIssueFields;	// IMP=0x00000001014434e0
- (_Bool)shouldCreateConversationAnonymously;	// IMP=0x0000000101443458
- (long long)minimumConversationDescriptionLength;	// IMP=0x0000000101443440
- (_Bool)allowUserAttachments;	// IMP=0x000000010144342c
- (_Bool)enableTypingIndicator;	// IMP=0x00000001014433d4
- (_Bool)showConversationInfoScreen;	// IMP=0x00000001014433bc
- (id)conversationPrefillText;	// IMP=0x00000001014433a4
- (int)enableContactUsOption;	// IMP=0x000000010144338c
- (_Bool)showConversationResolutionQuestion;	// IMP=0x0000000101443330
- (_Bool)showSearchOnNewConversation;	// IMP=0x0000000101443318
- (_Bool)fullPrivacyEnabled;	// IMP=0x0000000101443300
- (_Bool)hideNameAndEmail;	// IMP=0x00000001014432e8
- (_Bool)requireEmail;	// IMP=0x00000001014432d0
- (_Bool)presentFullScreenOnIPad;	// IMP=0x00000001014432b8
- (_Bool)gotoConversationAfterContactUs;	// IMP=0x00000001014432a0
- (id)customContactUsFlows;	// IMP=0x0000000101443288
- (void)setSdkLanguage:(id)arg1;	// IMP=0x00000001014431f0
- (id)supportedFileFormats;	// IMP=0x00000001014431ac
- (id)unityMessageHandler;	// IMP=0x0000000101443168
- (id)sdkLanguage;	// IMP=0x0000000101443154
- (id)periodicReviewDTO;	// IMP=0x00000001014430b4
- (id)reviewURL;	// IMP=0x00000001014430a0
- (_Bool)disableInAppConversation;	// IMP=0x000000010144308c
- (_Bool)shouldShowHelpshiftLogo;	// IMP=0x000000010144306c
- (_Bool)showCustomerSatisfactionSurvey;	// IMP=0x0000000101443058
- (_Bool)showAgentName;	// IMP=0x0000000101443044
- (_Bool)profileFormEnabled;	// IMP=0x0000000101443030
- (_Bool)requireNameAndEmail;	// IMP=0x000000010144301c
- (unsigned long long)debugLogLimit;	// IMP=0x0000000101442ff4
- (unsigned long long)breadcrumbLimit;	// IMP=0x0000000101442fcc
- (_Bool)conversationHistory;	// IMP=0x0000000101442f68
- (id)conversationGreetingMeeting;	// IMP=0x0000000101442f54
- (_Bool)conversationalIssueFiling;	// IMP=0x0000000101442f04
- (void)setAddFAQsToDeviceSearch:(short)arg1;	// IMP=0x0000000101442ec4
- (short)addFAQsToDeviceSearch;	// IMP=0x0000000101442e9c
- (id)runtimeVersion;	// IMP=0x0000000101442e88
- (id)pluginVersion;	// IMP=0x0000000101442e74
- (id)sdkType;	// IMP=0x0000000101442e60
- (_Bool)disableErrorLogging;	// IMP=0x0000000101442e4c
- (_Bool)disableAppLaunchEvent;	// IMP=0x0000000101442e38
- (_Bool)disableHelpshiftBranding;	// IMP=0x0000000101442e24
- (void)setDisableAnimations:(_Bool)arg1;	// IMP=0x0000000101442de0
- (_Bool)disableAnimations;	// IMP=0x0000000101442dcc
- (_Bool)defaultFallbackLanguageEnabled;	// IMP=0x0000000101442db8
- (_Bool)inboxPollingEnabled;	// IMP=0x0000000101442da4
- (_Bool)enableInAppNotification;	// IMP=0x0000000101442d90
- (void)updateInstallConfigWithDTO:(id)arg1;	// IMP=0x000000010144245c
- (void)updateInstallConfigWithConfig:(id)arg1;	// IMP=0x00000001014423ac
- (void)setInstallCredentialsWithApiKey:(id)arg1 domain:(id)arg2 appId:(id)arg3;	// IMP=0x00000001014421ec
- (void)updateApiConfigWithDTO:(id)arg1;	// IMP=0x0000000101441c8c
- (void)updateApiConfigWithConfig:(id)arg1;	// IMP=0x0000000101441ae4
- (id)createAPIConfig;	// IMP=0x0000000101441834
- (void)updateConfigForUser:(id)arg1 andUserManager:(id)arg2 withServerConfig:(id)arg3;	// IMP=0x00000001014417c0
- (void)updateServerConfigWithDTO:(id)arg1;	// IMP=0x000000010144105c
- (id)fetchServerConfig:(id)arg1;	// IMP=0x0000000101440ce0
- (id)initWithDomain:(id)arg1 platform:(id)arg2 withError:(id *)arg3;	// IMP=0x0000000101440b54

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

