//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HsSingleFaqDataSource.h"

@class HsFaq, NSString;

@interface HsSingleFaqModel : NSObject <HsSingleFaqDataSource>
{
    HsFaq *_faq;	// 8 = 0x8
    id <HsModelObserver> _observer;	// 16 = 0x10
}

@property(nonatomic) __weak id <HsModelObserver> observer; // @synthesize observer=_observer;
@property(retain, nonatomic) HsFaq *faq; // @synthesize faq=_faq;
- (void).cxx_destruct;	// IMP=0x000000010139a06c
- (id)faqHelpfulStatus;	// IMP=0x0000000101399fc0
- (id)isFaqRtl;	// IMP=0x0000000101399f08
- (id)getSearchTerms;	// IMP=0x0000000101399e7c
- (id)idForDataAtIndex:(unsigned long long)arg1;	// IMP=0x0000000101399df0
- (id)dataAtIndex:(unsigned long long)arg1;	// IMP=0x0000000101399d1c
- (unsigned long long)getCount;	// IMP=0x0000000101399d14
- (id)init;	// IMP=0x0000000101399ca4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

