//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsViewableConversation.h"

@class HsConversationDM;

@interface HsSingleConversationDM : HsViewableConversation
{
    _Bool _hasOlderMessages;	// 8 = 0x8
    HsConversationDM *_conversation;	// 16 = 0x10
}

@property(retain) HsConversationDM *conversation; // @synthesize conversation=_conversation;
- (void).cxx_destruct;	// IMP=0x00000001013c8c10
- (_Bool)hasOlderMessages;	// IMP=0x00000001013c8b54
- (unsigned long long)type;	// IMP=0x00000001013c8b4c
- (_Bool)shouldOpen;	// IMP=0x00000001013c8b00
- (void)prependConversations:(id)arg1;	// IMP=0x00000001013c88a4
- (id)filterConversationsToPrepend:(id)arg1;	// IMP=0x00000001013c85b4
- (id)conversations;	// IMP=0x00000001013c84bc
- (void)initializeConversationsForUI;	// IMP=0x00000001013c8478
- (id)activeConversation;	// IMP=0x00000001013c846c
- (id)identifier;	// IMP=0x00000001013c8454
- (id)initWithConversation:(id)arg1 platform:(id)arg2 domain:(id)arg3 liveUpdateDM:(id)arg4 conversationLoader:(id)arg5 user:(id)arg6;	// IMP=0x00000001013c8344
- (id)initWithPlatform:(id)arg1 domain:(id)arg2 liveUpdateDM:(id)arg3 conversationLoader:(id)arg4 user:(id)arg5;	// IMP=0x00000001013c8264

@end

