//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsBaseNetwork.h"

@interface HsUploadNetwork : HsBaseNetwork
{
}

+ (id)boundary;	// IMP=0x00000001013d0bf4
- (id)makeRequest:(id)arg1 withError:(id *)arg2;	// IMP=0x00000001013d0fb4
- (id)makeRequestObject:(id)arg1;	// IMP=0x00000001013d0d30
- (id)uploadHeaders:(id)arg1;	// IMP=0x00000001013d0c34
- (id)httpBody:(id)arg1;	// IMP=0x00000001013d0c20

@end

