//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HsDomain, HsWebsocketConfigDTO;

@interface HsWebsocketConfigDM : NSObject
{
    HsDomain *_domain;	// 8 = 0x8
    id <HsPlatform> _platform;	// 16 = 0x10
    HsWebsocketConfigDTO *_websocketConfig;	// 24 = 0x18
}

@property(retain, nonatomic) HsWebsocketConfigDTO *websocketConfig; // @synthesize websocketConfig=_websocketConfig;
- (void).cxx_destruct;	// IMP=0x00000001013495b8
- (void)saveWebsocketConfigJson:(id)arg1;	// IMP=0x000000010134951c
- (id)requestParameters;	// IMP=0x00000001013492d8
- (void)refreshConfigWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000101348df4
- (id)initWithDomain:(id)arg1 platform:(id)arg2;	// IMP=0x0000000101348d40

@end

