//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMSDKMTAEvent.h"

#import "IMSDKMTAEventProtocol.h"

@class NSString;

@interface IMSDKMTAActiveEvent : IMSDKMTAEvent <IMSDKMTAEventProtocol>
{
    unsigned int _duration;	// 40 = 0x28
}

@property unsigned int duration; // @synthesize duration=_duration;
- (id)init;	// IMP=0x0000000100652dd4
- (void)encode:(id)arg1;	// IMP=0x0000000100652d34
- (int)getType;	// IMP=0x0000000100652d2c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

