//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface IMSDKMBBarProgressView : UIView
{
    float _progress;	// 8 = 0x8
    UIColor *_lineColor;	// 16 = 0x10
    UIColor *_progressRemainingColor;	// 24 = 0x18
    UIColor *_progressColor;	// 32 = 0x20
}

@property(retain, nonatomic) UIColor *progressColor; // @synthesize progressColor=_progressColor;
@property(retain, nonatomic) UIColor *progressRemainingColor; // @synthesize progressRemainingColor=_progressRemainingColor;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;	// IMP=0x0000000100690a80
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001006909e8
- (id)observableKeypaths;	// IMP=0x0000000100690994
- (void)unregisterFromKVO;	// IMP=0x0000000100690860
- (void)registerForKVO;	// IMP=0x0000000100690724
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x00000001006901ec
- (void)dealloc;	// IMP=0x000000010069019c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010069004c
- (id)init;	// IMP=0x000000010069002c

@end

