//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class IMSDKAFHTTPRequestSerializer<IMSDKAFURLRequestSerialization>, IMSDKAFHTTPResponseSerializer<IMSDKAFURLResponseSerialization>, IMSDKAFNetworkReachabilityManager, IMSDKAFSecurityPolicy, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, NSOperationQueue, NSURL, NSURLCredential;

@interface IMSDKAFHTTPRequestOperationManager : NSObject <NSSecureCoding, NSCopying>
{
    _Bool _shouldUseCredentialStorage;	// 8 = 0x8
    NSURL *_baseURL;	// 16 = 0x10
    IMSDKAFHTTPRequestSerializer<IMSDKAFURLRequestSerialization> *_requestSerializer;	// 24 = 0x18
    IMSDKAFHTTPResponseSerializer<IMSDKAFURLResponseSerialization> *_responseSerializer;	// 32 = 0x20
    NSOperationQueue *_operationQueue;	// 40 = 0x28
    NSURLCredential *_credential;	// 48 = 0x30
    IMSDKAFSecurityPolicy *_securityPolicy;	// 56 = 0x38
    IMSDKAFNetworkReachabilityManager *_reachabilityManager;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_completionQueue;	// 72 = 0x48
    NSObject<OS_dispatch_group> *_completionGroup;	// 80 = 0x50
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001005f4fc8
+ (id)manager;	// IMP=0x00000001005f3d68
@property(retain, nonatomic) NSObject<OS_dispatch_group> *completionGroup; // @synthesize completionGroup=_completionGroup;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *completionQueue; // @synthesize completionQueue=_completionQueue;
@property(retain, nonatomic) IMSDKAFNetworkReachabilityManager *reachabilityManager; // @synthesize reachabilityManager=_reachabilityManager;
@property(retain, nonatomic) IMSDKAFSecurityPolicy *securityPolicy; // @synthesize securityPolicy=_securityPolicy;
@property(retain, nonatomic) NSURLCredential *credential; // @synthesize credential=_credential;
@property(nonatomic) _Bool shouldUseCredentialStorage; // @synthesize shouldUseCredentialStorage=_shouldUseCredentialStorage;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) IMSDKAFHTTPResponseSerializer<IMSDKAFURLResponseSerialization> *responseSerializer; // @synthesize responseSerializer=_responseSerializer;
@property(retain, nonatomic) IMSDKAFHTTPRequestSerializer<IMSDKAFURLRequestSerialization> *requestSerializer; // @synthesize requestSerializer=_requestSerializer;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (void).cxx_destruct;	// IMP=0x00000001005f5550
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001005f52dc
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001005f518c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001005f4fd0
- (id)description;	// IMP=0x00000001005f4ed0
- (id)DELETE:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001005f4dec
- (id)PATCH:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001005f4d08
- (id)PUT:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001005f4c24
- (id)POST:(id)arg1 parameters:(id)arg2 constructingBodyWithBlock:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;	// IMP=0x00000001005f48dc
- (id)POST:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001005f47f8
- (id)HEAD:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001005f4654
- (id)GET:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001005f4570
- (id)HTTPRequestOperationWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;	// IMP=0x00000001005f4370
- (id)HTTPRequestOperationWithHTTPMethod:(id)arg1 URLString:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;	// IMP=0x00000001005f4064
- (id)initWithBaseURL:(id)arg1;	// IMP=0x00000001005f3da4
- (id)init;	// IMP=0x00000001005f3d94

@end

