//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMSDKAFNetworkReachabilityManager : NSObject
{
    long long _networkReachabilityStatus;	// 8 = 0x8
    struct __SCNetworkReachability *_networkReachability;	// 16 = 0x10
    CDUnknownBlockType _networkReachabilityStatusBlock;	// 24 = 0x18
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;	// IMP=0x0000000100637934
+ (id)managerForAddress:(const void *)arg1;	// IMP=0x00000001006370e8
+ (id)managerForDomain:(id)arg1;	// IMP=0x0000000100637058
+ (id)sharedManager;	// IMP=0x0000000100636f5c
@property(copy, nonatomic) CDUnknownBlockType networkReachabilityStatusBlock; // @synthesize networkReachabilityStatusBlock=_networkReachabilityStatusBlock;
@property(nonatomic) struct __SCNetworkReachability *networkReachability; // @synthesize networkReachability=_networkReachability;
@property(nonatomic) long long networkReachabilityStatus; // @synthesize networkReachabilityStatus=_networkReachabilityStatus;
- (void).cxx_destruct;	// IMP=0x0000000100637a74
- (void)setReachabilityStatusChangeBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100637928
- (id)localizedNetworkReachabilityStatusString;	// IMP=0x000000010063790c
- (void)stopMonitoring;	// IMP=0x00000001006378b0
- (void)startMonitoring;	// IMP=0x0000000100637300
@property(readonly, nonatomic, getter=isReachableViaWiFi) _Bool reachableViaWiFi;
@property(readonly, nonatomic, getter=isReachableViaWWAN) _Bool reachableViaWWAN;
@property(readonly, nonatomic, getter=isReachable) _Bool reachable;
- (void)dealloc;	// IMP=0x0000000100637208
- (id)init;	// IMP=0x00000001006371d0
- (id)initWithReachability:(struct __SCNetworkReachability *)arg1;	// IMP=0x000000010063713c

@end

