//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMSDKFriendDelegate.h"

@class NSString;

@interface IMSDKFriendWhatsAppManager : NSObject <IMSDKFriendDelegate>
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100933684
+ (id)sharedInstance;	// IMP=0x0000000100933418
- (void)handleOpenURL:(id)arg1;	// IMP=0x0000000100934168
- (id)fetchSourceNameFromUrl:(id)arg1;	// IMP=0x0000000100933db4
- (void)share:(id)arg1 handle:(CDUnknownBlockType)arg2;	// IMP=0x0000000100933d48
- (void)sendMessage:(id)arg1 handle:(CDUnknownBlockType)arg2;	// IMP=0x00000001009337c4
- (void)inviteWithContent:(id)arg1 handle:(CDUnknownBlockType)arg2;	// IMP=0x0000000100933758
- (void)getFriendWithPage:(int)arg1 pageSize:(int)arg2 handle:(CDUnknownBlockType)arg3;	// IMP=0x00000001009336e8
- (id)mutablecopyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001009336d4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001009336ac
- (id)initSingleton;	// IMP=0x00000001009334f4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

