//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMSDKMTAEvent.h"

#import "IMSDKMTAEventProtocol.h"

@class NSString;

@interface IMSDKMTAErrorEvent : IMSDKMTAEvent <IMSDKMTAEventProtocol>
{
    unsigned int _attr;	// 40 = 0x28
    NSString *_error;	// 48 = 0x30
    NSString *_availableMemory;	// 56 = 0x38
    NSString *_freeDiskSpace;	// 64 = 0x40
    NSString *_processName;	// 72 = 0x48
}

@property(copy, nonatomic) NSString *processName; // @synthesize processName=_processName;
@property(copy, nonatomic) NSString *freeDiskSpace; // @synthesize freeDiskSpace=_freeDiskSpace;
@property(copy, nonatomic) NSString *availableMemory; // @synthesize availableMemory=_availableMemory;
@property unsigned int attr; // @synthesize attr=_attr;
@property(copy, nonatomic) NSString *error; // @synthesize error=_error;
- (void).cxx_destruct;	// IMP=0x0000000100654760
- (id)init;	// IMP=0x0000000100654628
- (void)encode:(id)arg1;	// IMP=0x00000001006537b8
- (int)getType;	// IMP=0x00000001006537b0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

