//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MidasBaseWebViewController.h"

@class MidasVerifyCodePageJSCallback;

@interface MidasVerifyCodeWebViewController : MidasBaseWebViewController
{
    id <MidasIAPOperationProtocol> _operation;	// 8 = 0x8
    MidasVerifyCodePageJSCallback *_verifyCodePageJSCallback;	// 16 = 0x10
    unsigned long long _fkVerifyType;	// 24 = 0x18
}

@property(nonatomic) unsigned long long fkVerifyType; // @synthesize fkVerifyType=_fkVerifyType;
@property(retain, nonatomic) MidasVerifyCodePageJSCallback *verifyCodePageJSCallback; // @synthesize verifyCodePageJSCallback=_verifyCodePageJSCallback;
@property(nonatomic) __weak id <MidasIAPOperationProtocol> operation; // @synthesize operation=_operation;
- (void).cxx_destruct;	// IMP=0x00000001005792a4
- (void)midasWebView:(id)arg1 pageDidFinishLoad:(id)arg2;	// IMP=0x00000001005790fc
- (void)midasWebView:(id)arg1 pageDidFailLoad:(id)arg2;	// IMP=0x0000000100578fcc
- (void)midasWebView:(id)arg1 pageDidStartLoad:(id)arg2;	// IMP=0x0000000100578e78
- (void)_judgeMidasFKVerifyType:(id)arg1;	// IMP=0x0000000100578aac
- (void)_configureSize;	// IMP=0x0000000100578910
- (id)_configureURL:(id)arg1;	// IMP=0x000000010057800c
- (id)jsCallBack;	// IMP=0x0000000100577fac
- (id)initWithOperation:(id)arg1 webViewClosedBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100577e2c
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100577df4
- (void)viewDidLoad;	// IMP=0x0000000100577dbc

@end

