//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MidasIAPReportListenerProtocol.h"

@class NSMutableArray;

@interface MidasIAPStatics : NSObject <MidasIAPReportListenerProtocol>
{
    NSMutableArray *_eventListeners;	// 8 = 0x8
}

+ (void)load;	// IMP=0x00000001005c1cd4
@property(retain, nonatomic) NSMutableArray *eventListeners; // @synthesize eventListeners=_eventListeners;
- (void).cxx_destruct;	// IMP=0x00000001005c2a24
- (void)constructEventListeners;	// IMP=0x00000001005c258c
- (void)onNotify:(id)arg1;	// IMP=0x00000001005c253c
- (void)onReport:(id)arg1;	// IMP=0x00000001005c2530
- (void)postEvent:(id)arg1;	// IMP=0x00000001005c232c
- (void)addEventListener:(id)arg1;	// IMP=0x00000001005c227c
- (void)cleanUp;	// IMP=0x00000001005c2260
- (void)dealloc;	// IMP=0x00000001005c211c
- (id)init;	// IMP=0x00000001005c2070

@end

