//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MidasIAPConcurrentJob.h"

@class MidasCommunicator, NSDictionary, NSString;

@interface MidasIAPGetConfigJob : MidasIAPConcurrentJob
{
    MidasCommunicator *_comm;	// 8 = 0x8
    _Bool _netError;	// 16 = 0x10
    id <MidasIAPOperationProtocol> _operation;	// 24 = 0x18
    long long _ret;	// 32 = 0x20
    NSString *_inner;	// 40 = 0x28
    NSString *_msg;	// 48 = 0x30
    NSDictionary *_content;	// 56 = 0x38
}

@property(copy, nonatomic) NSDictionary *content; // @synthesize content=_content;
@property(nonatomic) _Bool netError; // @synthesize netError=_netError;
@property(copy, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(copy, nonatomic) NSString *inner; // @synthesize inner=_inner;
@property(nonatomic) long long ret; // @synthesize ret=_ret;
@property(nonatomic) __weak id <MidasIAPOperationProtocol> operation; // @synthesize operation=_operation;
- (void).cxx_destruct;	// IMP=0x00000001005225d8
- (void)jobMainProc;	// IMP=0x000000010052206c
- (void)stop;	// IMP=0x0000000100521f70
- (void)start;	// IMP=0x0000000100521d04
- (void)dealloc;	// IMP=0x0000000100521bc4

@end

