//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MidasIAPBaseReq.h"

@class NSMutableArray;

@interface MidasIAPIntroPriceInfoReq : MidasIAPBaseReq
{
    _Bool _fromApple;	// 112 = 0x70
    NSMutableArray *_introPriceProuctIds;	// 120 = 0x78
}

@property(nonatomic) _Bool fromApple; // @synthesize fromApple=_fromApple;
@property(retain, nonatomic) NSMutableArray *introPriceProuctIds; // @synthesize introPriceProuctIds=_introPriceProuctIds;
- (void).cxx_destruct;	// IMP=0x00000001005d5d70
- (_Bool)validateParams;	// IMP=0x00000001005d5bd8
- (id)init;	// IMP=0x00000001005d5b00

@end

