//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MidasIAPNavCtrl, UIViewController;

@interface MidasIAPCtrlMgr : NSObject
{
    MidasIAPNavCtrl *_nav;	// 8 = 0x8
    _Bool _needShowLoadingAfterDismiss;	// 16 = 0x10
    UIViewController *_rootViewController;	// 24 = 0x18
}

+ (void)deInstance;	// IMP=0x0000000100525d14
+ (id)instance;	// IMP=0x0000000100525c7c
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void).cxx_destruct;	// IMP=0x0000000100526334
- (void)showAlertWithTitle:(id)arg1 body:(id)arg2 animation:(_Bool)arg3 dismissCompletion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100526200
- (id)topViewController;	// IMP=0x0000000100526160
- (unsigned long long)getViewControllerCount;	// IMP=0x0000000100526108
- (void)dismiss;	// IMP=0x000000010052604c
- (void)popCtrl:(_Bool)arg1;	// IMP=0x0000000100525f98
- (void)pushCtrl:(id)arg1 ainimated:(_Bool)arg2;	// IMP=0x0000000100525d3c
- (_Bool)hasUi;	// IMP=0x0000000100525d24

@end

