//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MidasConfig : NSObject
{
    _Bool _logEnable;	// 8 = 0x8
    _Bool _showResultPage;	// 9 = 0x9
}

@property(nonatomic) _Bool showResultPage; // @synthesize showResultPage=_showResultPage;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100576044
@property(nonatomic) long long logFileDays;
@property(nonatomic) long long logFileSize;
@property(nonatomic) _Bool disableReport;
@property(nonatomic) _Bool logEnable;
- (void)setTimeout:(id)arg1;	// IMP=0x0000000100575f60
- (id)networkTimeout;	// IMP=0x0000000100575f4c
- (void)parseConfig:(id)arg1;	// IMP=0x00000001005758f0
- (id)init;	// IMP=0x0000000100575884

@end

