//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MidasCommunicatorBase.h"

@interface MidasCommunicator : MidasCommunicatorBase
{
}

- (void)reportEmptyAppUserName:(_Bool)arg1 operation:(id)arg2;	// IMP=0x000000010053dcd4
- (void)callIAPQueryCgi:(id)arg1 productIds:(id)arg2 netErr:(CDUnknownBlockType)arg3 err:(CDUnknownBlockType)arg4 succ:(CDUnknownBlockType)arg5;	// IMP=0x000000010053d1ac
- (void)callSecurityProcCgi:(id)arg1 identity:(id)arg2 netErr:(CDUnknownBlockType)arg3 err:(CDUnknownBlockType)arg4 succ:(CDUnknownBlockType)arg5;	// IMP=0x000000010053cb60
- (void)callGetPayResult:(id)arg1 netErr:(CDUnknownBlockType)arg2 err:(CDUnknownBlockType)arg3 succ:(CDUnknownBlockType)arg4;	// IMP=0x000000010053c5c8
- (void)callOldCheckCgi:(id)arg1 transaction:(id)arg2 netErr:(CDUnknownBlockType)arg3 err:(CDUnknownBlockType)arg4 succ:(CDUnknownBlockType)arg5;	// IMP=0x000000010053b998
- (void)callCheckCgi:(id)arg1 netErr:(CDUnknownBlockType)arg2 err:(CDUnknownBlockType)arg3 succ:(CDUnknownBlockType)arg4;	// IMP=0x000000010053af18
- (void)callGetUserNameCgi:(id)arg1 netErr:(CDUnknownBlockType)arg2 err:(CDUnknownBlockType)arg3 succ:(CDUnknownBlockType)arg4;	// IMP=0x000000010053a328
- (void)callHBNetErr:(CDUnknownBlockType)arg1 err:(CDUnknownBlockType)arg2 succ:(CDUnknownBlockType)arg3;	// IMP=0x0000000100539e00
- (void)callReportCgi:(id)arg1 netErr:(CDUnknownBlockType)arg2 err:(CDUnknownBlockType)arg3 succ:(CDUnknownBlockType)arg4;	// IMP=0x00000001005398d4
- (void)callReprovideCgi:(id)arg1 transaction:(id)arg2 netErr:(CDUnknownBlockType)arg3 err:(CDUnknownBlockType)arg4 succ:(CDUnknownBlockType)arg5;	// IMP=0x0000000100538354
- (void)callReprovideCgi:(id)arg1 netErr:(CDUnknownBlockType)arg2 err:(CDUnknownBlockType)arg3 succ:(CDUnknownBlockType)arg4;	// IMP=0x0000000100537520
- (void)callProvideCgi:(id)arg1 netErr:(CDUnknownBlockType)arg2 err:(CDUnknownBlockType)arg3 succ:(CDUnknownBlockType)arg4;	// IMP=0x00000001005358e0
- (void)callOrderCgi:(id)arg1 netErr:(CDUnknownBlockType)arg2 err:(CDUnknownBlockType)arg3 succ:(CDUnknownBlockType)arg4;	// IMP=0x0000000100534258
- (void)callGetConfigCgi:(id)arg1 cmd:(id)arg2 netErr:(CDUnknownBlockType)arg3 err:(CDUnknownBlockType)arg4 succ:(CDUnknownBlockType)arg5;	// IMP=0x0000000100533438

@end

