//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MidasIAPConcurrentJob.h"

@class NSData, NSError;

@interface MidasIAPDCJob : MidasIAPConcurrentJob
{
    _Bool _started;	// 8 = 0x8
    NSData *_token;	// 16 = 0x10
    NSError *_error;	// 24 = 0x18
}

+ (_Bool)supported;	// IMP=0x00000001005318d0
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, copy, nonatomic) NSData *token; // @synthesize token=_token;
- (void).cxx_destruct;	// IMP=0x00000001005325a4
- (void)jobMainProc;	// IMP=0x0000000100531d78
- (void)stop;	// IMP=0x0000000100531c7c
- (void)start;	// IMP=0x0000000100531a38
- (void)dealloc;	// IMP=0x00000001005318f8

@end

