//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface MidasIAPTitleView : UIView
{
    id <MidasIAPTitleViewDelegate> _delegate;	// 8 = 0x8
    UIButton *_backButton;	// 16 = 0x10
    UIButton *_closeButton;	// 24 = 0x18
    UILabel *_titleLabel;	// 32 = 0x20
    UIView *_divider;	// 40 = 0x28
}

@property(nonatomic) __weak UIView *divider; // @synthesize divider=_divider;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak UIButton *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) __weak id <MidasIAPTitleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100592c90
- (void)onClose:(id)arg1;	// IMP=0x0000000100592adc
- (void)onBack:(id)arg1;	// IMP=0x0000000100592a2c
- (id)initFromNib;	// IMP=0x00000001005928e0

@end

