//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MTAWX : NSObject
{
    NSString *_appkey;	// 8 = 0x8
}

+ (void)onBackground;	// IMP=0x000000010150fa58
+ (void)startWithAppkey:(id)arg1;	// IMP=0x000000010150f9a4
+ (id)ConvertWXappkey:(id)arg1;	// IMP=0x000000010150f940
+ (id)getInstance;	// IMP=0x000000010150f8b0
@property(retain, nonatomic) NSString *appkey; // @synthesize appkey=_appkey;
- (void)dealloc;	// IMP=0x000000010150fb10
- (id)init;	// IMP=0x000000010150fad8

@end

