//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (MD5)
- (long long)fira_64LeastSignificantBits;	// IMP=0x00000001008ede38
- (long long)fira_64LSBMD5;	// IMP=0x00000001008eddec
- (id)fira_MD5Data;	// IMP=0x00000001008edd40
@end

