//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (GTMZLibAdditions)
+ (id)gtm_dataByRawInflatingData:(id)arg1 error:(id *)arg2;	// IMP=0x000000010092a968
+ (id)gtm_dataByRawInflatingData:(id)arg1;	// IMP=0x000000010092a958
+ (id)gtm_dataByRawInflatingBytes:(const void *)arg1 length:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000010092a940
+ (id)gtm_dataByRawInflatingBytes:(const void *)arg1 length:(unsigned long long)arg2;	// IMP=0x000000010092a930
+ (id)gtm_dataByRawDeflatingData:(id)arg1 compressionLevel:(int)arg2 error:(id *)arg3;	// IMP=0x000000010092a894
+ (id)gtm_dataByRawDeflatingData:(id)arg1 compressionLevel:(int)arg2;	// IMP=0x000000010092a884
+ (id)gtm_dataByRawDeflatingBytes:(const void *)arg1 length:(unsigned long long)arg2 compressionLevel:(int)arg3 error:(id *)arg4;	// IMP=0x000000010092a86c
+ (id)gtm_dataByRawDeflatingBytes:(const void *)arg1 length:(unsigned long long)arg2 compressionLevel:(int)arg3;	// IMP=0x000000010092a85c
+ (id)gtm_dataByRawDeflatingData:(id)arg1 error:(id *)arg2;	// IMP=0x000000010092a7c4
+ (id)gtm_dataByRawDeflatingData:(id)arg1;	// IMP=0x000000010092a7b4
+ (id)gtm_dataByRawDeflatingBytes:(const void *)arg1 length:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000010092a798
+ (id)gtm_dataByRawDeflatingBytes:(const void *)arg1 length:(unsigned long long)arg2;	// IMP=0x000000010092a788
+ (id)gtm_dataByInflatingData:(id)arg1 error:(id *)arg2;	// IMP=0x000000010092a6f4
+ (id)gtm_dataByInflatingData:(id)arg1;	// IMP=0x000000010092a6e4
+ (id)gtm_dataByInflatingBytes:(const void *)arg1 length:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000010092a6cc
+ (id)gtm_dataByInflatingBytes:(const void *)arg1 length:(unsigned long long)arg2;	// IMP=0x000000010092a6bc
+ (id)gtm_dataByDeflatingData:(id)arg1 compressionLevel:(int)arg2 error:(id *)arg3;	// IMP=0x000000010092a620
+ (id)gtm_dataByDeflatingData:(id)arg1 compressionLevel:(int)arg2;	// IMP=0x000000010092a610
+ (id)gtm_dataByDeflatingBytes:(const void *)arg1 length:(unsigned long long)arg2 compressionLevel:(int)arg3 error:(id *)arg4;	// IMP=0x000000010092a5f8
+ (id)gtm_dataByDeflatingBytes:(const void *)arg1 length:(unsigned long long)arg2 compressionLevel:(int)arg3;	// IMP=0x000000010092a5e8
+ (id)gtm_dataByDeflatingData:(id)arg1 error:(id *)arg2;	// IMP=0x000000010092a550
+ (id)gtm_dataByDeflatingData:(id)arg1;	// IMP=0x000000010092a540
+ (id)gtm_dataByDeflatingBytes:(const void *)arg1 length:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000010092a524
+ (id)gtm_dataByDeflatingBytes:(const void *)arg1 length:(unsigned long long)arg2;	// IMP=0x000000010092a514
+ (id)gtm_dataByGzippingData:(id)arg1 compressionLevel:(int)arg2 error:(id *)arg3;	// IMP=0x000000010092a478
+ (id)gtm_dataByGzippingData:(id)arg1 compressionLevel:(int)arg2;	// IMP=0x000000010092a468
+ (id)gtm_dataByGzippingBytes:(const void *)arg1 length:(unsigned long long)arg2 compressionLevel:(int)arg3 error:(id *)arg4;	// IMP=0x000000010092a450
+ (id)gtm_dataByGzippingBytes:(const void *)arg1 length:(unsigned long long)arg2 compressionLevel:(int)arg3;	// IMP=0x000000010092a440
+ (id)gtm_dataByGzippingData:(id)arg1 error:(id *)arg2;	// IMP=0x000000010092a3a8
+ (id)gtm_dataByGzippingData:(id)arg1;	// IMP=0x000000010092a398
+ (id)gtm_dataByGzippingBytes:(const void *)arg1 length:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000010092a37c
+ (id)gtm_dataByGzippingBytes:(const void *)arg1 length:(unsigned long long)arg2;	// IMP=0x000000010092a36c
@end

