//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableArray.h"

@interface NSMutableArray (IMSDK)
+ (void)ensureStorePath:(id)arg1;	// IMP=0x0000000100638684
- (void)writeToStore:(id)arg1;	// IMP=0x000000010063895c
- (id)initWithStore:(id)arg1;	// IMP=0x00000001006387dc
@end

