//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FMetalResourceData;

@interface NSObject (TMetalResouceHeap)
- (_Bool)isAliasable:(_Bool)arg1;	// IMP=0x00000001021e6758
- (void)makeAliasable:(_Bool)arg1;	// IMP=0x00000001021e66ac
- (int)metalType;	// IMP=0x00000001021e6680
- (id)heap:(_Bool)arg1;	// IMP=0x00000001021e6630
- (id)metalHeap;	// IMP=0x00000001021e6600
@property(retain, nonatomic) FMetalResourceData *resourceData; // @dynamic resourceData;
@end

