//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Vungle)
- (id)vng_calculateSHA;	// IMP=0x0000000100af2ee4
- (id)vng_creativeID;	// IMP=0x0000000100af2e1c
@end

