//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (ContentType)
+ (id)contentTypeForImageUTIValue:(struct __CFString *)arg1;	// IMP=0x0000000101391134
- (unsigned long long)contentCategoryForFile;	// IMP=0x0000000101391420
- (id)contentTypeForFile;	// IMP=0x0000000101391214
@end

