//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableDictionary.h"

@class NSMutableArray;

@interface OrderedDictionary : NSMutableDictionary
{
    NSMutableDictionary *dictionary;	// 8 = 0x8
    NSMutableArray *array;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100b5e71c
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2;	// IMP=0x0000000100b5e4bc
- (id)keyAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100b5e4a4
- (void)insertObject:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3;	// IMP=0x0000000100b5e3d0
- (id)reverseKeyEnumerator;	// IMP=0x0000000100b5e3b8
- (id)keyEnumerator;	// IMP=0x0000000100b5e3a0
- (id)objectForKey:(id)arg1;	// IMP=0x0000000100b5e388
- (unsigned long long)count;	// IMP=0x0000000100b5e370
- (void)removeObjectForKey:(id)arg1;	// IMP=0x0000000100b5e2fc
- (void)setObject:(id)arg1 forKey:(id)arg2;	// IMP=0x0000000100b5e244
- (id)copy;	// IMP=0x0000000100b5e238
- (id)initWithCapacity:(unsigned long long)arg1;	// IMP=0x0000000100b5e168
- (id)init;	// IMP=0x0000000100b5e09c

@end

