//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SimplePingDelegate.h"

@class NSMutableDictionary, NSString, NSThread, SimplePing;

@interface PingDelegate : NSObject <SimplePingDelegate>
{
    unsigned char _getPackageNumber;	// 8 = 0x8
    unsigned char _timeOut;	// 9 = 0x9
    unsigned char _packageNumber;	// 10 = 0xa
    SimplePing *_pinger;	// 16 = 0x10
    NSMutableDictionary *_pingTimeRecorderDict;	// 24 = 0x18
    NSString *_returnMessage;	// 32 = 0x20
    unsigned long long _totalPingTime;	// 40 = 0x28
    unsigned long long _maxPingTime;	// 48 = 0x30
    unsigned long long _minPingTime;	// 56 = 0x38
    NSThread *_pingThread;	// 64 = 0x40
    CDUnknownFunctionPointerType _pingCallback;	// 72 = 0x48
    NSString *_ip;	// 80 = 0x50
}

@property(retain) NSString *ip; // @synthesize ip=_ip;
@property unsigned char packageNumber; // @synthesize packageNumber=_packageNumber;
@property unsigned char timeOut; // @synthesize timeOut=_timeOut;
@property CDUnknownFunctionPointerType pingCallback; // @synthesize pingCallback=_pingCallback;
@property(retain) NSThread *pingThread; // @synthesize pingThread=_pingThread;
@property unsigned long long minPingTime; // @synthesize minPingTime=_minPingTime;
@property unsigned long long maxPingTime; // @synthesize maxPingTime=_maxPingTime;
@property unsigned long long totalPingTime; // @synthesize totalPingTime=_totalPingTime;
@property(nonatomic) unsigned char getPackageNumber; // @synthesize getPackageNumber=_getPackageNumber;
@property(retain, nonatomic) NSString *returnMessage; // @synthesize returnMessage=_returnMessage;
@property(retain, nonatomic) NSMutableDictionary *pingTimeRecorderDict; // @synthesize pingTimeRecorderDict=_pingTimeRecorderDict;
@property(retain, nonatomic) SimplePing *pinger; // @synthesize pinger=_pinger;
- (void).cxx_destruct;	// IMP=0x000000010001e838
- (void)simplePing:(id)arg1 didReceiveUnexpectedPacket:(id)arg2;	// IMP=0x000000010001e6a8
- (void)simplePing:(id)arg1 didReceivePingResponsePacket:(id)arg2 sequenceNumber:(unsigned short)arg3;	// IMP=0x000000010001e41c
- (void)simplePing:(id)arg1 didFailToSendPacket:(id)arg2 sequenceNumber:(unsigned short)arg3 error:(id)arg4;	// IMP=0x000000010001e338
- (void)simplePing:(id)arg1 didSendPacket:(id)arg2 sequenceNumber:(unsigned short)arg3;	// IMP=0x000000010001e180
- (void)pingTimer;	// IMP=0x000000010001de78
- (void)simplePing:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x000000010001dd50
- (void)simplePing:(id)arg1 didStartWithAddress:(id)arg2;	// IMP=0x000000010001d9d4
- (id)toIP:(id)arg1;	// IMP=0x000000010001d794
- (int)hexStringToInt:(BOOL)arg1;	// IMP=0x000000010001d770
- (void)keepLoopRun;	// IMP=0x000000010001d76c
- (id)init;	// IMP=0x000000010001d6e4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

