//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PLCrashReportSignalInfo : NSObject
{
    NSString *_name;	// 8 = 0x8
    NSString *_code;	// 16 = 0x10
    unsigned long long _address;	// 24 = 0x18
}

@property(readonly, nonatomic) unsigned long long address; // @synthesize address=_address;
@property(readonly, nonatomic) NSString *code; // @synthesize code=_code;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void)dealloc;	// IMP=0x0000000101582410
- (id)initWithSignalName:(id)arg1 code:(id)arg2 address:(unsigned long long)arg3;	// IMP=0x0000000101582360

@end

