//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQApi : NSObject
{
}

+ (void)cgiShareReportWithMessage:(id)arg1 andActtype:(int)arg2 andReporttype:(int)arg3 andCallsource:(int)arg4;	// IMP=0x0000000100b303cc
+ (id)supportShareScheme;	// IMP=0x0000000100b303c4
+ (_Bool)openTIMApp;	// IMP=0x0000000100b30318
+ (_Bool)openQQApp;	// IMP=0x0000000100b3026c
+ (id)getTIMInstallURL;	// IMP=0x0000000100b30260
+ (id)getQQInstallURL;	// IMP=0x0000000100b30254
+ (_Bool)isQQSupportApiForDataLine;	// IMP=0x0000000100b30248
+ (_Bool)isTIMSupportApi;	// IMP=0x0000000100b30240
+ (_Bool)isQQSupportApi;	// IMP=0x0000000100b30234
+ (_Bool)isTIMSupportQZoneMediaShare;	// IMP=0x0000000100b3022c
+ (_Bool)isQQSupportQZoneMediaShare;	// IMP=0x0000000100b30220
+ (_Bool)isQQSupportQZoneShare;	// IMP=0x0000000100b30214
+ (_Bool)isQIMInstalled;	// IMP=0x0000000100b30208
+ (_Bool)isTIMInstalled;	// IMP=0x0000000100b301fc
+ (_Bool)isQQInstalled;	// IMP=0x0000000100b301f0
+ (id)getAdItemArray;	// IMP=0x0000000100b301c4
+ (id)handleOpenURL:(id)arg1;	// IMP=0x0000000100b301b0
+ (id)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 annotation:(id)arg3;	// IMP=0x0000000100b3019c
+ (int)sendMessage:(id)arg1;	// IMP=0x0000000100b2f8b4
+ (int)sendMessage_TIMNotInstalledOrOld:(id)arg1 isOld:(_Bool)arg2;	// IMP=0x0000000100b2f8a4
+ (int)sendMessage_QQNotInstalledOrOld:(id)arg1 isOld:(_Bool)arg2;	// IMP=0x0000000100b2f894
+ (void)showErrorWithWebView:(id)arg1;	// IMP=0x0000000100b2f810
+ (_Bool)checkQQApiURLMessage:(id)arg1;	// IMP=0x0000000100b2f5a4
+ (void)registerPluginWithId:(id)arg1;	// IMP=0x0000000100b2ee38
+ (void)registerAccessToken:(id)arg1;	// IMP=0x0000000100b2edfc
+ (void)registerQQConnectAppId:(id)arg1;	// IMP=0x0000000100b2edc0
+ (void)registerQQUin:(id)arg1;	// IMP=0x0000000100b2ed84
+ (void)registerQQConnectOpenId:(id)arg1;	// IMP=0x0000000100b2ed48
- (id)init;	// IMP=0x0000000100b2ed10

@end

