//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQApiURLObject.h"

@interface QQApiNewsObject : QQApiURLObject
{
}

+ (id)objectWithURL:(id)arg1 title:(id)arg2 description:(id)arg3 previewImageURL:(id)arg4;	// IMP=0x0000000100b32a00
+ (id)objectWithURL:(id)arg1 title:(id)arg2 description:(id)arg3 previewImageData:(id)arg4;	// IMP=0x0000000100b329c4

@end

