//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQApiInterface : NSObject
{
}

+ (void)reportSDKCheck:(int)arg1 cmd:(id)arg2 isQzone:(_Bool)arg3;	// IMP=0x0000000100b38efc
+ (id)getTIMInstallUrl;	// IMP=0x0000000100b38ee8
+ (id)getQQInstallUrl;	// IMP=0x0000000100b38ed4
+ (_Bool)openTIM;	// IMP=0x0000000100b38ec0
+ (_Bool)openQQ;	// IMP=0x0000000100b38eac
+ (_Bool)isTIMSupportApi;	// IMP=0x0000000100b38e98
+ (_Bool)isQQSupportApi;	// IMP=0x0000000100b38e84
+ (_Bool)isTIMInstalled;	// IMP=0x0000000100b38e70
+ (_Bool)isQQInstalled;	// IMP=0x0000000100b38e5c
+ (int)SendReqToQZone:(id)arg1;	// IMP=0x0000000100b38db8
+ (int)sendReq:(id)arg1;	// IMP=0x0000000100b38d14
+ (int)sendMessageToQQQZoneWithReq:(id)arg1;	// IMP=0x0000000100b38ba8
+ (int)sendMessageToQQWithReq:(id)arg1;	// IMP=0x0000000100b38af4
+ (_Bool)handleOpenURL:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000100b3898c
+ (_Bool)responseToSendMessageToQQ:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000100b3889c
+ (int)responseToShowMessageFromQQ:(id)arg1;	// IMP=0x0000000100b38888
+ (int)responseToGetMessageFromQQ:(id)arg1;	// IMP=0x0000000100b38874
+ (int)SendMessageToQQRequest:(id)arg1;	// IMP=0x0000000100b38860
+ (void)getMessageRequestFromQQ:(id)arg1;	// IMP=0x0000000100b38820
+ (void)showMessageRequestFromQQ:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000100b387a8

@end

