//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQApiObject.h"

@class NSData, NSURL;

@interface QQApiURLObject : QQApiObject
{
    int _targetContentType;	// 40 = 0x28
    NSURL *_url;	// 48 = 0x30
    NSData *_previewImageData;	// 56 = 0x38
    NSURL *_previewImageURL;	// 64 = 0x40
}

+ (id)objectWithURL:(id)arg1 title:(id)arg2 description:(id)arg3 previewImageURL:(id)arg4 targetContentType:(int)arg5;	// IMP=0x0000000100b32644
+ (id)objectWithURL:(id)arg1 title:(id)arg2 description:(id)arg3 previewImageData:(id)arg4 targetContentType:(int)arg5;	// IMP=0x0000000100b325d4
+ (id)objectWithURL:(id)arg1;	// IMP=0x0000000100b323ec
@property(retain, nonatomic) NSURL *previewImageURL; // @synthesize previewImageURL=_previewImageURL;
@property(retain, nonatomic) NSData *previewImageData; // @synthesize previewImageData=_previewImageData;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) int targetContentType; // @synthesize targetContentType=_targetContentType;
- (void)dealloc;	// IMP=0x0000000100b326b4
- (id)initWithURL:(id)arg1 title:(id)arg2 description:(id)arg3 previewImageURL:(id)arg4 targetContentType:(int)arg5;	// IMP=0x0000000100b32500
- (id)initWithURL:(id)arg1 title:(id)arg2 description:(id)arg3 previewImageData:(id)arg4 targetContentType:(int)arg5;	// IMP=0x0000000100b3242c
- (id)initWithURL:(id)arg1;	// IMP=0x0000000100b32388

@end

