//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseResp.h"

@interface ShowMessageFromWXResp : BaseResp
{
}

- (void)dealloc;	// IMP=0x00000001015179c4
- (id)init;	// IMP=0x000000010151798c

@end

