//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TencentLoginDelegate.h"

@class NSString, TencentOAuth;

@interface TencentIncrAuthLogic : NSObject <TencentLoginDelegate>
{
    TencentOAuth *_tencentOAuth;	// 8 = 0x8
    NSString *_reportAction;	// 16 = 0x10
}

@property(retain, nonatomic) NSString *reportAction; // @synthesize reportAction=_reportAction;
@property(nonatomic) TencentOAuth *tencentOAuth; // @synthesize tencentOAuth=_tencentOAuth;
- (void).cxx_destruct;	// IMP=0x0000000100b2bd84
- (void)tencentDidNotNetWork;	// IMP=0x0000000100b2bcfc
- (void)tencentDidNotLogin:(_Bool)arg1;	// IMP=0x0000000100b2bca4
- (void)tencentDidLogin;	// IMP=0x0000000100b2bc10
- (id)initWithTencentOAuth:(id)arg1;	// IMP=0x0000000100b2bb98

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

