//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TracerouteCommon : NSObject
{
}

+ (id)formatIPv4Address:(struct in_addr)arg1;	// IMP=0x00000001000235cc
+ (id)formatIPv6Address:(struct in6_addr)arg1;	// IMP=0x0000000100023548
+ (struct ICMPPacket *)unpackICMPv6Packet:(char *)arg1 len:(int)arg2;	// IMP=0x0000000100023540
+ (struct ICMPPacket *)unpackICMPv4Packet:(char *)arg1 len:(int)arg2;	// IMP=0x00000001000234f8
+ (_Bool)isPortUnReachablePacket:(char *)arg1 len:(int)arg2;	// IMP=0x00000001000234b8
+ (_Bool)isTimeoutPacket:(char *)arg1 len:(int)arg2 isIPv6:(_Bool)arg3;	// IMP=0x0000000100023454
+ (_Bool)isEchoReplyPacket:(char *)arg1 len:(int)arg2 isIPv6:(_Bool)arg3;	// IMP=0x00000001000233f4
+ (id)resolveHost:(id)arg1;	// IMP=0x00000001000231a8
+ (id)makeICMPPacketWithID:(unsigned short)arg1 sequence:(unsigned short)arg2 isICMPv6:(_Bool)arg3;	// IMP=0x0000000100023084
+ (struct sockaddr *)makeSockaddrWithAddress:(id)arg1 port:(int)arg2 isIPv6:(_Bool)arg3;	// IMP=0x0000000100022ebc
+ (unsigned short)makeChecksumFor:(const void *)arg1 len:(unsigned long long)arg2;	// IMP=0x0000000100022e60

@end

