//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, UIImage;

@interface TSETweetURLAttachmentMetadata : NSObject
{
    NSURL *_URL;	// 8 = 0x8
    NSString *_URLTitle;	// 16 = 0x10
    UIImage *_linkPreview;	// 24 = 0x18
}

@property(readonly, nonatomic) UIImage *linkPreview; // @synthesize linkPreview=_linkPreview;
@property(readonly, copy, nonatomic) NSString *URLTitle; // @synthesize URLTitle=_URLTitle;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;	// IMP=0x000000010088fea0
- (id)initWithURL:(id)arg1 title:(id)arg2 linkPreview:(id)arg3;	// IMP=0x000000010088fd78

@end

