//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextStorage.h"

@class NSMutableAttributedString;

@interface TSETweetTextStorage : NSTextStorage
{
    _Bool _highlightEntities;	// 8 = 0x8
    NSMutableAttributedString *_backingStore;	// 16 = 0x10
}

@property(nonatomic) _Bool highlightEntities; // @synthesize highlightEntities=_highlightEntities;
- (void).cxx_destruct;	// IMP=0x0000000100881838
- (void)performReplacementsForRange:(struct _NSRange)arg1;	// IMP=0x00000001008816ec
- (void)applyStylesToRange:(struct _NSRange)arg1;	// IMP=0x0000000100881468
- (void)processEditing;	// IMP=0x0000000100881400
- (void)setAttributes:(id)arg1 range:(struct _NSRange)arg2;	// IMP=0x00000001008812a0
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;	// IMP=0x00000001008811c4
- (id)attributesAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;	// IMP=0x0000000100881158
- (id)string;	// IMP=0x0000000100881104
@property(readonly, nonatomic) NSMutableAttributedString *backingStore; // @synthesize backingStore=_backingStore;

@end

