//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface TSEThrottledProperty : NSObject
{
    id <TSEThrottledPropertyObserver> _observer;	// 8 = 0x8
    id _lastValue;	// 16 = 0x10
    double _throttleInterval;	// 24 = 0x18
    NSTimer *_timer;	// 32 = 0x20
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(readonly, nonatomic) double throttleInterval; // @synthesize throttleInterval=_throttleInterval;
@property(retain, nonatomic) id lastValue; // @synthesize lastValue=_lastValue;
@property(nonatomic) __weak id <TSEThrottledPropertyObserver> observer; // @synthesize observer=_observer;
- (void).cxx_destruct;	// IMP=0x0000000100891140
- (void)_tseui_throttledPropertyTimerFired:(id)arg1;	// IMP=0x0000000100890f6c
- (id)initWithThottleInterval:(double)arg1 observer:(id)arg2;	// IMP=0x0000000100890edc

@end

