//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSNumber, NSString;

@interface TSEUIScribeEvent : NSObject
{
    NSNumber *_userID;	// 8 = 0x8
    NSString *_element;	// 16 = 0x10
    NSString *_action;	// 24 = 0x18
    NSDictionary *_parameters;	// 32 = 0x20
}

@property(readonly, copy, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(readonly, copy, nonatomic) NSString *action; // @synthesize action=_action;
@property(readonly, copy, nonatomic) NSString *element; // @synthesize element=_element;
@property(readonly, nonatomic) NSNumber *userID; // @synthesize userID=_userID;
- (void).cxx_destruct;	// IMP=0x00000001008900a4
- (id)description;	// IMP=0x0000000100890000
- (id)initWithUser:(id)arg1 element:(id)arg2 action:(id)arg3;	// IMP=0x000000010088fef4

@end

