//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TWTRAuthConfig;

@interface TwitterNetworking : NSObject
{
    TWTRAuthConfig *_authConfig;	// 8 = 0x8
}

+ (id)defaultAdditionalHeaders;	// IMP=0x00000001007f66a4
+ (id)defaultConfiguration;	// IMP=0x00000001007f6584
+ (id)URLSession;	// IMP=0x00000001007f640c
@property(readonly, nonatomic) TWTRAuthConfig *authConfig; // @synthesize authConfig=_authConfig;
- (void).cxx_destruct;	// IMP=0x00000001007f6b90
- (id)operationQueue;	// IMP=0x00000001007f6b00
- (id)URLRequestWithMethod:(id)arg1 URL:(id)arg2 parameters:(id)arg3;	// IMP=0x00000001007f677c
- (void)sendAsynchronousRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001007f60ac
- (id)DELETE:(id)arg1 parameters:(id)arg2;	// IMP=0x00000001007f6044
- (id)POST:(id)arg1 parameters:(id)arg2;	// IMP=0x00000001007f5fdc
- (id)GET:(id)arg1 parameters:(id)arg2;	// IMP=0x00000001007f5f74
- (id)initWithAuthConfig:(id)arg1;	// IMP=0x00000001007f5ef0

@end

