//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TWTRImages : NSObject
{
}

+ (id)resourcesImageNamed:(id)arg1;	// IMP=0x000000010085cf8c
+ (id)resourcePathForImageName:(id)arg1;	// IMP=0x000000010085cde0
+ (id)buttonImageWithCornerRadius:(double)arg1 backgroundColor:(id)arg2 borderColor:(id)arg3;	// IMP=0x000000010085cc34
+ (id)buttonImageWithCornerRadius:(double)arg1 backgroundColor:(id)arg2;	// IMP=0x000000010085cc24
+ (id)closeButtonTemplateImage;	// IMP=0x000000010085cbc4
+ (id)vineBadgeImage;	// IMP=0x000000010085cbb0
+ (id)mediaScrubberThumb;	// IMP=0x000000010085cb9c
+ (id)mediaReplayTemplateImage;	// IMP=0x000000010085cb3c
+ (id)mediaPlayTemplateImage;	// IMP=0x000000010085cadc
+ (id)mediaPauseTemplateImage;	// IMP=0x000000010085ca7c
+ (id)playIcon;	// IMP=0x000000010085ca68
+ (id)verifiedIcon;	// IMP=0x000000010085ca54
+ (id)darkRetweet;	// IMP=0x000000010085ca40
+ (id)lightRetweet;	// IMP=0x000000010085ca2c
+ (id)retweetImageForBackgroundColor:(id)arg1;	// IMP=0x000000010085c9a4
+ (id)shareImageLarge;	// IMP=0x000000010085c990
+ (id)shareImage;	// IMP=0x000000010085c97c
+ (id)retweetImage;	// IMP=0x000000010085c968
+ (id)likeImageSheetLarge;	// IMP=0x000000010085c954
+ (id)likeOffLarge;	// IMP=0x000000010085c940
+ (id)likeOnLarge;	// IMP=0x000000010085c92c
+ (id)likeImageSheet;	// IMP=0x000000010085c918
+ (id)likeOff;	// IMP=0x000000010085c904
+ (id)likeOn;	// IMP=0x000000010085c8f0

@end

