//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TWTRTweetRepository : NSObject
{
    id <TWTRTweetCache> _cache;	// 8 = 0x8
}

+ (id)cacheDirectoryPath;	// IMP=0x0000000100828d6c
+ (id)sortedArrayWithArray:(id)arg1 withIDsArray:(id)arg2;	// IMP=0x0000000100828aac
+ (id)sharedInstance;	// IMP=0x000000010082766c
@property(retain, nonatomic) id <TWTRTweetCache> cache; // @synthesize cache=_cache;
- (void).cxx_destruct;	// IMP=0x0000000100828ff4
- (id)lookupRequestForTweetIDs:(id)arg1 APIClient:(id)arg2 additionalParameters:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100828df0
- (void)loadCachedTweetsWithIDs:(id)arg1 perspective:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001008285c8
- (void)cacheTweet:(id)arg1 perspective:(id)arg2;	// IMP=0x00000001008284d0
- (void)cacheTweet:(id)arg1;	// IMP=0x0000000100828458
- (void)loadTweetsWithIDs:(id)arg1 APIClient:(id)arg2 additionalParameters:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100827814
- (id)initWithCache:(id)arg1;	// IMP=0x0000000100827790

@end

