//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TWTRVideoPlayerScribeDelegate.h"
#import "TWTRVideoPlayerViewDelegate.h"

@class NSString, TWTRSynchronizerDisplayLinkWrapper, TWTRVideoControlsView, TWTRVideoPlayerView;

@interface TWTRVideoControlsViewSynchronizer : NSObject <TWTRVideoPlayerViewDelegate, TWTRVideoPlayerScribeDelegate>
{
    _Bool _disableSynchronization;	// 8 = 0x8
    _Bool _presentsVideoControlsOnReady;	// 9 = 0x9
    TWTRVideoControlsView *_controlsView;	// 16 = 0x10
    TWTRVideoPlayerView *_videoPlayerView;	// 24 = 0x18
    id <TWTRVideoPlayerScribeDelegate> _scribeDelegate;	// 32 = 0x20
    TWTRSynchronizerDisplayLinkWrapper *_displayLinkWrapper;	// 40 = 0x28
    long long _playbackStateBeforeScrubbing;	// 48 = 0x30
}

@property(nonatomic) long long playbackStateBeforeScrubbing; // @synthesize playbackStateBeforeScrubbing=_playbackStateBeforeScrubbing;
@property(readonly, nonatomic) TWTRSynchronizerDisplayLinkWrapper *displayLinkWrapper; // @synthesize displayLinkWrapper=_displayLinkWrapper;
@property(nonatomic) _Bool presentsVideoControlsOnReady; // @synthesize presentsVideoControlsOnReady=_presentsVideoControlsOnReady;
@property(nonatomic) __weak id <TWTRVideoPlayerScribeDelegate> scribeDelegate; // @synthesize scribeDelegate=_scribeDelegate;
@property(readonly, nonatomic) __weak TWTRVideoPlayerView *videoPlayerView; // @synthesize videoPlayerView=_videoPlayerView;
@property(readonly, nonatomic) __weak TWTRVideoControlsView *controlsView; // @synthesize controlsView=_controlsView;
- (void).cxx_destruct;	// IMP=0x0000000100820b5c
- (void)videoPlayer:(id)arg1 didPlayPercentOfMedia:(unsigned long long)arg2 playbackConfiguration:(id)arg3;	// IMP=0x00000001008209cc
- (void)videoPlayerDidBecomeReady:(id)arg1;	// IMP=0x00000001008208dc
- (void)videoPlayer:(id)arg1 didChangePlaybackState:(long long)arg2;	// IMP=0x0000000100820894
- (void)handleActionButton;	// IMP=0x0000000100820854
- (void)handleScrubberValueChange;	// IMP=0x0000000100820758
- (void)handleScrubberTouchUp;	// IMP=0x00000001008206e4
- (void)handleScrubberTouchDown;	// IMP=0x0000000100820644
- (id)displayStringForTimeInterval:(double)arg1;	// IMP=0x00000001008205e8
- (void)updateTimeLabelWithElapsedTime:(double)arg1 duration:(double)arg2;	// IMP=0x00000001008204d8
- (void)synchronizeUI;	// IMP=0x00000001008203b0
- (CDUnknownBlockType)displayLinkDidFireBlock;	// IMP=0x0000000100820270
- (void)dealloc;	// IMP=0x0000000100820194
- (id)initWithVideoPlayer:(id)arg1 controls:(id)arg2;	// IMP=0x000000010081fe88

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

