//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface TWTRBirdView : UIView
{
    UIColor *_birdColor;	// 8 = 0x8
    struct CGSize _desiredSize;	// 16 = 0x10
}

+ (id)mediumBird;	// IMP=0x0000000100841488
+ (id)smallBird;	// IMP=0x0000000100841450
@property(nonatomic) struct CGSize desiredSize; // @synthesize desiredSize=_desiredSize;
- (void).cxx_destruct;	// IMP=0x000000010084172c
@property(retain, nonatomic) UIColor *birdColor; // @synthesize birdColor=_birdColor;
- (struct CGSize)intrinsicContentSize;	// IMP=0x0000000100841634
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x000000010084155c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001008414c0

@end

