//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString, NSURLRequest, NSUUID;

@interface TWTRNetworkingPipelinePackage : NSObject <NSCopying>
{
    NSURLRequest *_request;	// 8 = 0x8
    id <TWTRSessionStore> _sessionStore;	// 16 = 0x10
    NSString *_userID;	// 24 = 0x18
    CDUnknownBlockType _callback;	// 32 = 0x20
    long long _attemptCounter;	// 40 = 0x28
    NSUUID *_UUID;	// 48 = 0x30
}

+ (id)packageWithRequest:(id)arg1 sessionStore:(id)arg2 userID:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100819110
@property(readonly, nonatomic) NSUUID *UUID; // @synthesize UUID=_UUID;
@property(nonatomic) long long attemptCounter; // @synthesize attemptCounter=_attemptCounter;
@property(readonly, copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(readonly, copy, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(readonly, nonatomic) id <TWTRSessionStore> sessionStore; // @synthesize sessionStore=_sessionStore;
@property(readonly, copy, nonatomic) NSURLRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;	// IMP=0x00000001008192e4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001008191d0
- (id)copyForRetry;	// IMP=0x00000001008190c4
- (id)initWithRequest:(id)arg1 sessionStore:(id)arg2 userID:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100818eb4

@end

