//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet, TWTRTimelineFilter;

@interface TWTRTimelineFilterManager : NSObject
{
    TWTRTimelineFilter *_filters;	// 8 = 0x8
    NSSet *_filteredHashtags;	// 16 = 0x10
    NSSet *_filteredUrls;	// 24 = 0x18
    NSSet *_filteredHandles;	// 32 = 0x20
    NSSet *_filteredKeywords;	// 40 = 0x28
    unsigned long long _totalFilteredTweets;	// 48 = 0x30
}

@property(nonatomic) unsigned long long totalFilteredTweets; // @synthesize totalFilteredTweets=_totalFilteredTweets;
@property(copy, nonatomic) NSSet *filteredKeywords; // @synthesize filteredKeywords=_filteredKeywords;
@property(copy, nonatomic) NSSet *filteredHandles; // @synthesize filteredHandles=_filteredHandles;
@property(copy, nonatomic) NSSet *filteredUrls; // @synthesize filteredUrls=_filteredUrls;
@property(copy, nonatomic) NSSet *filteredHashtags; // @synthesize filteredHashtags=_filteredHashtags;
@property(copy, nonatomic) TWTRTimelineFilter *filters; // @synthesize filters=_filters;
- (void).cxx_destruct;	// IMP=0x000000010082318c
- (id)hostFromURLString:(id)arg1;	// IMP=0x0000000100822f4c
- (id)lowercaseText:(id)arg1;	// IMP=0x0000000100822e58
- (id)hostsSetFromStrings:(id)arg1;	// IMP=0x0000000100822c5c
- (id)lowercaseSetFromStrings:(id)arg1;	// IMP=0x0000000100822a58
- (id)setFromUsernameEntities:(id)arg1;	// IMP=0x0000000100822890
- (id)setFromURLEntities:(id)arg1;	// IMP=0x00000001008226bc
- (id)setFromHashtagsEntities:(id)arg1;	// IMP=0x00000001008224f4
- (_Bool)text:(id)arg1 containsWord:(id)arg2;	// IMP=0x0000000100822404
- (_Bool)tweet:(id)arg1 containsKeywords:(id)arg2;	// IMP=0x00000001008221d0
- (_Bool)tweet:(id)arg1 containsUrls:(id)arg2;	// IMP=0x00000001008220f8
- (_Bool)tweet:(id)arg1 containsHashtags:(id)arg2;	// IMP=0x0000000100822020
- (_Bool)tweet:(id)arg1 containsHandles:(id)arg2;	// IMP=0x0000000100821eb0
- (id)filterTweetsWithEnumeration:(id)arg1;	// IMP=0x0000000100821934
- (id)filterTweets:(id)arg1;	// IMP=0x00000001008216b4
- (id)initWithFilters:(id)arg1;	// IMP=0x000000010082163c

@end

