//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TWTRImageLoaderTaskManager.h"

@class NSMutableDictionary, NSString;

@interface TWTRImageLoaderTaskManager : NSObject <TWTRImageLoaderTaskManager>
{
    NSMutableDictionary *_currentTasks;	// 8 = 0x8
}

@property(retain, nonatomic) NSMutableDictionary *currentTasks; // @synthesize currentTasks=_currentTasks;
- (void).cxx_destruct;	// IMP=0x0000000100873ac8
- (id)removeTaskWithRequestID:(id)arg1;	// IMP=0x000000010087399c
- (void)addTask:(id)arg1 withRequestID:(id)arg2;	// IMP=0x00000001008738d4
- (id)init;	// IMP=0x0000000100873854

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

