//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

#import "TWTRAttributedLabel.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSAttributedString, NSDictionary, NSString, TWTRTweetEntityRange, UIColor;

@interface TWTRAttributedLabel : UILabel <TWTRAttributedLabel, UIGestureRecognizerDelegate>
{
    _Bool _needsFramesetter;	// 8 = 0x8
    struct __CTFramesetter *_framesetter;	// 16 = 0x10
    struct __CTFramesetter *_highlightFramesetter;	// 24 = 0x18
    NSAttributedString *_attributedText;	// 32 = 0x20
    id <TWTRAttributedLabelDelegate> _delegate;	// 40 = 0x28
    NSArray *_entities;	// 48 = 0x30
    NSDictionary *_linkAttributes;	// 56 = 0x38
    NSDictionary *_activeLinkAttributes;	// 64 = 0x40
    NSDictionary *_inactiveLinkAttributes;	// 72 = 0x48
    double _shadowRadius;	// 80 = 0x50
    double _highlightedShadowRadius;	// 88 = 0x58
    UIColor *_highlightedShadowColor;	// 96 = 0x60
    double _kern;	// 104 = 0x68
    double _firstLineIndent;	// 112 = 0x70
    double _lineSpacing;	// 120 = 0x78
    double _minimumLineHeight;	// 128 = 0x80
    double _maximumLineHeight;	// 136 = 0x88
    double _lineHeightMultiple;	// 144 = 0x90
    long long _verticalAlignment;	// 152 = 0x98
    NSString *_truncationTokenString;	// 160 = 0xa0
    NSDictionary *_truncationTokenStringAttributes;	// 168 = 0xa8
    NSAttributedString *_inactiveAttributedText;	// 176 = 0xb0
    NSAttributedString *_renderedAttributedText;	// 184 = 0xb8
    TWTRTweetEntityRange *_activeLink;	// 192 = 0xc0
    NSArray *_accessibilityElements;	// 200 = 0xc8
    struct CGSize _highlightedShadowOffset;	// 208 = 0xd0
    struct UIEdgeInsets _textInsets;	// 224 = 0xe0
}

+ (struct CGSize)sizeThatFitsAttributedString:(id)arg1 withConstraints:(struct CGSize)arg2 limitedToNumberOfLines:(unsigned long long)arg3;	// IMP=0x000000010083a458
@property(retain, nonatomic) NSArray *accessibilityElements; // @synthesize accessibilityElements=_accessibilityElements;
@property(retain, nonatomic) TWTRTweetEntityRange *activeLink; // @synthesize activeLink=_activeLink;
@property(copy, nonatomic) NSAttributedString *renderedAttributedText; // @synthesize renderedAttributedText=_renderedAttributedText;
@property(copy, nonatomic) NSAttributedString *inactiveAttributedText; // @synthesize inactiveAttributedText=_inactiveAttributedText;
@property(retain, nonatomic) NSDictionary *truncationTokenStringAttributes; // @synthesize truncationTokenStringAttributes=_truncationTokenStringAttributes;
@property(retain, nonatomic) NSString *truncationTokenString; // @synthesize truncationTokenString=_truncationTokenString;
@property(nonatomic) long long verticalAlignment; // @synthesize verticalAlignment=_verticalAlignment;
@property(nonatomic) struct UIEdgeInsets textInsets; // @synthesize textInsets=_textInsets;
@property(nonatomic) double lineHeightMultiple; // @synthesize lineHeightMultiple=_lineHeightMultiple;
@property(nonatomic) double maximumLineHeight; // @synthesize maximumLineHeight=_maximumLineHeight;
@property(nonatomic) double minimumLineHeight; // @synthesize minimumLineHeight=_minimumLineHeight;
@property(nonatomic) double lineSpacing; // @synthesize lineSpacing=_lineSpacing;
@property(nonatomic) double firstLineIndent; // @synthesize firstLineIndent=_firstLineIndent;
@property(nonatomic) double kern; // @synthesize kern=_kern;
@property(retain, nonatomic) UIColor *highlightedShadowColor; // @synthesize highlightedShadowColor=_highlightedShadowColor;
@property(nonatomic) struct CGSize highlightedShadowOffset; // @synthesize highlightedShadowOffset=_highlightedShadowOffset;
@property(nonatomic) double highlightedShadowRadius; // @synthesize highlightedShadowRadius=_highlightedShadowRadius;
@property(nonatomic) double shadowRadius; // @synthesize shadowRadius=_shadowRadius;
@property(retain, nonatomic) NSDictionary *inactiveLinkAttributes; // @synthesize inactiveLinkAttributes=_inactiveLinkAttributes;
@property(retain, nonatomic) NSDictionary *activeLinkAttributes; // @synthesize activeLinkAttributes=_activeLinkAttributes;
@property(retain, nonatomic) NSDictionary *linkAttributes; // @synthesize linkAttributes=_linkAttributes;
@property(retain, nonatomic) NSArray *entities; // @synthesize entities=_entities;
@property(nonatomic) id <TWTRAttributedLabelDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSAttributedString *attributedText; // @synthesize attributedText=_attributedText;
- (void).cxx_destruct;	// IMP=0x0000000100840e28
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100840068
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010083f9ec
- (void)copy:(id)arg1;	// IMP=0x000000010083f974
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010083f8b8
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010083f574
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010083f428
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010083f310
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;	// IMP=0x000000010083f2fc
- (_Bool)canBecomeFirstResponder;	// IMP=0x000000010083f2f4
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x000000010083f1d0
- (void)tintColorDidChange;	// IMP=0x000000010083edd0
- (struct CGSize)intrinsicContentSize;	// IMP=0x000000010083ed7c
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010083ec2c
- (long long)indexOfAccessibilityElement:(id)arg1;	// IMP=0x000000010083e504
- (id)accessibilityElementAtIndex:(long long)arg1;	// IMP=0x000000010083e4a8
- (long long)accessibilityElementCount;	// IMP=0x000000010083e45c
- (_Bool)isAccessibilityElement;	// IMP=0x000000010083e454
- (void)drawTextInRect:(struct CGRect)arg1;	// IMP=0x000000010083dcf4
- (struct CGRect)textRectForBounds:(struct CGRect)arg1 limitedToNumberOfLines:(long long)arg2;	// IMP=0x000000010083db10
- (void)setTextColor:(id)arg1;	// IMP=0x000000010083da5c
- (id)textColor;	// IMP=0x000000010083d9dc
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x000000010083d988
- (void)setText:(id)arg1 afterInheritingLabelAttributesAndConfiguringWithBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000010083cd54
@property(copy, nonatomic) id text; // @dynamic text;
- (void)drawStrike:(struct __CTFrame *)arg1 inRect:(struct CGRect)arg2 context:(struct CGContext *)arg3;	// IMP=0x000000010083c59c
- (void)drawBackground:(struct __CTFrame *)arg1 inRect:(struct CGRect)arg2 context:(struct CGContext *)arg3;	// IMP=0x000000010083bedc
- (void)drawFramesetter:(struct __CTFramesetter *)arg1 attributedString:(id)arg2 textRange:(CDStruct_912cb5d2)arg3 inRect:(struct CGRect)arg4 context:(struct CGContext *)arg5;	// IMP=0x000000010083b6e0
- (struct CGRect)boundingRectForCharacterRange:(struct _NSRange)arg1;	// IMP=0x000000010083b534
- (long long)characterIndexAtPoint:(struct CGPoint)arg1;	// IMP=0x000000010083b1fc
- (id)entityAtPoint:(struct CGPoint)arg1;	// IMP=0x000000010083b1c4
- (id)entityAtCharacterIndex:(long long)arg1;	// IMP=0x000000010083b0dc
- (void)addLinksForTweetEntityRanges:(id)arg1 attributes:(id)arg2;	// IMP=0x000000010083ae4c
- (void)addLinksForEntityRanges:(id)arg1;	// IMP=0x000000010083add8
@property(nonatomic) double leading;
- (void)setHighlightFramesetter:(struct __CTFramesetter *)arg1;	// IMP=0x000000010083ad74
- (struct __CTFramesetter *)highlightFramesetter;	// IMP=0x000000010083ad64
- (void)setFramesetter:(struct __CTFramesetter *)arg1;	// IMP=0x000000010083ad18
- (struct __CTFramesetter *)framesetter;	// IMP=0x000000010083ac34
- (void)setNeedsFramesetter;	// IMP=0x000000010083abf8
- (void)dealloc;	// IMP=0x000000010083a3ec
- (void)commonInit;	// IMP=0x0000000100839fe8
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100839f70

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

