//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TWTRScribeSerializable.h"

@class NSString;

@interface TWTRScribeCardEvent : NSObject <TWTRScribeSerializable>
{
    unsigned long long _promotionCardType;	// 8 = 0x8
}

+ (id)scribeKey;	// IMP=0x0000000100804880
@property(readonly, nonatomic) unsigned long long promotionCardType; // @synthesize promotionCardType=_promotionCardType;
- (id)dictionaryRepresentation;	// IMP=0x00000001008048ac
- (id)initWithPromotionCardType:(unsigned long long)arg1;	// IMP=0x000000010080482c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

