//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface TWTRAuthConfig : NSObject <NSCoding>
{
    NSString *_consumerKey;	// 8 = 0x8
    NSString *_consumerSecret;	// 16 = 0x10
}

@property(copy, nonatomic) NSString *consumerSecret; // @synthesize consumerSecret=_consumerSecret;
@property(copy, nonatomic) NSString *consumerKey; // @synthesize consumerKey=_consumerKey;
- (void).cxx_destruct;	// IMP=0x00000001007fddc8
- (unsigned long long)hash;	// IMP=0x00000001007fdd44
- (_Bool)isEqualToAuthConfig:(id)arg1;	// IMP=0x00000001007fdc30
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001007fdbb0
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001007fdaec
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001007fda2c
- (id)initWithConsumerKey:(id)arg1 consumerSecret:(id)arg2;	// IMP=0x00000001007fd958

@end

