//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@interface UIApplication (XGPushHookSetDelegate)
+ (void)load;	// IMP=0x00000001014d8914
- (void)__xgpush_messaging_setDelegate:(id)arg1;	// IMP=0x00000001014d8948
@end

