//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class NSString, NSURL, NSURLRequest, UIActivityIndicatorView, UILabel, UINavigationController, UIWebView, VKError;

@interface VKAuthorizeController : UIViewController <UIWebViewDelegate>
{
    _Bool _finished;	// 8 = 0x8
    UIWebView *_webView;	// 16 = 0x10
    NSString *_appId;	// 24 = 0x18
    NSString *_scope;	// 32 = 0x20
    NSURL *_redirectUri;	// 40 = 0x28
    UIActivityIndicatorView *_activityMark;	// 48 = 0x30
    UILabel *_warningLabel;	// 56 = 0x38
    UILabel *_statusBar;	// 64 = 0x40
    VKError *_validationError;	// 72 = 0x48
    NSURLRequest *_lastRequest;	// 80 = 0x50
    UINavigationController *_internalNavigationController;	// 88 = 0x58
}

+ (id)buildAuthorizationURLWithContext:(id)arg1;	// IMP=0x0000000100b4db40
+ (void)presentThisController:(id)arg1;	// IMP=0x0000000100b4d88c
+ (void)presentForValidation:(id)arg1;	// IMP=0x0000000100b4d800
+ (void)presentForAuthorizeWithAppId:(id)arg1 andPermissions:(id)arg2 revokeAccess:(_Bool)arg3 displayType:(id)arg4;	// IMP=0x0000000100b4d730
@property(nonatomic) _Bool finished; // @synthesize finished=_finished;
@property(nonatomic) __weak UINavigationController *internalNavigationController; // @synthesize internalNavigationController=_internalNavigationController;
@property(retain, nonatomic) NSURLRequest *lastRequest; // @synthesize lastRequest=_lastRequest;
@property(retain, nonatomic) VKError *validationError; // @synthesize validationError=_validationError;
@property(retain, nonatomic) UILabel *statusBar; // @synthesize statusBar=_statusBar;
@property(retain, nonatomic) UILabel *warningLabel; // @synthesize warningLabel=_warningLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityMark; // @synthesize activityMark=_activityMark;
@property(retain, nonatomic) NSURL *redirectUri; // @synthesize redirectUri=_redirectUri;
@property(retain, nonatomic) NSString *scope; // @synthesize scope=_scope;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;	// IMP=0x0000000100b4fa6c
- (long long)preferredStatusBarStyle;	// IMP=0x0000000100b4f8cc
- (void)dismissWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100b4f4f0
- (void)cancelAuthorization:(id)arg1;	// IMP=0x0000000100b4f2b0
- (void)makeViewport;	// IMP=0x0000000100b4f1bc
- (void)webViewDidFinishLoad:(id)arg1;	// IMP=0x0000000100b4f01c
- (void)setRightBarButtonActivity;	// IMP=0x0000000100b4ef30
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;	// IMP=0x0000000100b4ed08
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;	// IMP=0x0000000100b4e8f8
- (void)startLoading;	// IMP=0x0000000100b4e7b4
- (void)viewDidLoad;	// IMP=0x0000000100b4e760
- (id)initWith:(id)arg1 andPermissions:(id)arg2 revokeAccess:(_Bool)arg3 displayType:(id)arg4;	// IMP=0x0000000100b4e5cc
- (void)didRotateFromInterfaceOrientation:(long long)arg1;	// IMP=0x0000000100b4e578
- (void)loadView;	// IMP=0x0000000100b4dfb8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

