//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

#import "NSCoding.h"

@class NSMutableDictionary, NSOperationQueue;

@interface VKHTTPClient : VKObject <NSCoding>
{
    NSOperationQueue *_operationQueue;	// 8 = 0x8
    NSMutableDictionary *_defaultHeaders;	// 16 = 0x10
}

+ (id)getClient;	// IMP=0x0000000100b4b880
@property(retain, nonatomic) NSMutableDictionary *defaultHeaders; // @synthesize defaultHeaders=_defaultHeaders;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void).cxx_destruct;	// IMP=0x0000000100b4d21c
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100b4d124
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100b4d0a8
- (void)enqueueBatchOfHTTPRequestOperations:(id)arg1 progressBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100b4c8ac
- (void)enqueueOperation:(id)arg1;	// IMP=0x0000000100b4c82c
- (id)multipartFormRequestWithMethod:(id)arg1 path:(id)arg2 images:(id)arg3;	// IMP=0x0000000100b4c334
- (id)requestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3 secure:(_Bool)arg4;	// IMP=0x0000000100b4bf00
- (void)setDefaultHeader:(id)arg1 value:(id)arg2;	// IMP=0x0000000100b4be70
- (id)defaultValueForHeader:(id)arg1;	// IMP=0x0000000100b4bdec
- (id)init;	// IMP=0x0000000100b4b8d8

@end

