//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKApiObject.h"

@class NSNumber, NSString, VKPhotoSizes;

@interface VKPhoto : VKApiObject
{
    NSNumber *_id;	// 8 = 0x8
    NSNumber *_album_id;	// 16 = 0x10
    NSNumber *_owner_id;	// 24 = 0x18
    NSString *_photo_75;	// 32 = 0x20
    NSString *_photo_130;	// 40 = 0x28
    NSString *_photo_604;	// 48 = 0x30
    NSString *_photo_807;	// 56 = 0x38
    NSString *_photo_1280;	// 64 = 0x40
    NSString *_photo_2560;	// 72 = 0x48
    NSNumber *_width;	// 80 = 0x50
    NSNumber *_height;	// 88 = 0x58
    NSString *_text;	// 96 = 0x60
    NSNumber *_date;	// 104 = 0x68
    VKPhotoSizes *_sizes;	// 112 = 0x70
}

@property(retain, nonatomic) VKPhotoSizes *sizes; // @synthesize sizes=_sizes;
@property(retain, nonatomic) NSNumber *date; // @synthesize date=_date;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSNumber *height; // @synthesize height=_height;
@property(retain, nonatomic) NSNumber *width; // @synthesize width=_width;
@property(retain, nonatomic) NSString *photo_2560; // @synthesize photo_2560=_photo_2560;
@property(retain, nonatomic) NSString *photo_1280; // @synthesize photo_1280=_photo_1280;
@property(retain, nonatomic) NSString *photo_807; // @synthesize photo_807=_photo_807;
@property(retain, nonatomic) NSString *photo_604; // @synthesize photo_604=_photo_604;
@property(retain, nonatomic) NSString *photo_130; // @synthesize photo_130=_photo_130;
@property(retain, nonatomic) NSString *photo_75; // @synthesize photo_75=_photo_75;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
@property(retain, nonatomic) NSNumber *album_id; // @synthesize album_id=_album_id;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;	// IMP=0x0000000100b5b4d4
@property(readonly, nonatomic) NSString *attachmentString;

@end

