//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSDate;

@interface VKRequestTiming : VKObject
{
    NSDate *_parseStartTime;	// 8 = 0x8
    NSDate *_startTime;	// 16 = 0x10
    NSDate *_finishTime;	// 24 = 0x18
    double _loadTime;	// 32 = 0x20
    double _parseTime;	// 40 = 0x28
}

@property(nonatomic) double parseTime; // @synthesize parseTime=_parseTime;
@property(nonatomic) double loadTime; // @synthesize loadTime=_loadTime;
@property(retain, nonatomic) NSDate *finishTime; // @synthesize finishTime=_finishTime;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;	// IMP=0x0000000100b56ef0
@property(readonly, nonatomic) double totalTime;
- (void)finished;	// IMP=0x0000000100b56dfc
- (void)parseFinished;	// IMP=0x0000000100b56da0
- (void)parseStarted;	// IMP=0x0000000100b56d5c
- (void)loaded;	// IMP=0x0000000100b56d00
- (void)started;	// IMP=0x0000000100b56cbc
- (id)description;	// IMP=0x0000000100b56c40

@end

