//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKUploadPhotoBase.h"

@interface VKUploadWallPhotoRequest : VKUploadPhotoBase
{
}

- (id)getSaveRequest:(id)arg1;	// IMP=0x0000000100b4967c
- (id)getServerRequest;	// IMP=0x0000000100b495d0
- (id)initWithImage:(id)arg1 parameters:(id)arg2 userId:(long long)arg3 groupId:(long long)arg4;	// IMP=0x0000000100b49524

@end

