//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString;

@interface VungleFlexViewAnimator : NSObject <UIViewControllerAnimatedTransitioning>
{
    _Bool _isPresentation;	// 8 = 0x8
}

@property(nonatomic) _Bool isPresentation; // @synthesize isPresentation=_isPresentation;
- (void)animateTransition:(id)arg1;	// IMP=0x0000000100a9cbf0
- (double)transitionDuration:(id)arg1;	// IMP=0x0000000100a9cbe4
- (id)initWithIsPresentation:(_Bool)arg1;	// IMP=0x0000000100a9cb90

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

