//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class VungleAd, VungleCacheManager, VungleNetworkManager, VungleOperationQueue;

@interface VungleAdPreparer : NSObject
{
    VungleNetworkManager *_networkManager;	// 8 = 0x8
    VungleCacheManager *_cacheManager;	// 16 = 0x10
    VungleOperationQueue *_queue;	// 24 = 0x18
    VungleAd *_adBeingPrepared;	// 32 = 0x20
}

+ (id)buildErrorWithVungleMRAIDAd:(id)arg1;	// IMP=0x0000000100ac7104
@property(retain, nonatomic) VungleAd *adBeingPrepared; // @synthesize adBeingPrepared=_adBeingPrepared;
@property(readonly, nonatomic) VungleOperationQueue *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) __weak VungleCacheManager *cacheManager; // @synthesize cacheManager=_cacheManager;
@property(readonly, nonatomic) __weak VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
- (void).cxx_destruct;	// IMP=0x0000000100ade8a0
- (void)prepareAd:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100ade828
- (id)initWithNetworkManager:(id)arg1 cacheManager:(id)arg2;	// IMP=0x0000000100ade750

@end

