//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VungleAdReport.h"

#import "VNGPersistable.h"
#import "VungleReportable.h"

@class NSArray, NSMutableArray, NSString;

@interface VungleMRAIDAdReport : VungleAdReport <VungleReportable, VNGPersistable>
{
    _Bool _internalIncentivized;	// 8 = 0x8
    NSString *_templateID;	// 16 = 0x10
    NSMutableArray *_privateUserActions;	// 24 = 0x18
    NSMutableArray *_privateClickthrough;	// 32 = 0x20
    NSMutableArray *_privateErrors;	// 40 = 0x28
}

@property(retain, nonatomic) NSMutableArray *privateErrors; // @synthesize privateErrors=_privateErrors;
@property(retain, nonatomic) NSMutableArray *privateClickthrough; // @synthesize privateClickthrough=_privateClickthrough;
@property(retain, nonatomic) NSMutableArray *privateUserActions; // @synthesize privateUserActions=_privateUserActions;
@property(copy, nonatomic) NSString *templateID; // @synthesize templateID=_templateID;
@property(nonatomic) _Bool internalIncentivized; // @synthesize internalIncentivized=_internalIncentivized;
- (void).cxx_destruct;	// IMP=0x0000000100aec8f8
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100aec38c
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100aec254
- (_Bool)incentivized;	// IMP=0x0000000100aec248
- (id)placement;	// IMP=0x0000000100aec23c
- (void)setPlacement:(id)arg1;	// IMP=0x0000000100aec230
- (void)setPublisherInformation:(id)arg1;	// IMP=0x0000000100aec16c
- (void)setExtraInformation:(id)arg1;	// IMP=0x0000000100aec124
- (void)setDeviceInformation:(id)arg1;	// IMP=0x0000000100aec0dc
- (unsigned long long)duration;	// IMP=0x0000000100aec0d0
- (_Bool)isAdExperienceSuccessful;	// IMP=0x0000000100aec00c
- (void)setPlacementInformation:(id)arg1;	// IMP=0x0000000100aebfc4
- (id)uniqueIdentifier;	// IMP=0x0000000100aebf60
- (id)toDictionary;	// IMP=0x0000000100aebc20
- (void)appendVungleMRAIDErrorCode:(id)arg1;	// IMP=0x0000000100aebbd0
@property(readonly, nonatomic) NSArray *errors;
@property(readonly, nonatomic) NSArray *clickthrough;
@property(readonly, nonatomic) NSArray *userActions;
- (void)appendClickthrough:(id)arg1;	// IMP=0x0000000100aebab4
- (void)appendUserAction:(id)arg1 withValue:(id)arg2 timeStamp:(unsigned long long)arg3;	// IMP=0x0000000100aeb8d4
- (void)appendUserAction:(id)arg1 withValue:(id)arg2;	// IMP=0x0000000100aeb824
- (void)appendUserAction:(id)arg1;	// IMP=0x0000000100aeb798
- (void)appendUserAction:(id)arg1 timeStamp:(unsigned long long)arg2;	// IMP=0x0000000100aeb55c
- (id)init;	// IMP=0x0000000100aeb478

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

