//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface VungleZipArchiver : NSObject
{
    NSString *_path;	// 8 = 0x8
    NSString *_filename;	// 16 = 0x10
    void *_zip;	// 24 = 0x18
    _Bool _open;	// 32 = 0x20
    _Bool _close;	// 33 = 0x21
}

+ (id)_dateWithMSDOSFormat:(unsigned int)arg1;	// IMP=0x0000000100ae5df0
+ (_Bool)createZipFileAtPath:(id)arg1 withContentsOfDirectory:(id)arg2 keepParentDirectory:(_Bool)arg3 withPassword:(id)arg4;	// IMP=0x0000000100ae507c
+ (_Bool)createZipFileAtPath:(id)arg1 withContentsOfDirectory:(id)arg2 withPassword:(id)arg3;	// IMP=0x0000000100ae5000
+ (_Bool)createZipFileAtPath:(id)arg1 withFilesAtPaths:(id)arg2 withPassword:(id)arg3;	// IMP=0x0000000100ae4e34
+ (_Bool)createZipFileAtPath:(id)arg1 withContentsOfDirectory:(id)arg2 keepParentDirectory:(_Bool)arg3;	// IMP=0x0000000100ae4dcc
+ (_Bool)createZipFileAtPath:(id)arg1 withContentsOfDirectory:(id)arg2;	// IMP=0x0000000100ae4d74
+ (_Bool)createZipFileAtPath:(id)arg1 withFilesAtPaths:(id)arg2;	// IMP=0x0000000100ae4d1c
+ (_Bool)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 overwrite:(_Bool)arg3 password:(id)arg4 error:(id *)arg5 delegate:(id)arg6 progressHandler:(CDUnknownBlockType)arg7 completionHandler:(CDUnknownBlockType)arg8;	// IMP=0x0000000100ae3b18
+ (_Bool)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 progressHandler:(CDUnknownBlockType)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0000000100ae3a68
+ (_Bool)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 overwrite:(_Bool)arg3 password:(id)arg4 progressHandler:(CDUnknownBlockType)arg5 completionHandler:(CDUnknownBlockType)arg6;	// IMP=0x0000000100ae3994
+ (_Bool)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 overwrite:(_Bool)arg3 password:(id)arg4 error:(id *)arg5 delegate:(id)arg6;	// IMP=0x0000000100ae38d4
+ (_Bool)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 delegate:(id)arg3;	// IMP=0x0000000100ae3844
+ (_Bool)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 overwrite:(_Bool)arg3 password:(id)arg4 error:(id *)arg5;	// IMP=0x0000000100ae37a4
+ (_Bool)unzipFileAtPath:(id)arg1 toDestination:(id)arg2;	// IMP=0x0000000100ae3744
@property(readonly, nonatomic, getter=isClosed) _Bool close; // @synthesize close=_close;
@property(readonly, nonatomic, getter=isOpen) _Bool open; // @synthesize open=_open;
- (void).cxx_destruct;	// IMP=0x0000000100ae5fa8
- (_Bool)close;	// IMP=0x0000000100ae5dc8
- (_Bool)writeData:(id)arg1 filename:(id)arg2 withPassword:(id)arg3;	// IMP=0x0000000100ae5c10
- (_Bool)writeFileAtPath:(id)arg1 withFileName:(id)arg2 withPassword:(id)arg3;	// IMP=0x0000000100ae58f8
- (_Bool)writeFile:(id)arg1 withPassword:(id)arg2;	// IMP=0x0000000100ae5898
- (_Bool)writeFolderAtPath:(id)arg1 withFolderName:(id)arg2 withPassword:(id)arg3;	// IMP=0x0000000100ae560c
- (void)zipInfo:(CDStruct_b33206b2 *)arg1 setDate:(id)arg2;	// IMP=0x0000000100ae5504
- (_Bool)open;	// IMP=0x0000000100ae54b4
- (id)initWithPath:(id)arg1;	// IMP=0x0000000100ae5428

@end

