//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface VungleTapPassingView : UIView
{
    UIView *_forwardView;	// 8 = 0x8
}

@property(retain, nonatomic) UIView *forwardView; // @synthesize forwardView=_forwardView;
- (void).cxx_destruct;	// IMP=0x0000000100ae2140
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0000000100ae1fb0
- (id)init;	// IMP=0x0000000100ae1f00

@end

