//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VungleOperation.h"

@class NSFileManager, VungleThirdPartyMRAIDAd;

@interface VunglePrepareThirdPartyMRAIDAdOperation : VungleOperation
{
    NSFileManager *_fileManager;	// 24 = 0x18
    VungleThirdPartyMRAIDAd *_thirdPartyAd;	// 32 = 0x20
    CDUnknownBlockType _completionHandler;	// 40 = 0x28
}

+ (id)localIndexCreationErrorWithUserInfo:(id)arg1;	// IMP=0x0000000100af8df4
+ (id)campaignDirectoryCreationErrorWithUserInfo:(id)arg1;	// IMP=0x0000000100af8d58
+ (id)invalidBase64Error;	// IMP=0x0000000100af8c80
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) __weak VungleThirdPartyMRAIDAd *thirdPartyAd; // @synthesize thirdPartyAd=_thirdPartyAd;
@property(retain, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
- (void).cxx_destruct;	// IMP=0x0000000100af8f04
- (_Bool)writeIndexHTMLFileWithBaseURL:(id)arg1 markup:(id)arg2 ad:(id)arg3;	// IMP=0x0000000100af8b18
- (id)createCampaignDirectoryWithAd:(id)arg1;	// IMP=0x0000000100af89c4
- (id)decodeHTMLWithAd:(id)arg1;	// IMP=0x0000000100af890c
- (id)expectedLocalIndexURLWithCampaignID:(id)arg1;	// IMP=0x0000000100af8824
- (void)finishOperationWithInvalidAd:(id)arg1 error:(id)arg2;	// IMP=0x0000000100af876c
- (void)execute;	// IMP=0x0000000100af8568
- (id)initWithVungleMRAIDAd:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100af8478

@end

