//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VungleNetworkOperation.h"

@class NSDictionary;

@interface VungleUploadOperation : VungleNetworkOperation
{
    NSDictionary *_content;	// 24 = 0x18
}

@property(copy, nonatomic) NSDictionary *content; // @synthesize content=_content;
- (void).cxx_destruct;	// IMP=0x0000000100acc7f0
- (id)getOperationContent;	// IMP=0x0000000100acc7c8
- (id)compressed;	// IMP=0x0000000100acc59c
- (void)prepareRequest:(id)arg1;	// IMP=0x0000000100acc46c
- (id)taskWithRequest:(id)arg1 session:(id)arg2;	// IMP=0x0000000100acc388
- (id)initWithURL:(id)arg1 content:(id)arg2 session:(id)arg3 taskSetupCompletionBlock:(CDUnknownBlockType)arg4;	// IMP=0x0000000100acc2b8

@end

