//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VungleOperation.h"

@class NSDictionary, NSString, VungleWebViewFacade;

@interface VungleJSCommandOperation : VungleOperation
{
    _Bool _isArbitraryJavascript;	// 24 = 0x18
    id <VungleJSCommandDelegate><VungleMRAIDCommandDelegate> _delegate;	// 32 = 0x20
    CDUnknownBlockType _resultBlock;	// 40 = 0x28
    NSString *_command;	// 48 = 0x30
    NSDictionary *_parameters;	// 56 = 0x38
    VungleWebViewFacade *_webViewFacade;	// 64 = 0x40
}

@property(retain, nonatomic) VungleWebViewFacade *webViewFacade; // @synthesize webViewFacade=_webViewFacade;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(retain, nonatomic) NSString *command; // @synthesize command=_command;
@property(nonatomic) _Bool isArbitraryJavascript; // @synthesize isArbitraryJavascript=_isArbitraryJavascript;
@property(copy, nonatomic) CDUnknownBlockType resultBlock; // @synthesize resultBlock=_resultBlock;
@property(nonatomic) __weak id <VungleJSCommandDelegate><VungleMRAIDCommandDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100ad68f0
- (id)constructJavascriptExpression;	// IMP=0x0000000100ad680c
- (void)execute;	// IMP=0x0000000100ad6808
- (void)finishWithErrors:(id)arg1;	// IMP=0x0000000100ad6470
- (id)initWithCommand:(id)arg1 parameters:(id)arg2 webViewFacade:(id)arg3 resultBlock:(CDUnknownBlockType)arg4;	// IMP=0x0000000100ad6328
- (id)initWithCommand:(id)arg1 parameters:(id)arg2 webViewFacade:(id)arg3;	// IMP=0x0000000100ad62ac

@end

