//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSMutableData, NSString, NSTimer, NSURLConnection;

@interface WechatAuthSDK : NSObject
{
    NSString *_sdkVersion;	// 8 = 0x8
    id <WechatAuthAPIDelegate> _delegate;	// 16 = 0x10
    _Bool _isAuthing;	// 24 = 0x18
    unsigned int _retContentLength;	// 28 = 0x1c
    unsigned int _status;	// 32 = 0x20
    NSURLConnection *connection;	// 40 = 0x28
    NSMutableData *respData;	// 48 = 0x30
    NSString *uuid;	// 56 = 0x38
    NSData *qrCodeData;	// 64 = 0x40
    NSString *authCode;	// 72 = 0x48
    NSTimer *timer;	// 80 = 0x50
    long long lastState;	// 88 = 0x58
    long long _httpRetStatusCode;	// 96 = 0x60
}

@property(nonatomic) long long httpRetStatusCode; // @synthesize httpRetStatusCode=_httpRetStatusCode;
@property(nonatomic) _Bool isAuthing; // @synthesize isAuthing=_isAuthing;
@property(nonatomic) unsigned int status; // @synthesize status=_status;
@property(nonatomic) unsigned int retContentLength; // @synthesize retContentLength=_retContentLength;
@property(nonatomic) long long lastState; // @synthesize lastState;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer;
@property(retain, nonatomic) NSString *authCode; // @synthesize authCode;
@property(retain, nonatomic) NSData *qrCodeData; // @synthesize qrCodeData;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid;
@property(retain, nonatomic) NSMutableData *respData; // @synthesize respData;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection;
@property(readonly, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(nonatomic) __weak id <WechatAuthAPIDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000101508340
- (void)connectionDidFinishLoading:(id)arg1;	// IMP=0x0000000101507ff0
- (void)connection:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x0000000101507f04
- (void)connection:(id)arg1 didReceiveData:(id)arg2;	// IMP=0x0000000101507e78
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;	// IMP=0x0000000101507d24
- (void)handleResponse:(id)arg1;	// IMP=0x0000000101507614
- (void)handleGotQrcode;	// IMP=0x0000000101507410
- (void)handleError:(int)arg1;	// IMP=0x00000001015072f0
- (void)startPolling;	// IMP=0x000000010150708c
- (void)stopTimeoutCheck;	// IMP=0x0000000101506fe4
- (void)startTimeoutCheck;	// IMP=0x0000000101506f64
- (_Bool)sendAuthRequest:(id)arg1;	// IMP=0x0000000101506e10
- (_Bool)StopAuth;	// IMP=0x0000000101506df0
- (_Bool)Auth:(id)arg1 nonceStr:(id)arg2 timeStamp:(id)arg3 scope:(id)arg4 signature:(id)arg5 schemeData:(id)arg6;	// IMP=0x0000000101506bf0
- (void)resetConnection;	// IMP=0x0000000101506ae0
- (void)resetAll;	// IMP=0x0000000101506a44
- (void)dealloc;	// IMP=0x00000001015069b0
- (id)init;	// IMP=0x00000001015068d4

@end

