//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WXApi : NSObject
{
}

+ (void)stopLog;	// IMP=0x0000000101516d38
+ (void)startLogByLevel:(long long)arg1 logDelegate:(id)arg2;	// IMP=0x0000000101516cf4
+ (void)startLogByLevel:(long long)arg1 logBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000101516cb0
+ (_Bool)sendResp:(id)arg1;	// IMP=0x0000000101516c50
+ (_Bool)sendReq:(id)arg1;	// IMP=0x00000001015167e8
+ (_Bool)handleOpenTypeWebView:(id)arg1;	// IMP=0x0000000101516700
+ (_Bool)handlePayInsuranceReq:(id)arg1;	// IMP=0x00000001015165f0
+ (_Bool)handleNontaxPayReq:(id)arg1;	// IMP=0x00000001015164e0
+ (_Bool)invoiceAuthInsertReq:(id)arg1;	// IMP=0x00000001015163d0
+ (_Bool)subscribeMsg:(id)arg1;	// IMP=0x000000010151628c
+ (_Bool)sendAuthReq:(id)arg1 viewController:(id)arg2 delegate:(id)arg3;	// IMP=0x00000001015161dc
+ (_Bool)handleScanResult:(id)arg1;	// IMP=0x00000001015160dc
+ (_Bool)chooseInvoiceReq:(id)arg1;	// IMP=0x0000000101515d78
+ (_Bool)chooseCardReq:(id)arg1;	// IMP=0x0000000101515998
+ (_Bool)addCardToWXCardPackageReq:(id)arg1;	// IMP=0x000000010151557c
+ (_Bool)jumpToBizWebview:(id)arg1;	// IMP=0x00000001015153d0
+ (_Bool)openProfile:(id)arg1;	// IMP=0x0000000101515238
+ (_Bool)joinChatRoom:(id)arg1;	// IMP=0x0000000101515030
+ (_Bool)createChatRoom:(id)arg1;	// IMP=0x0000000101514da8
+ (_Bool)handleLaunchMiniProgram:(id)arg1;	// IMP=0x0000000101514bc8
+ (_Bool)openRankList:(id)arg1;	// IMP=0x0000000101514b48
+ (_Bool)openWebview:(id)arg1;	// IMP=0x0000000101514a30
+ (_Bool)openTempSession:(id)arg1;	// IMP=0x0000000101514908
+ (_Bool)sendHBReq:(id)arg1;	// IMP=0x0000000101514744
+ (_Bool)auth:(id)arg1;	// IMP=0x00000001015145b8
+ (id)packResp:(id)arg1;	// IMP=0x0000000101514448
+ (id)packReq:(id)arg1;	// IMP=0x0000000101514310
+ (_Bool)handleOpenURL:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000101513f18
+ (_Bool)handleOpenTypeWebViewWithPayInsurance:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000101513da4
+ (_Bool)handleOpenTypeWebViewWithNontaxpay:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000101513c30
+ (_Bool)handleOpenTypeWebViewWithInvoiceAuthInsert:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000101513abc
+ (_Bool)handleOpenTypeWebViewWithSubscribeMsg:(id)arg1 delegate:(id)arg2;	// IMP=0x000000010151389c
+ (_Bool)handleOpenTypeWebView:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000101513740
+ (_Bool)handleOpenRankList:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000101513588
+ (_Bool)handleOpenWebviewOpenUrl:(id)arg1 delegate:(id)arg2;	// IMP=0x00000001015133d0
+ (_Bool)handleOpenTempSessionOpenUrl:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000101513218
+ (_Bool)handleChooseInvoice:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000101512da4
+ (_Bool)handleChooseCard:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000101512930
+ (_Bool)handleAddCardOpenUrl:(id)arg1 delegate:(id)arg2;	// IMP=0x000000010151247c
+ (_Bool)handleHBOpenUrl:(id)arg1 delegate:(id)arg2;	// IMP=0x00000001015122c4
+ (_Bool)handleAuthOpenUrl:(id)arg1 delegate:(id)arg2;	// IMP=0x000000010151202c
+ (id)parseURLParams:(id)arg1;	// IMP=0x0000000101511e5c
+ (_Bool)openWXApp;	// IMP=0x0000000101511dcc
+ (id)getApiVersion;	// IMP=0x0000000101511dc0
+ (id)getWXAppInstallUrl;	// IMP=0x0000000101511db4
+ (_Bool)isWXAppSupportApi;	// IMP=0x0000000101511da0
+ (_Bool)isWXAppInstalled;	// IMP=0x0000000101511d2c
+ (void)registerAppSupportContentFlag:(unsigned long long)arg1;	// IMP=0x0000000101511d20
+ (_Bool)registerApp:(id)arg1 enableMTA:(_Bool)arg2;	// IMP=0x0000000101511cb8
+ (_Bool)registerApp:(id)arg1;	// IMP=0x0000000101511ca8

@end

