//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface WXAppExtendObject : NSObject
{
    NSString *extInfo;	// 8 = 0x8
    NSData *fileData;	// 16 = 0x10
    NSString *url;	// 24 = 0x18
}

+ (id)object;	// IMP=0x000000010151961c
@property(retain, nonatomic) NSString *url; // @synthesize url;
@property(retain, nonatomic) NSData *fileData; // @synthesize fileData;
@property(retain, nonatomic) NSString *extInfo; // @synthesize extInfo;
- (void)dealloc;	// IMP=0x0000000101519594
- (id)init;	// IMP=0x0000000101519534

@end

