//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface WXFileObject : NSObject
{
    NSString *fileExtension;	// 8 = 0x8
    NSData *fileData;	// 16 = 0x10
}

+ (id)object;	// IMP=0x00000001015198a8
@property(retain, nonatomic) NSData *fileData; // @synthesize fileData;
@property(retain, nonatomic) NSString *fileExtension; // @synthesize fileExtension;
- (void)dealloc;	// IMP=0x0000000101519834
- (id)init;	// IMP=0x00000001015197e0

@end

