//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WXOMTAReachability : NSObject
{
    struct __SCNetworkReachability *_reachabilityRef;	// 8 = 0x8
}

+ (id)reachabilityForInternetConnection;	// IMP=0x0000000101540258
+ (id)reachabilityWithAddress:(const struct sockaddr *)arg1;	// IMP=0x00000001015401d8
+ (id)reachabilityWithHostName:(id)arg1;	// IMP=0x0000000101540128
- (long long)currentReachabilityStatus;	// IMP=0x0000000101540790
- (_Bool)connectionRequired;	// IMP=0x0000000101540690
- (long long)networkStatusForFlags:(unsigned int)arg1;	// IMP=0x000000010154065c
- (void)dealloc;	// IMP=0x00000001015405f8
- (void)stopNotifier;	// IMP=0x00000001015405b4
- (_Bool)startNotifier;	// IMP=0x00000001015402b8

@end

