//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface XGBaseModel : NSObject
{
    unsigned char _registerStatus;	// 8 = 0x8
    NSString *_updateTime;	// 16 = 0x10
}

@property(copy, nonatomic) NSString *updateTime; // @synthesize updateTime=_updateTime;
@property unsigned char registerStatus; // @synthesize registerStatus=_registerStatus;
- (void).cxx_destruct;	// IMP=0x00000001014d8900

@end

