//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XGKeyChain : NSObject
{
}

+ (void)delete:(id)arg1;	// IMP=0x00000001014c8198
+ (id)load:(id)arg1;	// IMP=0x00000001014c8024
+ (void)save:(id)arg1 data:(id)arg2;	// IMP=0x00000001014c7f4c
+ (id)getKeychainQuery:(id)arg1;	// IMP=0x00000001014c7ec4

@end

