//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XGPluginIDFA : NSObject
{
    id <XGIDFAProtocol> _delegate;	// 8 = 0x8
}

+ (id)getInstance;	// IMP=0x00000001014d4b54
@property(retain, nonatomic) id <XGIDFAProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001014d4c94

@end

