//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XGTPNs.h"

@interface XGTPNsRegisterEvent : XGTPNs
{
}

- (id)generateMSDKReq:(id)arg1 appID:(unsigned int)arg2 appkey:(id)arg3 account:(id)arg4;	// IMP=0x00000001014d2168
- (id)generatePublicReq:(id)arg1 appID:(unsigned int)arg2 appkey:(id)arg3 account:(id)arg4;	// IMP=0x00000001014d1698
- (void)send;	// IMP=0x00000001014d123c

@end

